### ISSUE TITLE
Table allows configuration of hyperlink column type

### ISSUE THREAD

**Issue by nate-ni** [ni/nimble#1012]
## 😯 Problem to Solve
For some columns in the table, there is a need to show an item as a hyperlink. Typically, this hyperlink will route to a new URL.

The user should be able to easily configure a static or dynamic URL for the table cell.
The user should be able to open the URL in a variety of locations similar to a typically href (_blank, _self, etc.) 

## 💁 Proposed Solution
For now, we don't need to indicate that a URL is to an external URL. This should be handled as part of a holistic enhancement to the anchor.
Assumption: The hyperlink will likely appear like a `nimble-anchor`, but refer to the visual design for finalized direction

## Open Questions
| Question | Initial Recommendation | Resolved | Decision |
|:---|:---|:---|:---|
| Do we need to indicate an external URL in some way? | No | No |  |
| Can we just use raw HTML in the string column type to achieve this? | No | No |  |
| Which width modes should we support?                                | Just fractional width, same as text column | No       |          |

## Design
- [x] #887

```[tasklist]
## 📋 Tasks
- [ ] TBD
```

**Comment by jattasNI** [comment]
As part of [a PR adding a new hyperlink column to a legacy grid](https://dev.azure.com/ni/DevCentral/_git/Skyline/pullrequest/447444) I came up with [this search to find existing SLE hyperlink column code](https://dev.azure.com/ni/DevCentral/_search?action=contents&text=%3Ca%20path%3Aweb%20ext%3Ats%20file%3A*grid*&type=code&lp=code-Project&filters=ProjectFilters%7BDevCentral%7DRepositoryFilters%7BSkyline%7D&pageSize=25&result=DefaultCollection/DevCentral/Skyline/GBmaster//Web/Workspaces/TestInsights/src/app/products/components/products-grid/products-grid.component.ts). It would be good to mine those uses for more requirements but here are a few that I noticed we'll need to consider:
- Angular router support
- support for opening links in new tab via Ctrl-click (it's not clear to me why custom code was necessary for this)
- mouse cursor changes to pointer (again, not sure why this didn't come for free)
- placeholder text that's not an anchor
- setting title to get a tooltip that matches the rendered text
