### ISSUE TITLE
Add API docs to Storybook

### ISSUE THREAD

**Issue by fredvisser** [ni/nimble#102]
## 😯 Problem to Solve

We would like to display great API documentation and maintain it in a low-effort way. This includes the entire API of a component, for example:

- element name
- property and attribute names (and how they map to each other if it's not obvious; see #824 ), types, and meaning
- event names, event data types, and their meaning
- method names, types of inputs and outputs, and their purpose
- slots
- accessibility concerns
- first class support for all of the above in each of our frameworks, where member names often differ in capitalization or other ways

## 💁 Proposed Solution

Currently we maintain some of this manually in Storybook, but a lot of it is missing and there may be better ways to autogenerate it from source. Storybook supports several tools to extract this information from the component definition and pull it into Storybook.

1. We're currently using `@storybook/html` which doesn't support autogenerated API documentation, but it should be trivial to switch to `@storybook/web-components` which does.
2. `@storybook/web-components` uses the `custom-elements-manifest` tool to extract API documentation from the component. It has support for FAST element, but [doesn't yet](https://github.com/open-wc/custom-elements-manifest/issues/71) have support for components defined on FAST foundation.

**Comment by msmithNI** [comment]
Duing the Innovation Day on 6/14/2023 I did some prototyping with TypeDoc for generating API docs from our TypeScript comments on nimble-components:
[Storybook](https://60e89457a987cf003efc0a5b-xjebzzmmzw.chromatic.com/api-docs/)  
[branch](https://github.com/ni/nimble/compare/%40ni/nimble-components_v19.3.0...innovationDay230614-apiDocs)

**Comment by m-akinc** [comment]
It's not clear to me what this is blocked on, so I'm removing the label.
