### ISSUE TITLE
Evaluate using host directives in Angular 15

### ISSUE THREAD

**Issue by mollykreis** [ni/nimble#1032]
## 🧹 Tech Debt
Once we upgrade to Angular 15, we should evaluate using HostDirectives as a way to simplify our Angular code. Some ideas/questions are:

- Can we stop extending Angular's directives in some places, such as the `RouterLinkWithHref`
- Can we consolidate repeated code? For example, can we create a "button base" or "drop down base" directives that would allow us to not have to repeat configuration that is shared in base classes within nimble-components?

**Comment by m-akinc** [comment]
@rajsite I remember you pushing back some about this being a closed issue, but I don't remember details. Do you still have reservations, or specific things you think merit further investigation?

**Comment by rajsite** [comment]
Think Molly had split the discussion and this one is fine to close
