### ISSUE TITLE
Create Table Column API documentation

### ISSUE THREAD

**Issue by atmgrifter00** [ni/nimble#1044]
## 🧹 Tech Debt

We need to create a document that users should be directed to that detail the various features of the table columns. The spec documents, as they are, do not provide the most accessible, digestible information to quickly inform users what the existing capabilities are, and how they can be extended. We should do better.

Areas that could be captured include (but are not limited to):
- The `abstract` API provided by the `TableColumn` base class, including but not limited to:
    - `column-id` -- its usages/purpose and validation associated with it
    - assigning an action menu slot to a column, how to respond to events on it
        - Do some of the action menu docs belong on the table itself since that is where the menu is slotted?
- The mixin pattern we leverage to provide column sizing behaviors/APIs
- Sort API
    - For column writers: `operandDataRecordFieldName` and `sortOperation`

- [x] Column ordering
- [x] Header content
- [x] Sorting: `sort-direction` and `sort-index`
- [x] Column id
- [x] Column sizing
- [ ] ~~Action menus (see above)~~
- [x] The `TableColumnText` class

**Comment by jattasNI** [comment]
FYI @atmgrifter00 @msmithNI the infrastructure for documenting column APIs in storybook has now been submitted. I'm not currently planning to pick up the remaining tasks in this issue (column sizing or moving the action menu docs to a column story) but you should be unblocked if you'd like to do so.
