### ISSUE TITLE
Implement pattern to enforce <myProperty>Changed() function signatures in components

### ISSUE THREAD

**Issue by mollykreis** [ni/nimble#1068]
## 🧹 Tech Debt
The FAST mechanism to get change notifications for observable properties is to create a `<myProperty>Changed` function. Currently, there is no enforcement that the function was created with the expected signature. We should change that, possibly using an approach similar to one of these:

- [opt-in specific properties to *Change signatures](https://www.typescriptlang.org/play?#code/PTAEFcBcEsBsYKYGcB0kkChIE8AODQBJAO0gQCdiBDWAeQCMkKA3CpAHgGlYqkkAaUJwTYkoBAA8yxACZiA1iID2AMyE8+APlABeUAG8MoY6ADai7KGjFQF1aAAK0AMbyuGgUJFJtAMlBIkOTWAOagvKAABgAk+hYAvgDCABZUxCEIMpEAugBcoAAUSrAyAGo04Aj53LxI5iLZoAA+ELIIKtaZgsQIAO7lsJXVHvXYjS3gbR09MgCUutrMStAyANwY8RgYIKD0SvRomM4eoABC+1YAtriwCJcIpGIkZJQ0DEzkrOQc5-SCAOTMGj-Zqgf5kQL-bSGEygXDgeiwFygIGwAD8+UCwXS61h8MRyIhkAxoGI4Eu9AouJMO3xSOcKJoKTSGRkBXm+k2sNpCPpjNgzPSmQKVExQVCoMmMnanTmBi5JjpyNRgtZIrF2LCEymssE9A1Eu10ummQ5CuMSoZRNVwrNGwwQA)
- [opt-in all properties to *Change signatures](https://www.typescriptlang.org/play?#code/PTAEFcBcEsBsYKYGcB0kkChIE8AODQBJAO0gQCdiBDWAeQCMkKA3CpAHgGlYqkkA+UAF5QAbwyhJoANoBrBNlDRioedgD2AM1DdeSUADJQSSOWUBzUL1AADACSi1AXwDCACyrFzCACY2AugD8AFygABTqsD4AajTgCKG6fHIK-qAAPhDEPgiayr4ANKDECADusbDxiTzJammZ4Nm5+T4AlMKCzOrQPgDcGE4YGCCgAMrq4OQAxggYUzX6AApU5AikYhJSuOD0sNBToOqQbhQhxeAAtvQU-YNzC6DucD6gCAAeZNlLK2uQShe4WAIC6-fQkMiUGgMJjkVjkDhPKKCcRSUDbXb7UDMGhnExmLz9VHovYHMgmM7ES7XciErY7ElYmjuTzeHwRKIVKrGUwWDJZHJ5Eo+IolcpxBLc-GWBpNQW+dqiQZE+mYo4ncjMry+dkxcWhSlXCh8xoCloKwaDIA)

Related PR discussion: https://github.com/ni/nimble/pull/1064#discussion_r1110428090

```[tasklist]
## Related PRs
- [ ] #1064 
```

**Comment by jattasNI** [comment]
Discussed with Milan and decided to close as low ROI since this should be a feature of FAST. He'll add it to his list to propose to them.
