### ISSUE TITLE
Some autotests failing in WebKit

### ISSUE THREAD

**Issue by msmithNI** [ni/nimble#1074]
## 🧹 Tech Debt
We currently have some test failures in WebKit/Safari. We should triage these to see if there's any user-visible impact (i.e. if they could be actual bugs in Nimble on WebKit/Safari) and fix them if possible.

To reproduce: `npm run test-webkit -w @ni/nimble-components`

**Note:** The drawer/dialog test failures are also present in Firefox. If we find a fix for one browser, we should test it in the other too.

Failures: 6 tests, drawer and dialog components:
- Drawer with default setup focuses the first button on the drawer when it opens FAILED
	Expected <body>...</body> to be <nimble-button id="ok">...</nimble-button>. Tip: To check for deep equality, use .toEqual() instead of .toBe().
- Drawer with default setup supports opening multiple drawers on top of each other FAILED
	Expected <body>...</body> to be <nimble-button>...</nimble-button>. Tip: To check for deep equality, use .toEqual() instead of .toBe().
- Drawer with default setup focuses the button with autofocus when the drawer opens FAILED
	Expected <body>...</body> to be <nimble-button id="cancel" autofocus current-value appearance="outline">...</nimble-button>. Tip: To check for deep equality, use .toEqual() instead of .toBe().
- Dialog focuses the button with autofocus when the dialog opens FAILED
	Expected <body>...</body> to be <nimble-button id="cancel" autofocus current-value appearance="outline">...</nimble-button>. Tip: To check for deep equality, use .toEqual() instead of .toBe().5#step:17:45)
- Dialog supports opening multiple dialogs on top of each other FAILED
	Expected <body>...</body> to be <nimble-button current-value appearance="outline">...</nimble-button>. Tip: To check for deep equality, use .toEqual() instead of .toBe().
- Dialog focuses the first button on the dialog when it opens FAILED
	Expected <body>...</body> to be <nimble-button id="ok" current-value appearance="outline">...</nimble-button>. Tip: To check for deep equality, use .toEqual() instead of .toBe().

**Comment by jattasNI** [comment]
Closing in favor of targeted bugs for each underlying issue:
- #1936
