### ISSUE TITLE
Visual Design for Column/Row Interactions

### ISSUE THREAD

**Issue by nate-ni** [ni/nimble#1086]
For more information, see the parent issue:
 - #885

**Comment by RickA-NI** [comment]
Here are the designs for review:
https://xd.adobe.com/view/1a9870c7-2510-4248-83a5-b0148e7a6763-4fcb/

**Comment by jattasNI** [comment]
The last remaining open question is the "ghost" visual appearance while dragging to reorder columns. But that dev work is not scheduled for a while so we're ok to close this.
