### ISSUE TITLE
Update Nimble usage of DesignSystem.tagFor to use component exported value

### ISSUE THREAD

**Issue by fredvisser** [ni/nimble#1095]
## 🧹 Tech Debt

As part of https://github.com/ni/nimble/pull/1078 : Enable TurboSnap for Chromatic tests - we exported DesignSystem.tagFor(ComponentClass) for each Nimble component.

We should use the new tag names consistently in Nimble instead of `DesignSystem.tagFor` where it makes sense (i.e. not for injecting the component registered to a base class but for when tags are used directly).

Looks like there are quite a few uses of DesignSystem.tagFor() in Nimble code and a couple references to it in CONTRIBUTING too: [github search](https://github.com/search?q=repo%3Ani%2Fnimble%20designsystem.tagfor&type=code).

- [x] address usages in most components #1115 
- [x] address usages in generated icons

**Comment by m-akinc** [comment]
Appears to be done
