### ISSUE TITLE
[Draft] UX design for client side search and sorting vs limited server side search

### ISSUE THREAD

**Issue by fredvisser** [ni/nimble#1129]
## 📌 Request Background

SystemLink applications often have the ability to search or sort data displayed in a table/grid. However, depending on the application, searching or sorting is either performed quickly and easily on the first page of results, or (if the service supports it) the search or sort query will do what the user expects and query the full dataset.

## Core Requirements

- We need to define a consistent table search experience that clearly communicates to customers 
  - What limitations (if any) are present in the data they are searching or sorting?
  - How to move past those limitations?
- What table search/sort capabilities are exposed?
  - I.e. If users can't sort by the entire query space, we should disable sort for the table. It's a better UX to disable than to only sort the first 100 or 1000 rows, and mislead customers.
  - 

## Prior Art

| Examples | Support search? | Notes |
|---|----|----|
| Systems Management – Systems | Supports frontend search with toolbar search field. Supports server side search with query builder | |
| Test Insights – Product & Results | Both support server side search with query builder | |
| Utilities – Files | Supports server side search with query builder | |
| Analysis & Reporting – Routines | Doesn't support search | |
| Analysis & Reporting – Executions | Supports server side search with query builder | |
| Access Control – Roles, Workspaces, Users | Supports server side search with toolbar search field | |

## Acceptance Criteria

Recommendation for…

- [ ] IxD Spec submitted (link)
- [ ] Visual Design work item created with latest requirements

**Comment by rajsite** [comment]
FYI @fredvisser related to this there is a prototype / discussion around implementing client side search in [Skyline PR 655380](https://dev.azure.com/ni/DevCentral/_git/Skyline/pullRequest/655380#1709668975).

Don't think it really addresses the topic of this issue (clear UX about client vs server side search) but might just become another example for the prior art table.

**Comment by fredvisser** [comment]
The [Filter, Query, & Search pattern](https://stratus-storybook.ni.dev/?path=/docs/patterns-filter-query-and-search--docs) is my current attempt at resolving these questions and bringing consistency to SystemLinks apps. Closing this issue.
