### ISSUE TITLE
NimbleComboboxListOptionDirective should use `text`, not `textContent`.

### ISSUE THREAD

**Issue by atmgrifter00** [ni/nimble#1136]
# 🐛 Bug Report

## 💻 Repro or Code Sample

As described in #1135, for clients to have the ability to create a `ListOption` variant that hosts more complex content, the `NimbleComboboxListOptionDirective` must alter its implementation to use the `text` property on the `ListboxOption` class, instead of bypassing it to use `textContent` instead. The `text` property ultimately just wraps the `textContent` (in FAST's implementation), but by going through the `text` property we allow overrides of `text` to provide the necessary `textContent` from some other node in the DOM.

## 🤔 Expected Behavior

Selecting items in the combobox that have complex visual content still work within forms.

## 😯 Current Behavior

If a combobox contains options with complex content, then the form bindings will not function as expected.

## 💁 Possible Solution

[Solution prototype branch](https://github.com/ni/nimble/tree/combobox-rich-content-list-option)

## 🔦 Context

Trying to unblock a [client request](https://dev.azure.com/ni/DevCentral/_git/Skyline/pullRequest/454075#1679409016).

**Comment by pakdev** [comment]
I just wasted time trying to figure out why my selected option was coming up "Symbol(not found)" only to realize my HTML was formatted like:

```
<nimble-list-option *ngFor="const item of items$ | async" [ngValue]="item">
    {{ item?.name }}
</nimble-list-option>
```

vs.

```
<nimble-list-option *ngFor="const item of items$ | async" [ngValue]="item">{{ 
    item?.name 
}}</nimble-list-option>
```

This caused my optionMap keys to have beginning/trailing spaces, so no options were being matched. I think using `text` vs `textContent` fixes this, but until then, we should trim `textContent`.

**Comment by rajsite** [comment]
I think this is easy to trip up on and should be addressed sooner independently of complex content support. Marking for triage.
