### ISSUE TITLE
Radio button keyboard focus indicator doesn't scroll with control

### ISSUE THREAD

**Issue by jattasNI** [ni/nimble#1143]
# 🐛 Bug Report

The radio button shows a thick border when you give it tab focus but that border is positioned on the page at the component's original location and doesn't move if the component scrolls.

## 💻 Repro or Code Sample

1. Open the Angular example app in a browser window that is tall enough for the radio button to appear on screen when the page loads.
2. Tab until it has focus
3. Scroll the page

## 🤔 Expected Behavior

Thick focus ring moves with the radio button
![image](https://user-images.githubusercontent.com/10500124/228956616-04f0827c-d8bb-4275-8999-3fd1ca466ff3.png)

## 😯 Current Behavior

Focus ring stays at the same screen location while the component scrolls away
![image](https://user-images.githubusercontent.com/10500124/228956689-5a86868a-9a65-4529-b96b-b6a5244e84d6.png)

## 💁 Possible Solution

The focus indicator is an `:after` pseudo element. It probably needs to be positioned differently relative to its parent.

## 🌍 Your Environment

* OS & Device: macOS
* Browser: Reproduced in Safari, Chrome, Firefox

**Comment by rajsite** [comment]
Doesn't show up for me at all in Safari 16.4 lol

<img width="454" alt="image" src="https://user-images.githubusercontent.com/1588923/228959799-492f339b-91fa-44d4-843d-00a59ea1beed.png">

**Comment by jattasNI** [comment]
@rajsite is it possible your browser window wasn't tall enough for the radio buttons to be on screen when the page first loaded? In that situation the focus indicator is permanently scrolled offscreen. I saw the same behavior when trying to reproduce in other browsers and thought at first that it was a difference in browser behavior before realizing it was a difference in how big my browser windows were.

But for the record I reproduced it in 16.3 and haven't tried 16.4 so it could be version-specific.

**Comment by rajsite** [comment]
> @rajsite is it possible your browser window wasn't tall enough for the radio buttons to be on screen when the page first loaded?

That appears to be the case! And you call that out in the repro steps so woops, my bad. I can reproduce the exact behavior shown in 16.4
