### ISSUE TITLE
Address Table accessibility issues

### ISSUE THREAD

**Issue by atmgrifter00** [ni/nimble#1151]
## 📌 User Story

The table needs the correct ARIA role.

Once the [table row grouping PR](https://github.com/ni/nimble/pull/1139) goes through, there will be some accessibility issues that will require some follow up work on (some of which will possibly be part of the [Table Interaction Keyboard](https://github.com/ni/nimble/issues/1137) work). Some of the issues raised include:
- Determine what the appropriate role for the `TableGroupRow` is ([ARIA guidance](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/rowgroup_role) strongly suggests that the `rowgroup` role is only appropriate for DOM elements that actually contain `row` (or other) elements, which our `TableGroupRow` does not).
- Determine what the appropriate focus interactions are for the expand/collapse button. We've had some direction that the expand/collapse button shouldn't be focusable, but this seems in conflict with some [expected ARIA behaviors](https://github.com/ni/nimble/pull/1139#discussion_r1152345869).
- ~~Assuming the expand/collapse button remains a button, we will need to create an API for users to supply it an accessible label, much like we did for the [action menu label](https://github.com/ni/nimble/blob/84efdc79ad9dc586b1a32cc3a5f4b39fbee18257/packages/nimble-components/src/table-column/base/index.ts#L32) (except likely exposed on the `Table`).~~ [Addressed in #1519]
- Configure `aria-expanded` on the group rows, but this requires the table itself to have a role of `treegrid`. Some questions about this:
    -  Should the table always be `treegrid` or should the role change based on whether or not a column is grouped and whether or not hierarchy is enabled?
    - Does `aria-expanded` make sense on group rows if the rows beneath it are not child elements in the DOM?
- ~~Add accessible label to the selection checkboxes in the multi-select case. This should probably be done in a consistent manner as adding a label to the expand/collapse button for group rows.~~ [Addressed in #1519]

Note: The localization concerns described above are also captured in #1090 

Note: When this is fixed, we can also address #1195.

**Comment by atmgrifter00** [comment]
@leslieab, we will likely need to revisit some of the decisions surrounding focus behaviors for the expand/collapse button (see the description above).

**Comment by atmgrifter00** [comment]
@leslieab, it would only raise warning for interactive elements like buttons. At the moment, the header has no such elements.

**Comment by leslieab** [comment]
@msmithNI So do the grids from [Telerik](https://demos.telerik.com/blazor-ui/grid/overview), [AG Grid](https://www.ag-grid.com/example/), and [MUI X](https://mui.com/x/react-data-grid/row-grouping/) just throw accessibility errors? All of them have clickable header elements that are not focusable.

**Comment by msmithNI** [comment]
The AG Grid and MUI X grids that you linked do have the same accessibility warnings on their column headers. The Telerik Blazor Grid doesn't, not sure why, maybe the click handlers are being handled at a higher level than the column headers.

It's worth noting that the grids still work fine for end users in Firefox. You only see the accessibility warnings we're talking about if you open the Inspector / Developer Tools, go to the Accessibility tab, and click Check for Issues > All Issues (or Keyboard):
![AGGridAccessibility](https://user-images.githubusercontent.com/20709258/229941683-c04f4161-367f-4a53-8af2-609cbfc87896.png)

**Comment by leslieab** [comment]
Thanks, I opened the inspector but wasn't sure where to check for those. Is the goal not to have any accessibility errors (and therefore we need to fix this)? Or should we discuss/test this with keyboard navigation/screen reader users to determine whether it's an actual usability issue?

**Comment by msmithNI** [comment]
I don't think we have a hard-and-fast rule about having no accessibility warnings/errors ( @jattasNI @rajsite might have a better answer here), but we try to address them if we can. For this one, I assume the concern is that clickable-but-unfocusable elements wouldn't show up to a screen reader as being interactable.

**Comment by leslieab** [comment]
I can't find anything online that suggests there's ever a use case for ignoring this error. The fact that the grid examples I've been using do so is probably an example of what Jim Allan was talking about when he said "people don’t have a lot of expectations [of grids] other than they’re usually coded poorly and they don’t work."

I am going to need to go back and re-examine my wireframes for areas where we are doing this and come up with recommended approaches to add focus back in, which I will not be able to do until next week at the earliest. Is this currently blocking anyone, or can it wait until the week of 17th?

**Comment by msmithNI** [comment]
I think it can wait / is not currently blocking anything. (I'll also be OOO next week and the following week)

**Comment by msmithNI** [comment]
@leslieab I wanted to circle back and see if you had any updates regarding focusability for the interactive parts of the table (clicking column headers for sorting, etc).

I should have interactive sorting implemented at the beginning of next week, so I'm just wondering what the impact would be to that (or interactive grouping / column header menus, which we may start implementing soon). Thanks.

**Comment by atmgrifter00** [comment]
Closing this issue by addressing the remaining noted items from the description in the following ways:
- `TableGroupRow` has a `role` or `row`
- Expand/collapse button focus behaviors will be addressed as part of #1137 
- `Table` now has a `role` of `treegrid`, and `aria-expanded` is being set on `GroupRows` (and `Rows`) accordingly
