### ISSUE TITLE
Nimble Picker

### ISSUE THREAD

**Issue by ranjgith-ni** [ni/nimble#1164]
## 😯 Problem to Solve

The [PDV app in SLE](https://dev.azure.com/ni/DevCentral/_git/Skyline?path=/docs/design-documents/Test-Insights/Query-and-visualize-parametric-data.md&_a=preview) was planned to use `nimble-picker` to display the selected axis for the plots.

We were able to find the designs available and some part of development being done in one of the [pulls](https://github.com/ni/nimble/pull/484)

![image](https://user-images.githubusercontent.com/99422861/230320904-4eb55fd0-5cbf-4803-b7ed-0b964d8a3f50.png)

Currently, as the component is not yet available, we decided to go with comma-separated values to display the selections, which has a questionable UX for removing a selection and handling errors if any of the selections becomes invalid due to the change in data

## 💁 Proposed Solution

1. Can we prioritize or continue the development of the picker component?
2.  If not considered already, picker should be able to highlight the invalid values in different color

**Comment by jattasNI** [comment]
@ranjgith-ni thanks for providing your requirements! We actually have an existing picker issue so I'm going to move your notes over there and close this one as duplicate. I'll also respond there about where this fits in our priorities. #458
