### ISSUE TITLE
Intermittent test "Table uses virtualization and calls focusedRecycleCallback on focused cell views when a scroll happens"

### ISSUE THREAD

**Issue by jattasNI** [ni/nimble#1165]
# 🐛 Bug Report

One of our table virtualization tests is intermittent. I saw it fail in the build linked below when submitting a documentation change.

```
and calls focusedRecycleCallback on focused cell views when a scroll happens
     Table uses virtualization
     Expected spy focusedRecycleCallback to have been called once. It was called 0 times.
    at <Jasmine>
    at UserContext.<anonymous> (/tmp/_karma_webpack_986422/webpack:/@ni/nimble-components/src/table/tests/table.spec.ts:610:39)
```

## 💻 Repro or Code Sample

https://github.com/ni/nimble/actions/runs/4623340359/jobs/8177052896?pr=1161

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* Version [e.g. 1.8.0]

**Comment by mollykreis** [comment]
I don't believe the intermittency in this test still exists. I've added the triage tag so that we can decide if we're happy closing this bug with that resolution, or if anyone has continued seeing this test failure.
