### ISSUE TITLE
Add File-Extract_16x16 icon to the development Nimble Icon Tokens

### ISSUE THREAD

**Issue by NIbokeefe** [ni/nimble#1179]
Please add the attached file: File-Extract_16x16.svg icon to the Nimble development token library.

Process Instructions:
**Steps 1-3 (extracting icons from adobe illustrator file) have been completed**
https://github.com/ni/nimble/blob/main/packages/nimble-tokens/CONTRIBUTING.md#updating-icons

@jattasNI @fredvisser 

![File-Extract_16x16](https://user-images.githubusercontent.com/106594349/231005885-3ff5a82d-39ae-4e5b-b7a5-ce0f680c08f8.svg)

**Comment by jattasNI** [comment]
Looks like this was addressed in #1177
