### ISSUE TITLE
Unable to set `id` or `class` on NimbleTabs Blazor component

### ISSUE THREAD

**Issue by tatwood2** [ni/nimble#1191]
# 🐛 Bug Report

While trying to set a height on the Blazor NimbleTabs component in my application, I found I can't set the `id` or `class` attribute.  Talking with @atmgrifter00, this is because we have an error with the `AdditionalAttributes` property, specifically we are missing the `CaptureUnmatchedValues` attribute.  I found https://github.com/ni/nimble/issues/751 which requests that someone creates a base class that exposes the typed properties but meanwhile, I'd still like to customize the `NimbleTabs` Blazor component in my application.

## 💻 Repro or Code Sample

Open the NimbleBlazor.sln and open the `ComponentsDemo.razor` file.  Navigate to the first `NimbleTabs` component and add `id="foo"`.  Launch the application and see the `Object of type 'NimbleBlazor.NimbleTabs' does not have a property matching the name 'id'.` error.

## 🤔 Expected Behavior

I should be able to set the `class` or `id` properties on the Nimble Tabs control so I can provide custom CSS.

## 😯 Current Behavior

You get the Blazor error: `"Object of type 'NimbleBlazor.NimbleTabs' does not have a property matching the name 'id'.` when trying to customize the CSS with the `id` or `class` property.

## 💁 Possible Solution

It looks like we missed adding the `[Parameter(CaptureUnmatchedValues = true)]` attribute to the `AdditionalAttributes` property on three components.
1. https://github.com/ni/nimble/blob/main/packages/nimble-blazor/NimbleBlazor/Components/NimbleTabs.razor.cs
2. https://github.com/ni/nimble/blob/c6c858b27deee7eb897a0be87f015e8c0fa860a4/packages/nimble-blazor/NimbleBlazor/Components/NimbleBreadcrumbItem.razor.cs
3. https://github.com/ni/nimble/blob/c6c858b27deee7eb897a0be87f015e8c0fa860a4/packages/nimble-blazor/NimbleBlazor/Components/NimbleTreeView.razor.cs

However, the best solution is probably the base class approach outlined in https://github.com/ni/nimble/issues/751.  We could temporarily add the attribute to these classes as a stopgap solution for now.

## 🔦 Context

I am trying to set a height on the NimbleTabs component.

## 🌍 Your Environment

* OS & Device: Windows
* Browser Latest Google Chrome

**Comment by rajsite** [comment]
@tatwood2 My thoughts are that our current pattern is to do `[Parameter(CaptureUnmatchedValues = true)]` on the AdditionalAttributes and I don't think those spots intentionally left the attribute off. So a patch to add those attributes makes sense. A PR to make that change should be trivial.

It would be nice to have a simple test that exercises our current AdditionalAttributes behavior for each component as well (that dumping on additional properties doesn't error). I don't see an exisiting test so we could either include those tests in the PR to add the attribute (if you have the time) or make a separate tech debt task to add those tests.

I don't think the strongly typed base class idea in https://github.com/ni/nimble/issues/751 is fully formed enough yet. We probably need to do a survey to see what attributes are being typed and form a strategy. Probably needs an HLD to discuss the approach before tackling. Don't think it's ready to pick-up yet. Any additional thoughts @atmgrifter00 ?

**Comment by atmgrifter00** [comment]
Nope, that's a complete summary.
