### ISSUE TITLE
Migrate hard-coded tokens to new base tokens

### ISSUE THREAD

**Issue by rajsite** [ni/nimble#1192]
## 🧹 Tech Debt

With the completion of #1183 we can now add new base design tokens to nimble in style dictionary. Some tokens we need to add are:
- [ ] The tokens defined in `design-tokens-static`, see discussion https://github.com/ni/nimble/issues/370#issuecomment-1233423198. After which we can remove design-tokens-static.
   - Update April 2024, We can actually just switch back to normal token usage and delete the static tokens once [CSS ::backdrop inheritance](https://caniuse.com/mdn-css_selectors_backdrop_inherit_from_originating_element) is available in all our browsers (late 2024). 
- [x] The fallback font definitions:  https://github.com/ni/nimble/blob/7118a210663789426b00d7817371924b0d8ea0e0/packages/nimble-components/src/theme-provider/design-tokens.ts#L104-L122
   - fixed by merging fallback font into font and font-family in #2033

**Comment by jattasNI** [comment]
Assigned to @rajsite to update the proposed pattern for fallback fonts. We shouldn't need to expose tokens, we can just include the fallback fonts in the primary font token values.

**Comment by rajsite** [comment]
Remaining work captured in https://github.com/ni/nimble/issues/1835
