### ISSUE TITLE
Figma Nimble Library is cluttered with unofficial components - Visual Design

### ISSUE THREAD

**Issue by NIbokeefe** [ni/nimble#1202]
The Figma library was created during an innovation day.  The library has tests and a lot of clutter that is not associated to official/finished nimble components.

1. Branch the library and create better organization so only the correct components to use are obvious.
2. Components need to be built on individual pages

**Comment by jattasNI** [comment]
The [latest Nimble Components Figma](https://www.figma.com/file/PO9mFOu5BCl8aJvFchEeuN/Nimble_Components?type=design&node-id=1295-77205&mode=design&t=xjf24rIUqKsuHqLG-0) is looking very official!

**Comment by NIbokeefe** [comment]
Thank you, this goal was for sure achieved!
