### ISSUE TITLE
Table interactive sorting (via column header menus)

### ISSUE THREAD

**Issue by msmithNI** [ni/nimble#1222]
See #854 which captures the other part of interactive sorting (via clicking the headers).

See #885 for the UX/IxD design for sorting via the header menus.

## 📌 User Story
- [ ] Interactive sorting via header menu (not started, header menu is also needed for #867 )

**Comment by fredvisser** [comment]
Adding column header menus is not a near to medium priority for the nimble-table. In Stratus apps, we have other shared components to configure columns, so don't require this capability.
