### ISSUE TITLE
Add Nimble icons to token library and update File Extract 

### ISSUE THREAD

**Issue by NIbokeefe** [ni/nimble#1237]
Add the new SVG icons:
Export_16x16
Import_16x16

![Import_16x16](https://github.com/ni/nimble/assets/106594349/cc565e7a-a196-4df3-92e9-9192b6ba2188)
![Export_16x16](https://github.com/ni/nimble/assets/106594349/dd5b3e55-ceb3-4c4a-b27b-1d6dae81b165)

Update the following token which is currently name "File export":
File-Extract_16x16

![File-Extract_16x16](https://github.com/ni/nimble/assets/106594349/5d857f24-a984-454d-8532-faafb0d327f5)

File extract was previously mis-named "file export" when published to the dev token library.  This needs to be updated to File-Extract_16x16.  I've included a new SVG for this in case it's easier replacing vs updating the naming. 

The first 3 steps have been completed and files are attached:
https://github.com/ni/nimble/blob/main/packages/nimble-tokens/CONTRIBUTING.md#updating-icons

@jattasNI @fredvisser

**Comment by fredvisser** [comment]
Fixed by https://github.com/ni/nimble/pull/1242
