### ISSUE TITLE
Anchor column doesn't work as expected with the Angular router

### ISSUE THREAD

**Issue by mollykreis** [ni/nimble#1238]
# 🐛 Bug Report

The `nimble-table-column-anchor` element doesn't work correctly with the Angular router. Specifically, if you set an href in your data that works with the browser's navigation (e.g. CTRL+CLICK) then it doesn't work correctly with the Angular router and vice versa. This problem is definitely apparent when your Angular application is configured to have a base href, but it might manifest itself with other configurations as well.

My understanding of the problem is this:
- In normal circumstances, configuring a `routerLink` (or `nimbleRouterLink`) on an element in Angular uses the router link to calculate the `href` attribute to set on the element. This calculation is done by using the router.
- In the case of the anchor column, we are setting the `href` on the underlying anchor element and then the Angular directive assumes the `href` is also the valid `routerLink`. This is not a valid assumption.

## 🤔 Expected Behavior

I should be able to configure my anchor column with an href that will work with the Angular router and with CTRL+CLICK on the link (even if my application has a base href).

## 😯 Current Behavior

If my application has a base href, I have to choose if I want CTRL+CLICK to work or regular clicking (which uses the Angular router).

## 💁 Possible Solution

We could stop assuming that the href specified is a valid Angular router link and instead do something like what we do in the navigation tree -- try navigating the with router and falling back to updating the document's location.

Note: Whatever the final solution, we should ensure that we appropriately document whether the href specified in an Angular app is the router link or the href needed for navigation outside of the Angular router.

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* Version [e.g. 1.8.0]

**Comment by rajsite** [comment]
> We could stop assuming that the href specified is a valid Angular router link and instead do something like what we do in the navigation tree -- try navigating the with router and falling back to updating the document's location.

The [anchor-tree-item](https://github.com/ni/nimble/blob/65a8a1b9cb43209d80161fb84f2f783ae3e34245/angular-workspace/projects/ni/nimble-angular/src/directives/anchor-tree-item/nimble-anchor-tree-item-router-link-with-href.directive.ts#L18) seems to directly extend [RouterLinkWithHref](https://github.com/angular/angular/blob/14.3.x/packages/router/src/directives/router_link.ts#L309). Is the fallback behavior described what's defined by Angular's RouterLinkHref or is there something else doing that? I guess I'm hoping (?) that we aren't needing custom logic outside of the RouterLinkHref for the navigation tree.

**Comment by mollykreis** [comment]
For the navigation tree, we don't leverage `nimbleRouterLink`, we directly set the `href` on the `anchor-tree-item` elements and then there is custom code that determines whether or not to use the router or to let the link navigate with its default behavior. The reason there is that some tree items point to links within the current app and therefore can use the router, but some tree items point to links outside of the app and therefore cannot use the router. We can make a best guess of which is which from looking at the routes, but in the end, it's only a guess.

**Comment by mollykreis** [comment]
For the navigation tree, we don't leverage `nimbleRouterLink`, we directly set the `href` on the `anchor-tree-item` elements and then there is custom code that determines whether or not to use the router or to let the link navigate with its default behavior. The reason there is that some tree items point to links within the current app and therefore can use the router, but some tree items point to links outside of the app and therefore cannot use the router. We can make a best guess of which is which from looking at the routes, but in the end, it's only a guess.
