### ISSUE TITLE
Nimble combobox filter not updated on programmatically changing the value.

### ISSUE THREAD

**Issue by saikrishnan-ni** [ni/nimble#1266]
# 🐛 Bug Report

The filter for nimble combobox's filtered options stays the same after programmatically changing the combobox's value.

## 💻 Steps to recreate the behavior

Select an options from the combobox, manually delete a character from the input and select the previous option again. 
Now change the combobox's value programmatically, either through devtools console or angular component(using combobox's element reference)
Now when clicked on the combobox it will show the previosly selected value in the below list option

## 🤔 Expected Behavior

When we change the selected option from the list option either via typing or selecting from the list by clicking and later update it programmatically, it should either display the list options or the selected option when clicked on it.

## 😯 Current Behavior

When we type something in the dropdown and then select an option from the filtered list, the filter text remains the same even after the combobox value is programmatically changed and when we click back on the combobox it still shows the previously filtered options list which doesn't seems relevant to the selected value. Attached gif below for reference
![NimbleComboboxFilter](https://github.com/ni/nimble/assets/123591928/4ceb5dcf-4ee1-484d-b35e-4d2de1fa4ace)

## 💁 Possible Solution

The filter could be reset to empty string on changing the combobox's value.

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* Version [e.g. 1.8.0]

**Comment by atmgrifter00** [comment]
I'll note that this is a FAST issue (which I will be filing one against them soon). Unfortunately, this isn't easy to workaround as the filter state that is causing this behavior is private and inaccessible to our implementation. Nor is there a good way for us to override behavior to subvert/alter changes to that private state. At the moment this appears like something that will have to be addressed in FAST directly, which will obviously delay when a fix will be available.

**Comment by m-akinc** [comment]
It seems like there are a number of inconsistencies with how the combobox sets or clears its filter, e.g. based on whether you open the dropdown with a click or down arrow. I believe @atmgrifter00 will be trying to enumerate some of those problems in the issue he files to FAST. In the meantime, I think we can provide a stop-gap solution by modifying the private filter member like this: `this['filter'] = ...`. It's dirty to have to do that, but it seems worth doing to resolve a problem that clients have no other workaround for.
