### ISSUE TITLE
Filterable `NimbleSelect`.

### ISSUE THREAD

**Issue by atmgrifter00** [ni/nimble#1273]
## 😯 Problem to Solve

We are seeing a lot of requests from clients to have a filterable dropdown component that supports model values associated with each option (in Angular), with no need for arbitrary value support. Ideally, this filtering would allow for _any_ string matching within the text of each displayed option.

## 💁 Proposed Solution

Add new typing-based filtering to the `NimbleSelect`. Behaviorally, it could operate in a very similar fashion to [this dropdown component](https://select2.org/dropdown). The key addition here is a new input area in the dropdown itself allowing a user to type. This likely should be a _conditional_ ability of the `Select` as well, allowing a user to not always have a dedicated area for a user to type.

[Prototype branch](https://github.com/ni/nimble/tree/filterable-select) (and [Storybook](https://60e89457a987cf003efc0a5b-ldjwdkyulp.chromatic.com/?path=/story/components-select--underline-select))

[Initial visual designs (WIP)](https://www.figma.com/file/PO9mFOu5BCl8aJvFchEeuN/Nimble_Components?type=design&node-id=1529-41777&mode=design) -- see references to "filter" in WIP Experiments section

**Comment by jattasNI** [comment]
One use case where this came up was the SLE user picker. It would be good to be able to type a user's first or last name to narrow the list of visible users. [Discussion on Teams here](https://teams.microsoft.com/l/message/19:a045e5de02a8458484bd3705ac3df6ed@thread.skype/1679332622128?tenantId=87ba1f9a-44cd-43a6-b008-6fdb45a5204e&groupId=41626d4a-3f1f-49e2-abdc-f590be4a329d&parentMessageId=1679332622128&teamName=ASW%20SystemLink&channelName=LIMS%20UI-UX&createdTime=1679332622128)

**Comment by atmgrifter00** [comment]
Some observations made while demoing the prototype:
- We should place the filter input at the bottom of the popup if the popup is shown above the component. Otherwise the input would bounce around as the user types.
- We should perhaps stop updating the display text of the select as the user navigates the dropdown via the arrow keys.
    - A corollary to this would be that we need to visually distinguish between the current selected item and items that are currently focused in the drop-down via the key navigation.

**Comment by jattasNI** [comment]
## Interaction design questions

1. What gestures can the user make to focus the filter input text box? Click in it? Tab to it? It gets focus when the select is opened?

We plan to have the dev team make a proposal and run it by IxD.

**Comment by jattasNI** [comment]
Filterable select came up again in [this SLE HLD for scheduling test plans](https://dev.azure.com/ni/DevCentral/_git/Skyline/pullRequest/565673#1695848003)

**Comment by fredvisser** [comment]
@NIbokeefe - Is there just some bookkeeping work remaining on the filterable Select component? I.e. Move the move the chosen design to the Select page in the Figma doc?

**Comment by NIbokeefe** [comment]
Yes, @fredvisser the design for it is complete and represented in the nimble-menu in Figma.  I either make a property on the select that toggles the filterable option on, or just represent that feature in the documentation portion.  Either way, when using the figma select you can choose the filterable option from the menu property.
