### ISSUE TITLE
Storybook links from README are broken

### ISSUE THREAD

**Issue by mollykreis** [ni/nimble#1296]
# 🐛 Bug Report

The storybook links from the repo's readme are broken. They take you to storybook, but it is an error page of storybook rather than the correct component. I think this is related to #1292 where components are now organized under `components` or `incubating`.

## 🤔 Expected Behavior

Storybook links should work from the readme

## 😯 Current Behavior

Storybook links take you to storybook where you can find the component in the navigation tree, but the links don't initially take you to where they should.

## 💁 Possible Solution

Update the links in the table in the readme.

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* Version [e.g. 1.8.0]

**Comment by rajsite** [comment]
What if we moved the component status table into storybook instead of being in the README?
```
Getting Started
Component Status
Components/
Incubating/
Tokens/
Tests/
```

Have a feeling it'll be easier to catch errors / double check in reviews. Also we have a nice table that supports links and soon enough icons :)
