### ISSUE TITLE
Add a way to show a progress indicator while fetching items for select

### ISSUE THREAD

**Issue by jattasNI** [ni/nimble#1311]
## 😯 Problem to Solve

Some clients need to do a network request to request select items based on the current filter. While waiting for that request to complete they would like to show a spinner that indicates something is happening.

[This SLE PR](https://ni.visualstudio.com/DevCentral/_git/Skyline/pullrequest/502815) implements a workaround for this by slotting something into a list option.

![image](https://github.com/ni/nimble/assets/10500124/9aed2de5-4fa9-423d-98e3-1a9733049e74)

## 💁 Proposed Solution

1. Come up with Visual Design guidance for where the indicator should go (Brandon is looking at that on the linked PR)
    - Brandon's initial prototypes (screenshot below) [Nimble_Components Combobox WIP_Experiments](https://www.figma.com/proto/PO9mFOu5BCl8aJvFchEeuN/Nimble_Components?type=design&node-id=2229-79038&scaling=min-zoom&page-id=1529%3A41777)
3. Implement that guidance with documentation, testing, and possibly new APIs in Nimble
4. Ensure clients with workarounds adopt the new implementation

![image](https://github.com/ni/nimble/assets/10500124/414f7518-dfca-44eb-8bc6-7098152867ba)

**Comment by m-akinc** [comment]
Leaving combobox side of this for later

**Comment by jattasNI** [comment]
I split the combobox work into #2277.
