### ISSUE TITLE
Nimble-drawer closes after presing cancel on input of type file

### ISSUE THREAD

**Issue by CuckooHashing** [ni/nimble#1316]
# 🐛 Bug Report

Closing the file explorer popup in any way (other than by clicking 'Open') makes the `nimble-drawer` close as well.

## 💻 Repro or Code Sample
Steps to reproduce: 
- in the files grid in a Chrome browser, open the 'Upload files' slide out
- choose browse for files, as that open the file input
- close the file input in any way without selecting a file
- the slide out is now closed

## 🤔 Expected Behavior
The file input's state should have no bearing on the drawer's, regardless of browser.

## 😯 Current Behavior
It seems to be an issue with the inner `nimble-drawer` (that is, the one the `sl-slide-out` is wrapper over), as the code which handles the closing of the `sl-slide-out` is never called; even if one were to comment out that code, the slide out still closes. This behaviour cannot be reproduced on Firefox, but the bug still appears on Chrome and Edge.

Note that the slide out where this occurs has `preventDismiss` active.

Here's a demo of the behaviour, where all code from the `sl-slide-out` that closes the drawer has been commented out to better illustrate the abnormality:

![cancelFileInputClosesDrawer](https://github.com/ni/nimble/assets/61456916/a1e40606-373e-4b29-ba00-02ca8ff1dde6)

## 🔦 Context

Due to the fact that the code which handles the closing of the slide out is never called, an event that tells the parent components that the slide out has closed is never fired. Thus, the parent components consider the slide out open and do not open it again (i.e. in this case, the upload files button appears to be malfunctioning when it is working as intended).

**Comment by CuckooHashing** [comment]
**Update:** 

After some investigation it turns out that the problem is with the inner (native) dialog, as described in this [Chromium issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1442824). They have a fix ready, but I suppose it hasn't yet been released. 

@jattasNI I don't know what the next steps should be (regarding this nimble bug, I mean), as we'd rather wait for the fix to be released.

**Comment by rajsite** [comment]
> **Update:**
> 
> After some investigation it turns out that the problem is with the inner (native) dialog, as described in this [Chromium issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1442824). They have a fix ready, but I suppose it hasn't yet been released.
> 
> @jattasNI @rajsite I don't know what the next steps should be (regarding this nimble bug, I mean), as we'd rather wait for the fix to be released than introduce any workarounds.

Good find @CuckooHashing!
From that issue, one of the [linked duplicate issues](https://bugs.chromium.org/p/chromium/issues/detail?id=1446591) says that the fix will ship in Chrome 115 which is scheduled to release [July 12](https://chromestatus.com/roadmap).

I think waiting for the release makes sense. This nimble bug could be used for validation. You could either wait for release to validate and close the issue or try the chrome beta which should already have the fix to validate.

**Comment by m-akinc** [comment]
Validated fixed in Chrome 115
