### ISSUE TITLE
Nimble combobox doesn't scroll down to the selected option

### ISSUE THREAD

**Issue by ipopa144** [ni/nimble#1325]
# 🐛 Bug Report

When using the nimble combobox component with `autocomplete="inline"` option, if the dropdown doesn't fit on the screen, when typing a value, the option is selected, but it doesn't scroll down such that the user can see that the option is selected.

## 💻 Repro or Code Sample

```
<nimble-combobox
    formControlName="..."
    placeholder="Select or enter workspace"
    autocomplete="inline"
    error-text="text"
    [error-visible]="!valid">
...
</nimble-combobox>
```

## 🤔 Expected Behavior

The component should scroll down to the selected value if it is not visible on the screen.

## 😯 Current Behavior

![workspace-selector-bug](https://github.com/ni/nimble/assets/44372517/853b312c-783c-4a0d-b6cd-2d05e6b830ad)

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* Version [e.g. 1.8.0]

**Comment by atmgrifter00** [comment]
This is, indeed, an issue in FAST. While I think we can go ahead with a solution in Nimble, I've still created an [issue in FAST](https://github.com/microsoft/fast/issues/6776).
