### ISSUE TITLE
Consistent box-sizing configuration

### ISSUE THREAD

**Issue by rajsite** [ni/nimble#1326]
## 🧹 Tech Debt

We are currently a bit scattershot in where and how we configure the box-sizing mode of nimble-components.
We should be more consistent like with some helper that can do a minimal CSS reset in shadow roots for box-sizing.

We likely should also have recommendations for apps to configure their box-sizing modes more globally but that is outside the scope of this work item.

Proposal:

- [x] Have each application use a custom `display` helper in their `:host` styles #2114
- [ ] Update the display helper to also apply `box-sizing: border-box` to all elements in the shadow root consistently https://github.com/ni/nimble/pull/2184

**Comment by jattasNI** [comment]
Assigned to @rajsite to add more detail to the proposal:
1. what mechanism do we use to do the css reset
2. what's the default value we want for box-sizing
3. what's the per-component work
