### ISSUE TITLE
Allow anchor components to indicate that they represent external links.

### ISSUE THREAD

**Issue by atmgrifter00** [ni/nimble#1331]
## 😯 Problem to Solve

It can be helpful to provide visual context to a hyperlink that it is representing an external link. We should consider adding this ability to our anchors. Here is an example of such a visualization that Wikipedia uses:

![image](https://github.com/ni/nimble/assets/26874831/77d48942-eac9-4227-bf1a-a3e5ae87574e)

## 💁 Proposed Solution

Perhaps this is simply an extra attribute we provide for our anchor components (e.g. `external: boolean`). We would then just style the anchor to include the extra visual based on that attribute's presence.

**Comment by leslieab** [comment]
From a Figma video I was watching.

![Image](https://github.com/ni/nimble/assets/28602266/ef5a6e14-73f4-4ef0-beb1-67d916f034ae)

**Comment by fredvisser** [comment]
We _will_ support an icon to indicate that the link will open in a new tab/context (#1412), but won't support an icon for external links.

- If external links are opened in new tabs, they can use the new tab icon. 
- Using icons to indicate external links is not a common pattern.
- Detecting whether user generated links are external within frontend code is brittle.
