### ISSUE TITLE
Button doesn't set aria-disabled attribute when it is disabled

### ISSUE THREAD

**Issue by jattasNI** [ni/nimble#1339]
# 🐛 Bug Report

Many Nimble components (for example the [switch](https://github.com/ni/nimble/blob/a7991f6c44aabe702721b78be358146b59333a29/packages/nimble-components/src/switch/template.ts#L9) and [toggle-button](https://github.com/ni/nimble/blob/a7991f6c44aabe702721b78be358146b59333a29/packages/nimble-components/src/toggle-button/specs/README.md?plain=1#L56)) automatically set `aria-disabled=true` whenever you apply the `disabled` attribute. The `nimble-button` doesn't do this.

## 💻 Repro or Code Sample

https://nimble.ni.dev/storybook/?path=/story/components-button--outline-button&args=disabled:!true

## 🤔 Expected Behavior

If a client sets `disabled` then `aria-disabled` will be true.

## 😯 Current Behavior

`aria-disabled` is never set automatically

## 💁 Possible Solution

Other components have code in their template to sync the attributes. Unfortunately the button is currently using a FAST template so we'd either have to make a change in FAST (requiring a release from their legacy branch) or fork the template as we've done for other components.

Even if we fork the template we should still file an upstream issue to FAST.

## 🔦 Context

This is a problem for [this SLE PR making changes to Playwright tests](https://dev.azure.com/ni/DevCentral/_git/Skyline/pullRequest/512833#1687804240). The Playwright `toBeDisabled()` assertion [will only succeed if native form elements have the `disabled` attribute or non-native custom elements have `aria-disabled=true`](https://playwright.dev/docs/api/class-locatorassertions#locator-assertions-to-be-disabled). This means a `nimble-button` with the `disabled` attribute is currently failing that assertion.

**Comment by m-akinc** [comment]
I've submitted an issue to FAST: https://github.com/microsoft/fast/issues/6783. We should see if they are willing to fix this quickly, and if so, if they are willing to cherry-pick the fix into our legacy branch. If not, I guess we fork the template. 😒

**Comment by m-akinc** [comment]
Chris Holt very quickly pushed back on the request, pointing out that the element that is of interest from an accessibility standpoint is the native button in the shadow DOM. It is the one with the "button" role, not the host element. This is different from our switch and toggle-button, where the host element has the a11y role.

We may just need to modify the way our tests are being written.

**Comment by jattasNI** [comment]
I guess that leaves us with options like:
1. change the test to use `expect(control).toHaveBooleanAttribute('disabled')`
2. create higher level matchers that conditionally call `toBeDisabled()` or `toHaveBooleanAttribute()` depending on the type of the control 
3. file a bug to Playwright saying that `toBeDisabled()` is wrong for custom elements
4. decide we disagree with FAST and we really want `aria-disabled` and `disabled` to be synced, which means either making our case to FAST or forking their template

@rajsite you advocated for calling this a bug initially, do you have an opinion here? I'm inclined to trust FAST and try for a combo of 1-3.

**Comment by rajsite** [comment]
I think 1-2 are essentially advocating for a high-level page objects for our components right? Maybe we need to put the effort into playwright page objects.

I'm on the fence about 3-4. Think it might take some research. My questions:
- Right now the approach largely used by us / FAST is that the host custom-element itself is not the accessibility presenting element. Some child element is and we hide the host custom element / treat it as generic and forward properties to some child. I'm wondering if that is the right long-term vision.
   
   The ElementInternals apis have been adding a bunch of stuff to make the host custom element the accessibility tree presenting element. Maybe we / FAST should actually be targeting the host custom element for the accessibility tree.
- In the upcoming Accessibility Object Model APIs there will be a concept of computed accessibility node values. This is pure conjecture but I wonder if thoughts of shadow dom will participate in that. I could see the "computed accessibility" of a custom element with a shadow root being flattened to the custom element. Again pure conjecture, would need to find those discussions
- Given the above I think playwright is not 100% correct but I'm not sure if fixes help us. The [playwright disabled check algorithm](https://github.com/microsoft/playwright/blob/main/packages/playwright-core/src/server/injected/roleUtils.ts#L811) checks against a hard coded list of tag names and then checks for aria attributes. They should probably also check the ElementInternals state based on what exists today or check the Computed Accessibility Tree for what exists tomorrow. I think it's probably unreasonable for them to try and search our shadow root to figure out what is presenting externally, but maybe that's not unreasonable! I'm not completely sure.

**Comment by jattasNI** [comment]
For 1 or 2 I had been naively thinking they'd be changes to the tests or test utilities, but you're right that a page object is a better long term place for that. I left a comment on our testing APIs issue linking to this one.

Great research on the future direction. I'll need to take some time to digest to form an opinion.

**Comment by jattasNI** [comment]
We ended up using `toHaveAttribute('disabled')` to work around this issue in [the SystemsManagement Playwright tests](https://dev.azure.com/ni/DevCentral/_git/Skyline/pullRequest/512833#1687804240). We should replace that if we fix this some other way.

**Comment by fredvisser** [comment]
Closing as low ROI. If this becomes an issue in the future, please reopen.

**Comment by rajsite** [comment]
For more context / future direction:

- The [ElementInternals apis for configuring aria](https://developer.mozilla.org/en-US/docs/Web/API/ElementInternals#instance_properties_included_from_aria) are now available in all browsers. So we are longer term more likely to stop doing aria attribute configuration on the elements directly.
  - As we adopt that api we can behave "more normal", i.e. aria attributes on the elements are for users to configure and override our aria (for example when creating molecules out of nimble components). The aria attributes on our elements are not for the element itself to configure aria (which was needed prior to ElementInternals aria api availability)
- We should continue expanding the page objects we create to encapsulate details like this
- We should file issues to libraries that are failing to detect aria correctly
