### ISSUE TITLE
Investigate using pointer events for column resizing.

### ISSUE THREAD

**Issue by atmgrifter00** [ni/nimble#1362]
## 📌 User Story

The [current implementation](https://github.com/ni/nimble/pull/1321) for column resizing uses the HTML mouse events for handling the resizing of a column. This has several drawbacks including:
- not being touch-friendly
- not properly dealing with cases where a users drags off-screen, does mouse clicks off-screen, and then moves the mouse back into the browser (without doing extra work).
- necessitating an overlay in the template to intercept mouse events so other interactive elements don't see them while doing a column resize

Using the HTML [pointer events](https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events) seem like they can address all of the above issues without much effort.

**Comment by atmgrifter00** [comment]
Should try and handle the ability to cancel a column resize with the pointer event APIs (e.g. calling `releasePointerCapture`).

**Comment by rajsite** [comment]
> Should try and handle the ability to cancel a column resize with the pointer event APIs (e.g. calling `releasePointerCapture`).

In specific a user signifying an intent (i.e. we listen for the esc key being pressed ourselves) and then relying on the pointer event api to handle that lifecycle easier (if esc is pressed and we have a captured pointer, release the captured pointer)

**Comment by atmgrifter00** [comment]
There is an [existing bug in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1556240) related to pointer events where the click event will fire on whatever element the mouse is released over after doing a pointer capture. One example of a consequence here for the table (if we used pointer events), is that if a user drags a column divider and then releases it over a row (when row selection is enabled) that that row will be selected.

The W3C working group has [recently clarified](https://github.com/w3c/pointerevents/pull/474/) what the standard behavior is for this scenario (see [here](https://github.com/w3c/pointerevents/pull/474/files#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R652) and [here](https://github.com/w3c/pointerevents/pull/474/files#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R679-R686)).

**Comment by rajsite** [comment]
Ahh interesting, looks like Pointer Events was one of the topics for webcompat 2023: https://wpt.fyi/interop-2023
Found that trying to see what the web platform test coverage looks like across browsers. Might explain the recent activity and hopefully those issues will be resolved soon! 🤞

**Comment by atmgrifter00** [comment]
> Edit: Well maybe, doesn't look like the [pointer event focus areas](https://wpt.fyi/results/pointerevents?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2023-events) would cover this case. Guess we will see maybe.

Yeah, that's what I was noticing too. I was hoping that the bug in Firefox was linked from this area, but I don't believe it is.
