### ISSUE TITLE
How to handle empty values in table group headers?

### ISSUE THREAD

**Issue by m-akinc** [ni/nimble#1367]
# 🎙 Discussion

When grouping by a certain column, and some cells in that column render as blank, you end up with a strange-looking group header.
![image](https://github.com/ni/nimble/assets/7282195/eba413d4-84f6-446f-8576-8b41297ac68a)

This typically happens when the source value is missing, `null`, `undefined`, invalid, or otherwise formats as blank. 

Furthermore, since there may be multiple source values that render as blank, you may have multiple group headers that all look the same, which is weird.

**Comment by fredvisser** [comment]
Closed in favor of https://github.com/ni/nimble/issues/1538
