### ISSUE TITLE
Apply invalid styles to controls with :invalid pseudo-selector

### ISSUE THREAD

**Issue by brianehenry** [ni/nimble#138]
For Nimble controls with "invalid" styles, we should also apply those styles when the element has an [:invalid](https://developer.mozilla.org/en-US/docs/Web/CSS/:invalid) pseudo-class, for use with the control's own form validation properties (e.g. [required](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/required)).

Currently, styles targeting `:invalid` don't work in all browsers, an issue has been filed to FAST: https://github.com/microsoft/fast/issues/5231

**Comment by rajsite** [comment]
Our current patterns don't expect the control to automatically apply invalid states based on the native HTML form validation behaviors.

Instead the application chooses when to set `error-visible` and `error-text` attributes. This works well for Angular and Blazor applications at the moment.

We should re-consider this if clients request easier utilization of native html form validation and / or [ElementInternals APIs](https://caniuse.com/?search=elementinternals) become available cross-platform (currently absent in Safari but partially in [webkit tech previews](https://webkit.org/?s=elementinternals)).

Closing until use cases are identified.

**Comment by rajsite** [comment]
More notes:
- Angular disables html 5 native DOM validation UIs: https://angular.io/api/forms/NgForm#native-dom-validation-ui
- ElementInternals APIs are now in Webkit starting with 16.4
- 

keywords:
Html 5 form validation
native form
DOM validation ui
novalidate

**Comment by rajsite** [comment]
PR https://github.com/ni/nimble/pull/1141 is proposing have EditForms in Blazor automatically enable the error-visible and error-text properties on validation changes. This is not aligned with our HTML components and Angular Form components behaviors (where Angular just reports validation and the user manually assigns the result to attributes, etc).

Also Blazor has [ValidationMessage and ValidationSummary](https://learn.microsoft.com/en-us/aspnet/core/blazor/forms-and-input-components?view=aspnetcore-7.0#validation-summary-and-validation-message-components) for deciding how validation messages are displayed, I'm not sure the PR proposal aligns there either.
