### ISSUE TITLE
nimble-tabs allows switching to a hidden tab using keyboard

### ISSUE THREAD

**Issue by mollykreis** [ni/nimble#1383]
# 🐛 Bug Report

The `nimble-tabs` component allows you to switch to a hidden tab using the left/right arrows. This should not be allowed.

## 💻 Repro or Code Sample

1. Go to the storybook page for the Tabs Matrix: https://nimble.ni.dev/storybook/?path=/story/tests-tabs--tabs-theme-matrix
2. Focus the first tab element on the page
3. Notice that you can use the Right Arrow button to move from Tab One to Tab Two
4. Notice that if you press the Right Arrow button again, the content of the tab panel will be that of the hidden Tab Three that is part of the story

## 🤔 Expected Behavior

A hidden tab should behave as though it is not in the DOM. A user should not be able to navigate to that tab's content using the keyboard (or the mouse).

## 😯 Current Behavior

You can navigate to the hidden tab using the arrow keys.

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* Version [e.g. 1.8.0]

**Comment by m-akinc** [comment]
Check anchor tabs as well

**Comment by m-akinc** [comment]
PR to FAST: https://github.com/microsoft/fast/pull/6789
