### ISSUE TITLE
Cannot drag a link from the text

### ISSUE THREAD

**Issue by m-akinc** [ni/nimble#1406]
# 🐛 Bug Report

Normally with links, you can click and drag the link text, and it will show a copy of the url attached to the cursor that you can drop into another application or a new tab, for example. Nimble anchors do not do this. This applies to all types of Nimble anchors:
- anchor
- anchor button
- anchor tab
- anchor menu item

Interestingly, you _can_ drag from the area surrounding the text (i.e. for all types except the plain anchor).

## 💻 Repro or Code Sample

On the Anchor Button Storybook page, click on the button text and drag with the mouse.

## 🤔 Expected Behavior

The pointer should change and an element showing the url should follow the cursor around.

## 😯 Current Behavior

Nothing happens

## 💁 Possible Solution

This is a problem with the FAST anchor. We will have to try to fix it in FAST.

**Comment by fredvisser** [comment]
Let's file the bug to FAST, and see where this goes.
