### ISSUE TITLE
Create a stylesheet for mdx files that styles headers as needed

### ISSUE THREAD

**Issue by aidendk** [ni/nimble#1413]
## 🧹 Tech Debt

Based on [this comment](https://github.com/ni/nimble/pull/1355#discussion_r1281229676) from Milan:

In cases like the image below where spacing between the header and child titles are needed, `<br />` has been used to create this spacing. We should remove the usage of `<br />` in our mdx files and instead create a stylesheet that styles our headers as we need.
![usagedocsspacing](https://github.com/ni/nimble/assets/103057880/220eb471-135c-4a96-a28a-99557af63825)

**Comment by jattasNI** [comment]
Since we've moved all of our docs to mdx this is no longer an issue.
