### ISSUE TITLE
Interaction design for tab/toolbar with too much content to fit in screen width

### ISSUE THREAD

**Issue by jattasNI** [ni/nimble#1436]
## 📌 Request Background

There is an [SLE bug](https://dev.azure.com/ni/DevCentral/_workitems/edit/2488661?src=WorkItemMention&src-action=artifact_link) about the expand/collapse toolbar button being placed strangely on small screens. The team that's fixing it requested guidance from us about how to fix it.

![image](https://github.com/ni/nimble/assets/10500124/84579c6c-4777-41a5-b921-c1f408712f5f)

Initial suggestions included adding a way to scroll or growing the height of the toolbar. I've also seen experiences that put items in an overflow menu.

## 🎯 Core Requirements

Ideally we could have a good default behavior without requiring changes to how the content was added to the toolbar. So ideas that use a different presentation like a menu might be difficult because it might require annotating each item with more info like a menu item name.

## 🥅 Acceptance Criteria

- [ ] Interaction Designer comments on this issue with a recommendation

**Comment by leslieab** [comment]
The "..." menu is the overflow menu. If a toolbar doesn't have it, add it. If a toolbar does add it, add the icon buttons to it as items starting with the least important.

**Comment by jattasNI** [comment]
We briefly brainstormed about this in a team meeting today. It'll be a challenge for Nimble to automatically handle it because clients can provide arbitrary toolbar content like icon buttons, select, text, or menus. For some of that there isn't an obvious mapping to how it would render as a menu item.

Instead perhaps Nimble would just give guidance that apps should move content to a menu when it doesn't fit. Then we'd push the responsibility to apps to implement that using CSS container or media queries.

(Just recording brainstorming, not necessarily a decision)

**Comment by jattasNI** [comment]
I captured the guidance above in #1206. There will be lots more questions to answer but that belongs in that bigger mobile support discussion so I'm closing this for now.
