### ISSUE TITLE
Leverage appropriate number format options in number-text table column once supported in all browsers

### ISSUE THREAD

**Issue by mollykreis** [ni/nimble#1442]
## 🧹 Tech Debt
As part of #1414, we had to make some concessions and add some work-arounds due to certain number format options not being supported yet in Firefox.

Once Firefox has parity support with other browsers for these options for at least 6 months we should update our numeric formatters for the number-text table column to use these features.

Specifically the options we would like to use but cannot yet are:
- `useGrouping: auto`
- `signDisplay: negative`
- `roundingPriority: 'lessPrecision'`

**Comment by m-akinc** [comment]
Should check on this again in early 2024

**Comment by rajsite** [comment]
@m-akinc please wait to address this till after the unit support is merged

**Comment by m-akinc** [comment]
Waiting for a Chromatic update to get new enough browsers to support these options. Could be any time now.
