### ISSUE TITLE
NimbleTableModule imports/exports all modules/directives of main entry point

### ISSUE THREAD

**Issue by m-akinc** [ni/nimble#1476]
# 🐛 Bug Report

When an Angular app imports the NimbleTableModule, it brings along all the modules that are part of `nimble-angular`'s main entry point.

## 💻 Repro or Code Sample

1. Open sl-table-columns-text.component.spec.ts (in systemlink-lib-angular)
2. Mark a single test to be run (with "fit")
3. Start a debugging test session
4. In the Sources tab, open "check.js" and put a breakpoint on the line with `registerIcon(...)`
5. Refresh the browser to run the test
6. When the breakpoint is hit, look at the call stack and select the frame third from the top (source position is in ni-nimble-angular-table.mjs)
7. Examine the Locals view and see entries for all the modules/directives from the main `nimble-angular` entry point. The program is in the process of loading all those modules as imports of the NimbleTableModule.

## 🤔 Expected Behavior

The NimbleTableModule should not import/export the modules from the main entry point.

## 😯 Current Behavior

All modules from the main entry point are being loaded.
![image](https://github.com/ni/nimble/assets/7282195/794c9c8e-6aeb-4ac0-8d8a-822b077d34b1)

## 🔦 Context

Discovered this when it was pointed out that my sl-table-column-icon test was using an icon that it was not explicitly importing, but the test was running fine anyway.

**Comment by rajsite** [comment]
I suspect the behavior discussed is based on the second bullet in this issue: https://github.com/ni/nimble/issues/172#issuecomment-1026036739

reproduced as follows:

> The issue right now is that because they are [all exported together](https://github.com/ni/nimble/blob/main/angular-workspace/projects/ni/nimble-angular/src/public-api.ts), and because we intentionally use [imports with side-effects](https://github.com/ni/nimble/blob/main/angular-workspace/projects/ni/nimble-angular/src/directives/button/nimble-button.module.ts#L5), the dead-code checkers can't toss unused component definitions. Importing a button imports all the components. If each module is moved to secondary imports via the exports feature, ie import {ButtonModule} from '@ni/nimble-angular/button'; then dead code elimination can work as expected.

The likely issue is that any import from the top-level `@ni/nimble-angular` results in everything defined in the top-level being imported. We need to move to secondary entrypoints per component as we started doing with the table. Closing as duplicate

**Comment by m-akinc** [comment]
> The likely issue is that any import from the top-level `@ni/nimble-angular` results in everything defined in the top-level being imported.

But what I was seeing suggested that it was the `NimbleTableModule` that was causing all the top-level modules to be imported. I think there may be something else going on.

**Comment by rajsite** [comment]
> > The likely issue is that any import from the top-level `@ni/nimble-angular` results in everything defined in the top-level being imported.
> 
> But what I was seeing suggested that it was the `NimbleTableModule` that was causing all the top-level modules to be imported. I think there may be something else going on.

I'm pretty confident that any import from the top-level import will result in all nimble components from that entry point being registered. For example there are zero usages of [nimble-tooltip](https://dev.azure.com/ni/_search?action=contents&text=nimble-tooltip&type=code&lp=custom-Collection&filters=&pageSize=25&result=DefaultCollection/DevCentral/Skyline/GBmaster//Web/Workspaces/SystemLinkShared/projects/systemlink-lib-angular/notebook/src/components/sl-notebook-report-settings/sl-notebook-report-settings.component.html) but you can see `nimble-tooltip` get registered in the landing page: https://test.lifecyclesolutions.ni.com/

![image](https://github.com/ni/nimble/assets/1588923/ce343962-5de6-45c9-93a4-b1065d643763)

If you think there is something else going on and it won't be addressed by moving all components to separate entry points feel free to re-open the issue.

**Comment by m-akinc** [comment]
Dug into it some more, and I think it probably is just the issue you mentioned. The source file shown in the debugger call stack (which made me think it was the table responsible for the importing) appears to be wrong. It looks like the module ID 86160 which has all the main entrypoint imports is `nimble-angular` rather than `nimble-angular/table`:
![image](https://github.com/ni/nimble/assets/7282195/108c27c3-fe26-47eb-be0a-39220ed12cb7)
