### ISSUE TITLE
Multiple icons in the same cell

### ISSUE THREAD

**Issue by ni-saradei** [ni/nimble#1515]
The way the current asset grid works at the moment allows multiple icons to be displayed in the same cell. This practice is used inside the status column in order to display multiple ongoing states, in case they are happening at the same time. The asset move dialog, currently under feature flag, will display the same column, and it uses the nimble table, as we need to migrate from the previous component. 

## 😯 Problem to Solve

Future expectations for the status column are the same and we would like to have the possibility to display more than one icon inside the cell.

## 💁 Proposed Solution
One solution I see would be to add object type support for table-column-icon in order to be able to define multiple mappings.

## 📋 Tasks
- [ ] This is a subtask of the feature. (It can be converted to an issue.)
-->

**Comment by jattasNI** [comment]
@ni-saradei Thanks for the request! The Nimble dev team has a bunch of questions and thinks it might be a good idea to have a conversation about it. How about we talk about it at the UI WG next week? If you could have some screenshots or code links for existing implementations to share that would be helpful.

**Comment by ni-saradei** [comment]
> @ni-saradei Thanks for the request! The Nimble dev team has a bunch of questions and thinks it might be a good idea to have a conversation about it. How about we talk about it at the UI WG next week? If you could have some screenshots or code links for existing implementations to share that would be helpful.

Current implementation gives the possibility of string concatenation, that's all there is to it.
![image](https://github.com/ni/nimble/assets/136442709/1e92d5e0-f937-4e01-a14e-9ffa16363f6e)

We could talk at the next UI WG, if we can book something sooner that would be ok as well. I am not sure what the questions would imply, if it's about the alternatives, they would need to be confirmed with the PO as well.

**Comment by jattasNI** [comment]
Thanks @ni-saradei. In the nimble-table want to provide an API with the right amount of flexibility without allowing completely arbitrary HTML content like the previous grid did. So some of the questions we had were:

1. is there a limit to the number of icons in a cell?
2. are the possible combinations known at dev time or are they dynamic?
3. could the icons have different severities or not?

From inspecting [the code you screenshotted](https://dev.azure.com/ni/DevCentral/_git/Skyline?path=/Web/Workspaces/SystemLinkShared/projects/asset-manager-lib/src/utils/status-icon-helper/status-icon-helper.ts&version=GBmaster&line=23&lineEnd=24&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents) I see that the current use case is:
1. 0, 1, or 2 icons 
2. the combinations are known at dev time but there are quite a few of them (no icon + 4 solo icons + 3 pairs of icons = 7)
3. each icon has a known severity but the icons in a set might have different severities

If that captures all the requirements then we may not need to meet about it and our team can start brainstorming APIs. But if you/your PO knows of future needs then it would be good to hear about them.

**Comment by ni-saradei** [comment]
@jattasNI 
1. If we would have to define a limit I would say at least 3, if we can fit 4, just in case we need it later, that would be great.
2. we can know, but there are quite a few as you have noticed, and there is a possibility that we might need to expand that in the future. Depending on certain values we receive we need to display either 0/1/2 (current behavior) slots of icons, each with a different icon, text and severity.
3. yes, definitely different severities 

Regarding future needs, I know that the PO expects to need at least one more icon to display.

**Comment by ni-saradei** [comment]
@jattasNI I will have to sync with the PO for more details.

**Comment by ni-saradei** [comment]
@jattasNI Agreed on splitting the status, will close the issue. Thank you!
