### ISSUE TITLE
Rich text editor | Support for hyperlinks along with absolute links

### ISSUE THREAD

**Issue by vivinkrishna-ni** [ni/nimble#1527]
## 📌 User Story
**Context** - We are envisioning that after adding hyper link support, only pasted or typed absolute URLs might use `<autolink>` syntax and rest of them will likely use normal links syntax `[link text](url)`. However this is subjected to discussion on rich text components spec to decide the intended behavior after research. 

**Scope of this user story** - As part of adding hyperlink support, we may need to revisit some restrictions on supporting only absolute links and consider removing/replacing them. This user story will capture those tasks for future reference. 

Hyperlink (termed as [Links in CommonMark Spec](https://spec.commonmark.org/0.30/#links)) support for the `nimble-rich-text-editor` component will be added along with current absolute link (termed as [Autolinks in CommonMark Spec](https://spec.commonmark.org/0.30/#autolinks)) support

- Hyperlink markdown syntax - `[link text](url)`
- Absolute link markdown syntax - `<autolink>`

_Note that any detailed implementation plan for hyperlink support will be updated in spec HLD for rich text components._ 

### 😮 Current Support

We support only **Absolute links** for the initial pass which is by typing or pasting a full URL into the editor and not adding a link to the existing texts.

We also made the following changes to support only absolute links in the editor and autolink in the markdown which should be revisited when we support normal hyper links with text:
1. [ ] Added `pointer-event: none;` to all the links in the editor which will restrict the user from opening the link from the editor in any form.
2. [ ] In `markdown-serializer.ts`, [prosemirror-markdown](https://github.com/ProseMirror/prosemirror-markdown/blob/c7210d0e55c82bfb0b2f7cba5dffe804575fafb3/src/to_markdown.ts#L3C1-L26C2) implements logic for both hyperlink and autolink in `defaultMarkdownSerializer`. Therefore, implemented our own implementation to support only autolink in markdown output.
3. [ ] In `markdown-parser.ts`, bypass the default [normalization link text](https://github.com/markdown-it/markdown-it/blob/2b6cac25823af011ff3bc7628bc9b06e483c5a08/lib/index.js#L67C1-L86C2) provided by markdown-it to display the link as is in the editor and viewer. This needs to be removed.
4. [ ] [`inclusive`](https://prosemirror.net/docs/ref/#model.MarkSpec.inclusive) is disabled in the Tiptap editor as well as in the link schema because the absolute link mark need not be active when positioned at the end/start of the link after it was added. Needs an update here based on the requirements.
5. [ ] [`linkOnPaste`](https://tiptap.dev/api/marks/link#link-on-paste) is switched off because it will add the link to the selected texts in the editor. Needs to be switched on.
6. [ ] Restricted other marks such as bold/italics in absolute link since common mark spec for autolinks does not support it. But it is supported with hyperlinks. Restricted by setting [`excludes: "_"`](https://prosemirror.net/docs/ref/#model.MarkSpec.excludes) in the Tiptap editor and markdown parser.
7. [ ] When hyperlinks are copied from a different source and pasted into the editor will actually render it as an absolute link by ignoring the text content. This is handled in the `transformPasted` method which needs an update when hyperlink support is added. Also, `transformPasted` validates if the copied links are valid (HTTPS/HTTP), as there is an open bug in Tiptap on adding the validation to the pasted links. If it is resolved, we could completely get off `transformPasted` when supporting Hyperlinks. https://github.com/ueberdosis/tiptap/issues/4427
8. [ ] When autolinks are between bold/italics sentences then the part that is next link formatting will be lost when parsing. For example, markdown: `**Some text <https://link> Some text**`, the output will be like - '**Some text** https://link Some text'. This issue can be fixed when hyperlink support is enabled

### 💡 Future Support

1. Link can be added to the existing text in the editor by opening a dialog based on the design.
2. Both autolink`<URL>` and link`[test](URL)` can be enabled in markdown format.

### 🔗 Relevant Links
https://github.com/ni/nimble/pull/1394
https://github.com/ni/nimble/pull/1496

**Comment by rajsite** [comment]
@vivinkrishna-ni is this feature work being tracked in AzDo somewhere?

**Comment by vivinkrishna-ni** [comment]
@rajsite Support for hyperlinks is tracked as part of this [_Epic 2383228_](https://dev.azure.com/ni/DevCentral/_workitems/edit/2383228)
_: Comment support for images and rich text emails_ and a related feature [_Feature 2567597_](https://dev.azure.com/ni/DevCentral/_workitems/edit/2567597)_: Support for opening links from comments in new tab_

**Comment by rajsite** [comment]
@vivinkrishna-ni can you make sure a link to this issue is captured in a feature on AzDo and then close this one as not planned. We can re-open this issue when prioritized.

**Comment by vivinkrishna-ni** [comment]
Closing this as not planned for now and will reprioritize as part of this feature: [Feature 2567597](https://dev.azure.com/ni/DevCentral/_workitems/edit/2567597): Support for Hyperlink and opening links from comments in new tab
