### ISSUE TITLE
Nimble Numeric field | Option to hide "+-" buttons

### ISSUE THREAD

**Issue by gokuldharan-ni** [ni/nimble#1528]
## 😯 Problem to Solve

In our app we got requirement to hide the "+-" buttons used to increment and decrement the number value. We have aligned with Jesse and came to know that there is an API already available for this, but its not documented. 

## 💁 Proposed Solution
- Option  to hide "+-" icon buttons, as its already available it would be better to have this documented.

**Comment by jattasNI** [comment]
The undocumented attribute is called `hide-step`. We should add it to Storybook docs and also include it in our matrix tests. But I don't think there is much risk in your app using it today.

For traceablility, [here is the original discussion](https://dev.azure.com/ni/DevCentral/_workitems/edit/2414324). I've asked for more context there about the rationale for hiding the buttons.

**Comment by adamarnesen** [comment]
For some context on why we want to have this option. 

For floating point numbers, the increment/decrement step applied by the "+-" buttons is not helpful. My understanding is that we always add/subtract 1 when using these buttons. When dealing with test data, integer values are almost never used. The values are almost always floating point. Having the "+-" buttons in this context confuses the users so we want to be able to hide it in test data contexts.

**Comment by mollykreis** [comment]
@adamarnesen, I'm not trying to sway your usage one way or the other, but I thought I'd point out that there is an API to configure a `step` to control how much is added/subtracted with the +/- buttons are pressed. So, if it makes more sense to have a smaller step here, that's also an option.

**Comment by rajsite** [comment]
> The undocumented attribute is called `hide-step`. We should add it to Storybook docs and also include it in our matrix tests. But I don't think there is much risk in your app using it today.
> 
> For traceablility, [here is the original discussion](https://dev.azure.com/ni/DevCentral/_workitems/edit/2414324). I've asked for more context there about the rationale for hiding the buttons.

It also needs to be exposed from the Angular directive to get access to it. So docs and an angular directive change (w/ tests).
