### ISSUE TITLE
Placeholder text in nimble-table columns

### ISSUE THREAD

**Issue by m-akinc** [ni/nimble#1538]
## 😯 Problem to Solve

Need to support placeholder text in table columns.
Related: #1511

LIMS use case where missing date values should render "--":
![image](https://github.com/ni/nimble/assets/7282195/9ba3d3a5-a86f-41fc-9847-63d64f3ad7c3)

SLE Executions grid where a missing Notebook value is rendered **as a link** with text "Notebook not available" in italics:
![image](https://github.com/ni/nimble/assets/7282195/775d3ff1-5302-4cb5-8e92-a69dcf24d804)

SLE Systems grid grouping by "Group" value, where some systems have no "Group" value:
![image](https://github.com/ni/nimble/assets/7282195/1d7c9a86-1ee8-4481-b4c7-93533586a2f4)

Need to support different placeholder text in different columns. Cannot standardize on a single placeholder.

Open questions:
1. Should we support group header text that is different from the cell text? 
    a. E.g. "--" in cell but "No value" in group header.
    b. E.g. empty cell in an icon column, but "No value" in group header.
2. Should placeholder text be dimmed? Only in cells, but not group headers?
3. Should placeholder text always be italicized?
4. Does placeholder text use the same alignment of cells with values, e.g. number-text column with right alignment?

**Comment by fredvisser** [comment]
Looking at the open questions:

1. Should we support group header text that is different from the cell text?
a. E.g. "--" in cell but "No value" in group header.
b. E.g. empty cell in an icon column, but "No value" in group header.

If it's technically straightforward – **yes**. "No value" communicates more clearly than "--" in the group header.

![Image](https://github.com/ni/nimble/assets/1458528/7362cbed-4693-4e21-8f03-4f83dd422334)

@NIbokeefe - thoughts on the below questions?
2. Should placeholder text be dimmed? Only in cells, but not group headers?
3. Should placeholder text always be italicized?
4. Does placeholder text use the same alignment of cells with values, e.g. number-text column with right alignment?

**Comment by fredvisser** [comment]
After talking with Brandon and Jesse –

1. Should we support group header text that is different from the cell text?
- Yes, "No value" makes sense for the group header
2. Should placeholder text be dimmed? Only in cells, but not group headers?
- Yes, placeholder text should be dimmed (standard placeholder token value) in the data rows, but not in group headers.
3. Should placeholder text always be italicized?
- No, the placeholders don't need to be italicized
4. Does placeholder text use the same alignment of cells with values, e.g. number-text column with right alignment?
- Yes, placeholder text will use the same alignment as the other values

**Comment by jattasNI** [comment]
@fredvisser could you provide guidance on these points too?
1. Can placeholder text be specified as a single string for a column or might it need to be different for each cell in a column?
2. Do we need to support placeholder text for all column types?

**Comment by fredvisser** [comment]
@jattasNI - Per our discussion today, we plan to use this placeholder text feature to support blank or null values, and will create a new feature to support error information on the cell level (datatype mismatch, invalid/disallowed URLs, etc.)

So with that increased focus:
1. Placeholder text should be specified as a single string for a column. We should not support unique placeholder values per cell.
2. We don't need to support placeholder text for the enum and icon column types, but should support the remaining column types. And yes, it looks like we need to support placeholder hyperlinks for the [Executions](https://dev.lifecyclesolutions.ni.com/executions/) app.

@NIbokeefe - Any issues applying the placeholder styling to anchor text in the table context?

<img width="622" alt="Screenshot 2024-01-19 at 11 50 24 AM" src="https://github.com/ni/nimble/assets/1458528/95302d6c-f6cd-457a-92c3-18c4ea47176e">

**Comment by mollykreis** [comment]
Support for placeholders has been added to nimble-components, nimble-angular, and nimble-blazor.
