### ISSUE TITLE
sl-table refresh behavior interaction design request

### ISSUE THREAD

**Issue by fredvisser** [ni/nimble#1576]
## 📌 Request Background

SLE apps use tables to display data. This data can change in the backend, so apps adopt different strategies so that their table is consistent with the backend data store:
1. Don't poll, and rely on the user to refresh the page or navigate back to the page to refresh the latest data on page load. E.g. [Security UIs](https://dev.lifecyclesolutions.ni.com/security/users)
2. Don't poll, and give the user a **Refresh Data** button. E.g. [Licenses](https://dev.lifecyclesolutions.ni.com/licenses/)
3. Allow the user to configure the polling interval. E.g. Manual, 3 seconds, 10 seconds, 30 seconds – [Test Results (Manual)](https://dev.lifecyclesolutions.ni.com/testinsights/results?viewId=638625232a4e648d1a8045f4), [Assets (10 seconds)](https://dev.lifecyclesolutions.ni.com/assets/), [Files (Manual)](https://dev.lifecyclesolutions.ni.com/files/), [Executions (Manual)](https://dev.lifecyclesolutions.ni.com/executions/)
4. Poll, but don't allow the user to configure the polling interval. E.g. poll every 5 seconds  – [Systems](https://dev.lifecyclesolutions.ni.com/systems/?viewId=64079263795ed88ef65469cc), [Products](https://dev.lifecyclesolutions.ni.com/testinsights/products?viewId=638625232a4e648d1a8045f3), [Data Spaces](https://dev.lifecyclesolutions.ni.com/testinsights/dataspaces), [Routines](https://dev.lifecyclesolutions.ni.com/routines/)

Other apps:
1. Use non-polling techniques for real-time synchronization. E.g. WebSockets
2. Tell the user that updates are available, but don't update the table until they click
3. Poll, but stop after a period of inactivity. Require the user to take action to resume polling.

## 😥 Challenges:
1. Polling is resource inefficient – it produces excess load on our servers, adds network traffic, reduces battery life on devices that have these web UIs open
2. Accessibility is hard for tables that change without user interaction.

## 🤨 Questions:
1. Do our users require or expect data in tables to update as backend data changes? Why? Do they keep these pages open for a long time? Do they open and monitor the pages for a few seconds to confirm data appears correctly?
2. Do our users require efficient web UIs? Beyond the potential infrastructure savings, do customers use battery powered devices to view SLE? Operate in limited network environments?
3. Can we propose an approach that is consistent across all SLE apps?

## 😶‍🌫️ SWAG proposal:
1. Add a **Refresh Data** button to all `sl-tables` in SLE. Remove all automatic polling, or user configured polling. Rely on user to click button if they want data refreshed. Avoids full page load, so is much more efficient than full page reload.

## 🥅 Acceptance Criteria (TBD)

- [ ] Interaction Design Spec submitted (link)
- [ ] Interaction Design Spec reviewed by design team
- [ ] Interaction Design Spec reviewed by dev team

**Comment by joshuaprewitt** [comment]
Your proposal would probably be fine for grids that don't show status asynchronously.  It would be a huge usability decrease if I had to manually refresh these system's grid to check on the installation progress when deploying software to 100 systems or see that my system is back online after rebooting it or when adding a new system. 

For pretty much anything else it would probably be fine to not refresh by default, but expose it as a user option. However, if the user does change it to refresh on regular basis it should persist that setting. It annoys the heck out of me that the tag grid doesn't persist the refresh option.

**Comment by joshuaprewitt** [comment]
It is also annoying that the refresh option takes up so much space in the toolbar.

**Comment by fredvisser** [comment]
Moved this to the [pattern doc backlog](https://dev.azure.com/ni/DevCentral/_workitems/edit/2810570)
