### ISSUE TITLE
Requesting new icon for '@' mention in rich text editor

### ISSUE THREAD

**Issue by vivinkrishna-ni** [ni/nimble#1585]
## 😯 Problem to Solve

For the `comments` feature in SLE, we have a requirement to support the '@' mention of other users. To support this, we can either enter the `@` symbol through the keyboard in the `nimble-rich-text-editor` or click the button with the `@` symbol icon in the toolbar to display a dropdown with the list of users. 

For reference, below is the equivalent icon in the AzDo rich text editor,
![image](https://github.com/ni/nimble/assets/123377523/a301c05e-c2f1-4cb2-b0ce-de1cc97db143)

Link to the relevant task in AzDo: [Task 2536823](https://dev.azure.com/ni/DevCentral/_workitems/edit/2536823): Nimble component requirement | @ icon

## 💁 Proposed Solution

Create and add the `@` icon to nimble icons.

**Comment by RickA-NI** [comment]
Icon is created need a reminder on how to submit it to Nimble

**Comment by jattasNI** [comment]
@RickA-NI [Instructions for adding an icon](https://github.com/ni/nimble/blob/main/packages/nimble-tokens/CONTRIBUTING.md#updating-icons). If you can extract the icon from Illustrator and attach it to a new issue that you file, the dev team can add it to the repo.

**Comment by jattasNI** [comment]
Was resolved with #1625
