### ISSUE TITLE
Rich text editor doesn't respect Command-arrow keyboard combination on macOS

### ISSUE THREAD

**Issue by jattasNI** [ni/nimble#1590]
# 🐛 Bug Report

On macOS, when typing in a text input the Command-arrow keyboard combination is expected to navigate the cursor to the start or end of the line. It doesn't do this in the rich text editor even though it works fine in other Nimble components like text-area.

## 💻 Repro or Code Sample

Open storybook demo for the rich text editor on a mac, put cursor focus in the editor, type the keyboard combination.

## 🤔 Expected Behavior

When typing in a text input:
- Command-left arrow navigates the cursor to the start of the line
- Command-right arrow navigates the cursor to the end of the line
- Shift-Command-left arrow selects from the current location to the beginning of the line
- Shift-Command-right arrow selects from the current location to the end of the line

## 😯 Current Behavior

Command-left navigates the browser backward (at least in Firefox which I tested). This is the correct behavior if not in a text input but is not expected when in a text input.

Command-shift-left does nothing.

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* Version [e.g. 1.8.0]

**Comment by fredvisser** [comment]
Works correctly now - closing - 👍
