### ISSUE TITLE
Inline context help for nimble-combobox

### ISSUE THREAD

**Issue by mure** [ni/nimble#1592]
## 😯 Problem to Solve

Hi all - I'm starting to look at ⁠[this feature](https://dev.azure.com/ni/DevCentral/_workitems/edit/2472948), part of the new routines UX that requires Nimble updates.

The goal of the feature is to be able to display inline help for the workspace selector field. The current wireframes show this UX:

![image](https://github.com/ni/nimble/assets/9257800/3422c0ae-b542-4f7a-9b5f-94147fdc3e0d)

Hovering the ℹ️ icon would display a tooltip. This would require changes to the `nimble-combobox`.

## 💁 Proposed Solution

I'm anticipating pushback on the UX above, mostly because it conflicts with the existing UX for displaying validation errors:

![image](https://github.com/ni/nimble/assets/9257800/134e3aad-2594-49d1-bf9f-8b95267ccd9b)

My proposal would be to move the tooltip hover icon into the component's label. This approach can apply to all form controls, so it's both easier to implement and less cognitive load for users.

Here's an example of how Grafana's design system does inline help:

![image](https://github.com/ni/nimble/assets/9257800/58797eff-3459-418b-af87-9505bb5925c1)

My intent for this issue is to come to a consensus on the correct UX and implementation for the feature. Based on the outcome, I can create a spec if needed. My understanding is that we'll also need to create or update an IxD spec.

## 🙋‍♂️ Open issues

- [ ] Decide on UX of inline help for form controls
- [ ] I noticed in [Storybook](https://nimble.ni.dev/storybook/?path=/docs/components-combobox--docs) that the combobox doesn't seem to have a label attribute. Will we need to add this?
- [ ] Should we resurrect the [nimble-tooltip](https://github.com/ni/nimble/issues/309) for this feature?

**Comment by m-akinc** [comment]
Please set up a meeting with @leslieab, @NIbokeefe, and @mollykreis to discuss direction.

**Comment by jattasNI** [comment]
[Visual design is available](https://www.figma.com/file/PO9mFOu5BCl8aJvFchEeuN/Nimble_Components?type=design&node-id=5308-156796&mode=dev) as nimble-toggle-tip.

**Comment by fredvisser** [comment]
Closing in favor of https://github.com/ni/nimble/issues/1876
