### ISSUE TITLE
Text wrapping for nimble table

### ISSUE THREAD

**Issue by SPathani-NI** [ni/nimble#1600]
## 😯 Problem to Solve

Currently, Nimble table does not support text wrapping for its rows. As a result, when a cell contains a large text value, it overflows.
![image](https://github.com/ni/nimble/assets/147801131/6239e7d4-f78c-4e29-99d7-b4568dcf381f)

## 💁 Proposed Solution

 Adding a feature that allows users to define text wrapping so that a row can expand vertically showing the complete data.
 
![image](https://github.com/ni/nimble/assets/147801131/2ad6dfd4-e7bf-405a-af3b-17dbb3097f58)

link to old frontend page for reference: https://dashboard.ni.systems/dashboard/#/systems/system-logs

**Comment by jattasNI** [comment]
Thank you for filing this issue! We are not currently planning to prioritize it until we see more demand for it. In the meantime, we can suggest alternatives like:
1. parsing the contents of this string to pull out relevant information and displaying a subset of that in dedicated columns
2. showing a summary of the data in a column and adding a way (via an action menu or selection + toolbar button) for a user to see the long text information in a different workflow like a dialog / drawer / detail page.

We will also bring this up with our interaction designer as an input to future visions about nested tables or "tables within tables".
