### ISSUE TITLE
Add icons to token library: ni_16x16 and system link_16x16

### ISSUE THREAD

**Issue by NIbokeefe** [ni/nimble#1606]
Icon names:

**ni_16x16**  
Tags: ni, logo, product

**systemlink_16x16** 
Tags: systemlink, logo, product

![systemlink_16x16](https://github.com/ni/nimble/assets/106594349/c920ae64-7caa-4259-8e16-df92d239d6fa)
![ni_16x16](https://github.com/ni/nimble/assets/106594349/9b3dc3db-c1c6-457d-81f6-a1fe03fba9ca)

**Comment by jattasNI** [comment]
@fredvisser let's plan for you to take this one but let me know if you can't find bandwidth in the next few days.

**Comment by NIbokeefe** [comment]
@fredvisser I have another request for a "save as" icon that I'm going to consolidate into this task by end of day

**Comment by NIbokeefe** [comment]
@fredvisser  Disregard that comment I previously made about adding the save-as icon.  Our current save icon should be sufficient.  This is good to go.
