### ISSUE TITLE
Row coloring for Nimble Table

### ISSUE THREAD

**Issue by SPathani-NI** [ni/nimble#1608]
## 😯 Problem to Solve

The current implementation of nimble table does not provide the feature to change row color/
![image](https://github.com/ni/nimble/assets/147801131/23173830-8ba8-40f1-8450-a267df60b31a)

For my use case I want the row to change color depending on some property value as is the case with frontend V1

![image](https://github.com/ni/nimble/assets/147801131/f787ffd9-bebf-4f7b-8bc1-6cda736138b1)
![image](https://github.com/ni/nimble/assets/147801131/e85226b7-de76-43b2-8986-27dd6594672e)

This will enable end user to know the type of data the row is displaying at a glance.

## 💁 Proposed Solution

Add row color as a useable feature.

**Comment by atmgrifter00** [comment]
@SPathani-NI, I would ask for even more specifics. Ultimately, what the Nimble table will likely never do is allow a user to arbitrarily set row colors to whatever color they wanted. The reasoning being that this would allow a user to easily put the table in a state that violated accessibility guidelines (even if they believe it to look proper).

The rows of our tables already have very specific colors associated with them for the different supported themes that allow them to look consistent with the rest of the Nimble component library (this covers things like selected state, hover state, selected and hovered state). It's possible that there are other colors that could be used in each theme that would still provide a natural look for the rows, however I imagine it is a pretty discrete set (if there are any). So, one question would be, do you have a set of specific semantic meanings you would like to convey for a row (i.e. "row is in an error state", "row is in a good state", etc...)? If so, that could influence the visual design we feel is proper to convey such meaning.

**Comment by rajsite** [comment]
An alternate direction would be to use an icon column to represent the state of a row. This is how exisiting applications show different error states, for example the state of a System managed in SystemLink. 

A benefit of the icon column is those states can be sorted, grouped, etc. And the icon columns can be configured for different levels of severity (warning, error, information, success), that renders with a consistent and accessible color in the different themes (light mode and dark mode): https://nimble.ni.dev/storybook/?path=/docs/components-table-column-icon--docs

Would representing the error states of rows with an icon column be a viable alternative?

**Comment by SPathani-NI** [comment]
Thank you for your suggestions.
a specific icon column won't fit as in my use case as majority of rows are of a single particular type and also their numbers mostly range in thousands thus it won't be intuitive.
What I would ask is to give the user a certain set of colors that each have a particular meaning as is done with nimble icons and their "severity" property.

**Comment by rajsite** [comment]
@SPathani-NI I'm not sure I understand your concern. You can have 1000s of rows of data that have an icon column.

**Comment by SPathani-NI** [comment]
Sorry for late reply.
After discussion we decided that this is actually a good solution however there are 2 small issues with it:
1 We don't want to dedicate a column worth of space to this. Is there any way to integrate icons column inside other columns?
2 For my application I require icon for 5 levels "debug,information,warning,error,critical" rest are fine but critical and error currently have to share the "error " severity.

**Comment by rajsite** [comment]
> Is there any way to integrate icons column inside other columns?

Nope. There isn't currently a feature planned around that. Integrating it in a separate column makes it harder to sort / group by the icon states.

> make the column width equal to the icon size?

There is an issue to track smaller headers on icon columns here: https://github.com/ni/nimble/issues/1332
We have some open design questions we have not resolved yet so there isn't an expected time we would ship that yet.

A workaround mentioned by @atmgrifter00 that could bee used here:

> setting min-pixel-width to something small like 32 [and] setting a fractional-width setting of some unknown amount smaller than the other columns to get it to actually adopt the min-pixel-width setting (might require trial and error)

See the [min-pixel-width and fractional-width docs](https://nimble.ni.dev/storybook/?path=/story/components-table-column-configuration--fractional-width-column).

> For my application I require icon for 5 levels "debug,information,warning,error,critical" rest are fine but critical and error currently have to share the "error " severity

Having two distinct colors to emphasize the difference between critical and error may be challenging (a color has to be designed to meet accessibility contrast ratios, selected for each theme, tested across controls). I don't expect we would add that color state today without clear usage guidance.

An alternative may be to use the same error color state but a different icon if you want a way to visually tell the states apart.

**Comment by rajsite** [comment]
Closing as alternatives were provided and haven't heard any concerns.
