### ISSUE TITLE
Can't type table data in storybooks to be 'as const'.

### ISSUE THREAD

**Issue by atmgrifter00** [ni/nimble#1613]
## 🧹 Tech Debt

It's expected that we should be able to type data we set on a `Table` as `as const`, however currently in our storybook implementations for various table storybooks we can not do this. The reasoning for this, I think, is that many of the table storybook implementations use [shared types](https://github.com/ni/nimble/blob/260ad74bc906cc5b0b3861f9df376593ce3ce732/packages/nimble-components/src/table-column/base/tests/table-column-stories-utils.ts#L4C1-L4C1) that  ultimately will type the `Table` to its default `TableRecord` type, which will be incompatible with something declared with `as const`.

Not sure what the proper resolution to this would be.

**Comment by rajsite** [comment]
Fixed by #1711
