### ISSUE TITLE
nimble-{ Move Icon } visual design request

### ISSUE THREAD

**Issue by NIbokeefe** [ni/nimble#1628]
Create a Move icon for TJ Giere 

From TJ: "I was originally thinking that this [Move Icon - Free PNG & SVG 2071274 - Noun Project (thenounproject.com)](https://thenounproject.com/icon/move-2071274/) looks pretty darn similar to a 45degree rotated nimble-icon-arrows-maximize, but wanted  to run that by you, and see if you had another recommendation, or time to create a new icon to represent move."

**Comment by NIbokeefe** [comment]
@jattasNI @fredvisser 

Requesting these two icons be included in the nimble icon library for TJ Giere

arrow-in-circle_16x16  Tags: move, move in
![arrow-in-circle_16x16](https://github.com/ni/nimble/assets/106594349/887ef979-8024-4dbf-ac8e-43e04326e61e)

arrow-out-circle_16x16  Tags: move, move out
![arrow-out-circle_16x16](https://github.com/ni/nimble/assets/106594349/117b2105-9da7-42f1-8a9b-d7b711aec4c0)

**Comment by jattasNI** [comment]
@fredvisser I'll start on this now unless you let me know that you already have

**Comment by NIbokeefe** [comment]
[heart]         Brandon O'Keefe reacted to your message:
________________________________
