### ISSUE TITLE
Accessibility tree for number field claims increment/decrement buttons are focusable

### ISSUE THREAD

**Issue by kjohn1922** [ni/nimble#1644]
# 🐛 Bug Report

In the accessibility tree, the increment/decrement buttons  of a number field are shown as focusable. They are not focusable.

## 💻 Repro or Code Sample

Seems to affect all number fields, so you can see the issue on the [Number Field storybook page](https://nimble.ni.dev/storybook/?path=/docs/components-number-field--docs). The issue is visible in both the regular accessibility tree and the full page accessibility tree view with Chrome dev tools.

![image](https://github.com/ni/nimble/assets/35350751/ccdd3e8d-85a0-4947-9226-b9bd48fa9f4f)
![image](https://github.com/ni/nimble/assets/35350751/92701e3a-765c-45ee-b046-5ebae46a67f7)

## 🤔 Expected Behavior

The "focusable" attribute should be "false" in the accessibility tree for the increment/decrement buttons of a number field.

The [`fast-number-field` example in the explore view](https://explore.fast.design/components/fast-number-field) doesn't show the increment/decrement buttons in the accessibility tree at all.

## 😯 Current Behavior

The "focusable" attribute is "true" in the accessibility tree for the increment/decrement buttons of a number field.

## 💁 Possible Solution

Unsure of the solution. The increment/decrement buttons have tabindex="-1" set [here](https://github.com/ni/nimble/blob/f159a084527c7e53bac99dd43182c10c2f2f628f/packages/nimble-components/src/number-field/index.ts#L71).

## 🔦 Context

Mentioned in PR comment in #1638 [here](https://github.com/ni/nimble/pull/1638#discussion_r1379435727).

## 🌍 Your Environment

* OS & Device: Windows 10 on PC
* Browser Google Chrome 118.0.5993.90
* Version [e.g. 1.8.0]

**Comment by m-akinc** [comment]
It looks like an element that is not focusable should not be shown in the accessibility tree. In that case, we must use `aria-hidden` to explicitly hide it from the a11y tree.
