### ISSUE TITLE
Rich text mention users view is not selectable in Firefox browsers

### ISSUE THREAD

**Issue by vivinkrishna-ni** [ni/nimble#1662]
# 🐛 Bug Report

The `nimble-rich-text-mention-users-view` is an internal element for the nimble rich text components used to render the user mentions within a component as an emphasized green text. This will be rendered both in the rich text editor and viewer. With the current approach as per https://github.com/ni/nimble/pull/1653, there are a couple of issues in the Firefox browser in selecting the node:
1. When rendered in the viewer, if the light DOM is present with the view node, both are not selectable at the same time (recording below in current behavior)
2. When rendered in the editor, the blue background is not shown for the shadow DOM text.

These are known issues in Firefox and here are the links to the actual issues:
1. https://bugzilla.mozilla.org/show_bug.cgi?id=1455893
2. https://bugzilla.mozilla.org/show_bug.cgi?id=1545367
3. https://bugzilla.mozilla.org/show_bug.cgi?id=1860292

## 💻 Repro or Code Sample

Repro: Try selecting all the texts by opening [this link](https://bug1455893.bmoattachments.org/attachment.cgi?id=9289349) in Firefox browser
Code: Inspect the page

## 🤔 Expected Behavior

All the texts should be selected.

## 😯 Current Behavior

https://github.com/ni/nimble/assets/10500124/674e7832-f9ae-461d-bd00-b2d442e405db

## 💁 Possible Solution

Currently, the text content is populated within the shadow DOM and not through a slot. If the text content is in the slot instead of constructing ourselves in the template, the issue is resolved. However, it creates a few other issues with selections which include:
1. Selecting the mention view node using the keyboard (Shift + left/right arrow keys) doesn't work as expected
2. If there is no whitespace/any other character at the beginning and/or at the end of the mention view node in the editor, keyboard selection doesn't work but mouse selection works

## 🔦 Context

Relevant discussions:
1. https://github.com/ni/nimble/pull/1653#discussion_r1384680808
2. https://github.com/ni/nimble/pull/1653#discussion_r1389624846

## 🌍 Your Environment

* OS & Device: Windows on PC
* Browser: Mozilla FireFox
* Version: 119.0.1 (64-bit)

**Comment by fredvisser** [comment]
Duplicate AzDO work item - [Bug 2645468](https://dev.azure.com/ni/DevCentral/_workitems/edit/2645468): [@mention] Rich text mention users view is not selectable in Firefox browsers

**Comment by fredvisser** [comment]
Closing as low ROI
