### ISSUE TITLE
Reduce duplication in Spright packages by single-sourcing and exporting from Nimble

### ISSUE THREAD

**Issue by jattasNI** [ni/nimble#1682]
## 🧹 Tech Debt

This issue tracks parts of Nimble that would be useful in https://github.com/ni/spright but which we had to duplicate (or not use) since they weren't easily consumable.

1. `nimble-components/src/utilities/tests`. `matrix` and `storybook` and `hidden` are used by matrix tests

**Comment by m-akinc** [comment]
Closing because Spright will now be hosted in the Nimble repo, and we will share code differently.
