### ISSUE TITLE
Rich text editor | Cursor disappears when moved to the start of the line with mention node

### ISSUE THREAD

**Issue by vivinkrishna-ni** [ni/nimble#1710]
# 🐛 Bug Report

When the editor is in focus, the mention node is at the start of the line, and moving it to the start of the line will disappear the text cursor. Please find the GIF in the below section.

## 💻 Repro or Code Sample

1. Add a mention node at the start of a line in the rich text editor component
2. Press the left arrow key to move the text cursor to the start of the line
3. The text cursor disappears but typing something will insert a text

## 🤔 Expected Behavior

The cursor should be visible

## 😯 Current Behavior

The cursor is not visible
![cursor-disappear-issue](https://github.com/ni/nimble/assets/123377523/459454ff-226a-455b-9576-684bc2b0576b)

## 💁 Possible Solution

To fix this bug, change the display for `nimble-rich-text-mention-users-view` to `inline` from `inline-block`. However, when performing the set content via a `setMarkdown()` API, the cursor is not inserted at the end of the editor when focused. This is a problem when performing edit a comment in SLE.

## 🔦 Context

[Bug 2603497](https://dev.azure.com/ni/DevCentral/_workitems/edit/2603497): Cursor not coming up when navigated to beginning of the mention node

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* Version [e.g. 1.8.0]

**Comment by fredvisser** [comment]
Duplicate AzDO work item – [Bug 2645467](https://dev.azure.com/ni/DevCentral/_workitems/edit/2645467): [@mention] Rich text editor | Cursor disappears when moved to the start of the line with mention node

**Comment by fredvisser** [comment]
Marked as `currently deprioritized` as this is being tracked in AzDO as https://dev.azure.com/ni/DevCentral/_workitems/edit/2603497
