### ISSUE TITLE
When suggestions re-focused after pressing Esc key, mention popup opens

### ISSUE THREAD

**Issue by vivinkrishna-ni** [ni/nimble#1712]
# 🐛 Bug Report

In the rich text editor, when the user wants to type a normal text with `@` symbol, they can type like `@some text` and press Escape to close the popup so that the text remains as plain text. However, if the same text is re-focused the popup opens again which might affect the user experience.

## 💻 Repro or Code Sample

Steps to reproduce:

1. Add a text `@Some text`
2. Press Escape
3. Press Enter to start a new line and write some text
4. Now move the cursor back to the end of `@Some text`

## 🤔 Expected Behavior

The mention popup should not be opened once after the `@some text` is focused.

## 😯 Current Behavior

The mention popup opens
![suggestion-auto-focus](https://github.com/ni/nimble/assets/123377523/744070c7-152d-426a-8af4-1387dee20522)

## 💁 Possible Solution

It is due to the below issue in Tiptap where the decoration node is not removed when `allowspace` is set to true in suggestion props for filtering the name with a space.
https://github.com/ueberdosis/tiptap/issues/214

Once the issue is resolved in Tiptap, it will be fixed here as well

## 🔦 Context

Relevant issue in SLE application: [Bug 2602538](https://dev.azure.com/ni/DevCentral/_workitems/edit/2602538): Suggestions are auto focused while revisiting the node, even after pressing Esc key

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* Version [e.g. 1.8.0]

**Comment by fredvisser** [comment]
Duplicate AzDO work item – [Bug 2645466](https://dev.azure.com/ni/DevCentral/_workitems/edit/2645466): [@mention] When suggestions re-focused after pressing Esc key, mention popup opens

**Comment by fredvisser** [comment]
Closing in favor of the SLE tech debt: [Bug 2602538](https://dev.azure.com/ni/DevCentral/_workitems/edit/2602538): Suggestions are auto focused while revisiting the node, even after pressing Esc key
