### ISSUE TITLE
Copy pasting mentioned user without spaces into editor not rendering as expected.

### ISSUE THREAD

**Issue by vivinkrishna-ni** [ni/nimble#1715]
# 🐛 Bug Report

With the current implementation of the rich text editor for @mention feature, when copy-pasting mentioned users into the editor, it will render as plain text without the `@` symbol. For example, if `@John Doe` is copied and pasted into the editor will render it as just `John Doe`. However, if a single mention node without any whitespace or other texts around it is copied from the viewer and pasted into the editor with the `@` character and retained bold text of view element.

This causes an issue when the user elements are dynamic every time the `mention-update` event is emitted.

## 💻 Repro or Code Sample

1. Copy a mentioned user from the viewer. Make sure the selected part only includes the view element and not the whitespace or any other text around it. Say `@John Doe`
2. Paste it into the editor

## 🤔 Expected Behavior

Should paste as just `John Doe` as a plain text

## 😯 Current Behavior

Pasting as `@John Doe` as a plain text

If copied with whitespace around it or with any other texts, they paste as expected `John Doe `.

## 🔦 Context

In SLE, we update the user mapping elements every time the `mention-update` event is emitted. So if pasted into the editor, they converted to `**@John Doe**`. See: [Bug 2605541](https://dev.azure.com/ni/DevCentral/_workitems/edit/2605541): Copy pasting mentioned user without spaces into editor not rendering as expected.

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* Version [e.g. 1.8.0]

**Comment by vivinkrishna-ni** [comment]
This issue is related to copy-pasting a `nimble-anchor` from viewer to editor https://github.com/ni/nimble/issues/1516#issuecomment-1731776248

<details><summary>HTML string when copied <code>nimble-rich-text-mentioned-users</code> from viewer</summary>
<p>
&#x3C;html&#x3E;
&#x3C;body&#x3E;
&#x3C;!--StartFragment--&#x3E;&#x3C;span style=&#x22;color: rgb(0, 107, 70); font-family: &#x26;quot;Source Sans Pro&#x26;quot;, &#x26;quot;Source Sans Pro Fallback&#x26;quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 600; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: pre-wrap; background-color: rgb(244, 244, 244); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;&#x22;&#x3E;@&#x3C;/span&#x3E;&#x3C;span style=&#x22;color: rgb(0, 107, 70); font-family: &#x26;quot;Source Sans Pro&#x26;quot;, &#x26;quot;Source Sans Pro Fallback&#x26;quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 600; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: pre-wrap; background-color: rgb(244, 244, 244); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;&#x22;&#x3E;John Doe&#x3C;/span&#x3E;&#x3C;!--EndFragment--&#x3E;
&#x3C;/body&#x3E;
&#x3C;/html&#x3E;
</p>
</details> 

👆In the content above, note there is only content within the shadow root is available and not the entire element. So they render even with bold styling and when pasting we couldn't find out whether it is mention node or not. Basically, they behave like a 'paste as plain text',

<details><summary>HTML string when copied <code>nimble-rich-text-mentioned-users</code> from viewer with a whitespace</summary>
<p>
&#x9;
&#x3C;html&#x3E;
&#x3C;body&#x3E;
&#x3C;!--StartFragment--&#x3E;&#x3C;nimble-rich-text-mention-users-view mention-href=&#x22;user:1&#x22; mention-label=&#x22;John Doe&#x22; disable-editing=&#x22;&#x22; style=&#x22;display: inline-block; box-sizing: border-box; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: ; font-variant-east-asian: ; font-variant-alternates: ; font-variant-position: ; font-weight: ; font-stretch: ; font-size: 14px; line-height: ; font-family: &#x26;quot;Source Sans Pro&#x26;quot;, &#x26;quot;Source Sans Pro Fallback&#x26;quot;; font-optical-sizing: ; font-kerning: ; font-feature-settings: ; font-variation-settings: ; color: rgb(22, 22, 23); white-space: pre-wrap; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(244, 244, 244); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;&#x22;&#x3E;&#x3C;span class=&#x22;control&#x22; style=&#x22;font: var(--ni-nimble-mention-font); color: var(--ni-nimble-private-mention-font-color); display: inline;&#x22;&#x3E;@John Doe&#x3C;/span&#x3E;&#x3C;/nimble-rich-text-mention-users-view&#x3E;&#x3C;span style=&#x22;color: rgb(22, 22, 23); font-family: &#x26;quot;Source Sans Pro&#x26;quot;, &#x26;quot;Source Sans Pro Fallback&#x26;quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(244, 244, 244); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;&#x22;&#x3E;&#x3C;span&#x3E; &#x3C;/span&#x3E;&#x3C;/span&#x3E;&#x3C;!--EndFragment--&#x3E;
&#x3C;/body&#x3E;
&#x3C;/html&#x3E;
</p>
</details> 

👆In this context, we can see the `<nimble-rich-text-mention-users-view>` is available so that we can differentiate whether it is mention node or not and convert it to a plain text as mentioned in the bug description.

**Comment by fredvisser** [comment]
Duplicate AzDO work item – [Bug 2645464](https://dev.azure.com/ni/DevCentral/_workitems/edit/2645464): [@mention] Copy pasting mentioned user without spaces into editor not rendering as expected

**Comment by vivinkrishna-ni** [comment]
@fredvisser Sorry for the delayed response, we will not prioritize this bug as it has a low ROI. If we want it to be fixed later, we will reopen the above-linked AzDo bug and work on it.

**Comment by m-akinc** [comment]
Closing as low ROI
