### ISSUE TITLE
nimble card directive and module are not exported into public-api.d.ts

### ISSUE THREAD

**Issue by PetitCalgon** [ni/nimble#1717]
# 🐛 Bug Report

nimble card directive and module are not exported into  `nimble-angular\public-api.d.ts`

## 💻 Repro or Code Sample

1. Create a new angular application
1. Add package @ni/nimble-angular
1. Try to import the module NimbleCardModule in `app.module.ts`

## 🤔 Expected Behavior

nimble card directive and module should be exported into  `public-api.d.ts`

## 🌍 Your Environment

* Version 18.2.4

**Comment by rajsite** [comment]
@PetitCalgon the nimble-card is imported from a secondary entrypoint from `@ni/nimble-angular/card`, see the example angular app as an example:

https://github.com/ni/nimble/blob/3506db58b98fc38b29e5372a77843bdc3cc003a8/angular-workspace/projects/example-client-app/src/app/app.module.ts#L13
