### ISSUE TITLE
Critical vulnerabilities in minimist pulled in by to-ico

### ISSUE THREAD

**Issue by jattasNI** [ni/nimble#1732]
## 🧹 Tech Debt

When you run `npm install` or `npm audit` there are two critical vulnerabilities in minimist 0.0.8:
https://github.com/advisories/GHSA-xvch-5gv4-984h
https://github.com/advisories/GHSA-vh95-rmgr-6w4m

The vulnerable version is pulled in by [`to-ico`](https://www.npmjs.com/package/to-ico)
```
│ └─┬ to-ico@1.1.5
│   └─┬ resize-img@1.1.2
│     └─┬ jimp@0.2.28
│       └─┬ mkdirp@0.5.1
│         └── minimist@0.0.8
```

That package hasn't been updated in a long time and hasn't accepted a PR that tried to update its dependencies https://github.com/kevva/to-ico/pull/19 . 

We only use the package in [one place](https://github.com/ni/nimble/blob/db80aa81bd7dd49053d52a3be70cad46fa203fad/packages/nimble-tokens/build/svg-to-ico.js#L6). I think we should move away from it. Options I found:
1. [this comment](https://github.com/kevva/to-ico/pull/19#issuecomment-1094140481) says that `png-to-ico` is a drop in replacement for `to-ico` so we could try switching to that.
2. our usage was adapted from [jtrauntvein/svg-to-ico](https://github.com/jtrauntvein/svg-to-ico). In [a recent PR](https://github.com/jtrauntvein/svg-to-ico/pull/1) they changed to use `ico-endec` instead so we could try to update our fork with a similar change
3. We should check if [NimbleTokens](https://www.nuget.org/packages/NimbleTokens) nuget package is actually leveraged elsewhere. If not, we can delete the package and stop generating ico and resx files included in it.
    - only reference found on [azdo search](https://dev.azure.com/ni/_search?type=workitem&text=NimbleTokens) or [codesearch](https://codesearch.natinst.com/search/text?q=NimbleTokens&fold_case=auto&regex=true&context=true) was for [ECU Toolkiit](https://dev.azure.com/ni/DevCentral/_workitems/edit/1927663) where from the description it sounds like the icons were copy and pasted but not actually used as the nimble icons did not match their color needs or sizing needs

**Comment by jattasNI** [comment]
Let's go with option 3, deleting the NimbleTokens nuget package. As part of that work we should post an FYI on the Blazor Teams channel.

**Comment by rajsite** [comment]
@jattasNI marked the package as legacy / deprecated but kept it listed (in-case someone is building with it): https://www.nuget.org/packages/NimbleTokens#versions-body-tab

**Comment by rajsite** [comment]
Actually, just went through and unlisted the releases. So won't see any versions published on nuget.org anymore and doesn't show up in search https://www.nuget.org/packages?q=NimbleTokens
