### ISSUE TITLE
WaferMap test expectations are not executing

### ISSUE THREAD

**Issue by rajsite** [ni/nimble#1746]
## 🧹 Tech Debt

Several wafer map tests are resulting in warns on nimble builds such as the following: https://github.com/ni/nimble/actions/runs/7475603903/job/20344086522#step:17:262

> 'Spec 'Wafermap Prerendering module with undefined values should have empty color fill style' has no expectations.'

The warning states that no `expect` statements are running for the test. However the source of the test shows expect statements:
https://github.com/ni/nimble/blob/e78cd3773cf97604aabb5b4750b349b1c34b39d2/packages/nimble-components/src/wafer-map/tests/prerendering.coloring.spec.ts#L327-L331

Seems like the tests are incorrectly written / not validating behaviors as expected.

The pattern that likely let this issue through is that the tests have conditionally executing expect statements which is an issue discussed here: https://github.com/ni/javascript-styleguide/issues/125#issuecomment-1631721812

To address this tech debt the wafer map tests should be hardened to avoid conditionally executing expect statements as discussed in the above style guide issue.

**Comment by m-akinc** [comment]
@munteannatan Just a heads up.
