### ISSUE TITLE
Table headers should be right-aligned when data is right-aligned

### ISSUE THREAD

**Issue by fredvisser** [ni/nimble#1750]
# 🐛 Bug Report

During the `nimble-table-column-number-text` definition we decided to maintain left-alignment of headers for right-aligned data. This was a mistake, and we should fix that by consistently aligning headers with the data.

See this [table best practices doc](https://medium.com/design-with-figma/the-ultimate-guide-to-designing-data-tables-7db29713a85a) for more.

## 💻 Repro or Code Sample

<img width="534" alt="Screenshot 2024-01-11 at 8 47 46 AM" src="https://github.com/ni/nimble/assets/1458528/36884fa3-57a5-41ee-b609-2249cc249f2e">

https://nimble.ni.dev/storybook/?path=/docs/components-table-column-number-text--docs

## 🤔 Expected Behavior

Table header text should be right-aligned when data is right-aligned

**Comment by rajsite** [comment]
@fredvisser I don't remember all the concerns but one question is how are the interactions with sorting and grouping and future menu drop downs?

Do we reserve the space for them? Do we have the header text jump around as the indicators pop in and out? Do we move the indicators to the left side of the header text so they can pop in and out without shifting the header?

Didn't read the full linked table best practices doc (forgive me if it's covered) but the following screenshot seems to maybe be showing all headers left aligned in that case (or maybe the table is too narrow to tell):
![image](https://github.com/ni/nimble/assets/1588923/6ebae8e5-00a5-4661-abbf-52361902242f)

**Comment by fredvisser** [comment]
@NIbokeefe - Do we have the right-aligned columns designed in Figma?

**Comment by NIbokeefe** [comment]
@fredvisser Yes, I can look into adding a property that gives the option to right align text.  Users of the figma component can manually do that right now, it's just not surfaced in a way that they would know it's an option.

**Comment by jattasNI** [comment]
Thanks @NIbokeefe! When you build that design, reminder of the main question from the dev team: where should the sorting and grouping icons go?

**Comment by fredvisser** [comment]
The decision was to mirror the sorting and grouping icons

![image](https://github.com/ni/nimble/assets/1458528/48a5355f-65ca-4424-9e12-0dda48c12548)
