### ISSUE TITLE
Table hierarchical data leaf mode

### ISSUE THREAD

**Issue by m-akinc** [ni/nimble#1759]
## 😯 Problem to Solve

Support for a table mode where only leaf rows represent first-class data. I.e. parent rows are organizational only. 

## 💁 Proposed Solution

See section in [HLD](https://github.com/ni/nimble/blob/main/packages/nimble-components/src/table/specs/data-hierarchy-hld.md#leaf-only-mode)

**Comment by fredvisser** [comment]
Closing as low ROI

**Comment by rajsite** [comment]
The channel selector table implemented a subset of leaf only mode behavior in the application layer for ([azdo pr](https://dev.azure.com/ni/DevCentral/_git/Skyline/pullrequest/1321848)).

<img width="744" height="253" alt="Image" src="https://github.com/user-attachments/assets/5385ab0a-6e71-4ed7-a22c-a677221ca822" />
