### ISSUE TITLE
Possibly flaky test: "should commit mention into the editor on Enter"

### ISSUE THREAD

**Issue by m-akinc** [ni/nimble#1761]
## 🧹 Tech Debt
Saw this test fail on an unrelated PR.

![image](https://github.com/ni/nimble/assets/7282195/f7e1ae7b-20a6-4cc9-8777-ed0c6de5bb0d)

https://github.com/ni/nimble/actions/runs/7576426399/job/20635217943

**Comment by m-akinc** [comment]
Created AzDO work item assigned to LIMS: https://ni.visualstudio.com/DevCentral/_workitems/edit/2632606

**Comment by rajsite** [comment]
Intermittent test disabled in https://github.com/ni/nimble/pull/1770
As per nimble intermittent test policy: https://github.com/ni/nimble/blob/adde25d1cad4b59868590e81684a622bbd38b23e/CONTRIBUTING.md#handling-intermittent-test-failures

AzDo issue filed to address disabled test: https://ni.visualstudio.com/DevCentral/_workitems/edit/2632606
