### ISSUE TITLE
Handling event in Blazor causes Table to set data

### ISSUE THREAD

**Issue by atmgrifter00** [ni/nimble#1763]
# 🐛 Bug Report

Blazor, by default, will behave in such a way that if you supply an event handler to a component, then that component that registered the event handler will reset the state of _all_ contained components. So, a `NimbleTable` on the same page as a button with an event handler, will, by default, update its data (assuming it is bound to some data in the Razor code) when the button event fires.

This is problematic for a couple of reasons:
1) Updating the Table can be expensive, and that happening as a result of _any_ event handler running for _any_ component within the same component as the `NimbleTable` is far less than ideal.
2) If the event being handled is on something like an action menu on a table row, then the action menu will get auto-dismissed, because, again, the table's data will be set, which we have decided should dismiss the action menu.

This was discovered by a client team and filed under [this AzDO Bug](https://dev.azure.com/ni/DevCentral/_workitems/edit/2483686). 

## 💻 Repro or Code Sample

The component in question for that bug is [here](https://dev.azure.com/ni/DevCentral/_git/ASW?path=/Source/LicenseManagement/Licensing.ClientUtility/Components/FeatureList.razor&version=GC2bbf7a340122f248e858e3cd9f843a9897b74dcc&_a=contents).

## 🤔 Expected Behavior

Handling events via the Table API should not cause the action menu popup to be dismissed. Moreover, handling events on components should not cause the `NimbleTable` to set its data.

## 😯 Current Behavior

The action menu on a table is dismissed if an event is handled as part of showing the popup. The table calls `setData` as a result of any event handlers being run (using Blazor's default behavior).

## 💁 Possible Solution

While it's possible for clients to avoid this by implementing various [render control flow strategies](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/rendering?view=aspnetcore-8.0#control-the-rendering-flow), it still seems prudent for the `NimbleTable` to attempt to behave properly (and optimally) in absence of direct client intervention.

Currently, the implementation for the `Data` property of the `NimbleTable` is simplistic and will result in data being re-rendered by the web component _any_ time the setter is called. Thus, if the same reference is supplied for the data, it will still be re-rendered (which is the root of the issue). Additionally, if a datatype is provided that is notifying (something that implements `INotifyCollectionChanged`), the `NimbleTable` will _not_ process a change to the data that would have otherwise notified (like calling `Add` or `Remove`), which is likely unexpected by the user.

I recommend that we not only handle the `INotifyCollectionChanged` case, but additionally document (and implement) that the `NimbleTable` will only update its data through either a new reference, or through changes made through the `INotifyCollectionChanged` interface. This is a pretty standard expectation for .NET users.

## 🔦 Context

See client issue linked above.

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* Version [e.g. 1.8.0]

**Comment by rajsite** [comment]
I think we should consider aligning the Blazor API with vanilla components and angular. We have run into issues trying to treat Angular as bindings because you may need multiple methods to run sequentially in order (setData followed by modifying selection, modifying loading spinner), for needing to wait for the setData to finish before running a different task ([closing a slideout after setData finishes](https://dev.azure.com/ni/DevCentral/_workitems/edit/2619696)), and it is an expensive operation that users should have good control over. Having the property binding api is a footgun. 🦶🔫
