### ISSUE TITLE
nimble-checkbox/radio-group - error state 🧑‍🎨 visual design request

### ISSUE THREAD

**Issue by fredvisser** [ni/nimble#1765]
## 📌 Request Background

We need to finish out our first-class form support for our core input components by supporting error states and text for all components commonly used in forms. 

## 🎯 Core Requirements

- Apply current error pattern to the `nimble-checkbox` and `nimble-radio-group` components.
- The [current designs](https://www.figma.com/file/PO9mFOu5BCl8aJvFchEeuN/Nimble_Components?node-id=1295%3A63148&mode=dev) have a partial error state drawn, but it doesn't include error text. It should include error text 

## 🥅 Acceptance Criteria

- [x] Visual Design Spec submitted ([link](https://www.figma.com/file/PO9mFOu5BCl8aJvFchEeuN/Nimble_Components?type=design&node-id=1295%3A63148&mode=dev))
- [x] Visual Design Spec reviewed by design team
- [x] [Visual Design Spec](https://www.figma.com/file/PO9mFOu5BCl8aJvFchEeuN/Nimble_Components?type=design&node-id=1295-63148&mode=dev) reviewed by dev team

**Comment by jattasNI** [comment]
@NIbokeefe the team reviewed the design today. Some questions:

1. how is the exclamation mark icon positioned? Is it a fixed distance from the end of the text? We don't currently have a width for options beyond how long the text is.
2. are you ok with the error text being ... ellipsized if it is longer than the checkbox option text? Or should we provide usage guidance to leave extra padding to the right of the checkbox / radio button and give the component an intrinsic width that's large enough to display error text?

![image](https://github.com/ni/nimble/assets/10500124/8e1f10b4-8915-4af5-b3f5-73d304cfb04e)

![image](https://github.com/ni/nimble/assets/10500124/70645b94-45c5-460b-a41d-650e64399274)

**Comment by jattasNI** [comment]
@NIbokeefe setting the checkbox width to the 100% of its container width would be a change from how the dev control works today where its width is determined by the text. It's likely achievable (though we'll have to figure out if Nimble sets that or if clients do) but opens up a question:

Right now you can click on the text to toggle the checkbox. Should clicking on the whitespace or the error exclamation mark also toggle it?

https://github.com/ni/nimble/assets/10500124/f246dcfe-88e0-4f42-9017-e7f9cb8e887f

**Comment by NIbokeefe** [comment]
@jattasNI @fredvisser Yes, I think it's okay to click in some white space, but it should be bound by a consistent and expected min/max width possibly defined by our general minimum control size.  I've always drawn our minimum control sizes as 176px.

The place we allow users to click in dead white space today is for menus and tree controls where the entirety of a line item region, which often has dead white space beyond the text still triggers a rollover and select. Checkboxes in the menu scenarios should definitely click in the dead white space.

A single checkboxes in forms where it can be both shot text or an extremely long string of text which can wrap multiple lines, is not a good idea to make the entire text area enable the checkbox. When the distance is greatly disconnected from the checkbox it lends itself to be accidentally be clicked and doesn't make sense why someone would intentionally click so far away from the checkbox target.

In a group checkbox scenario labels can be different widths, the inconsistency of the hotspot region based on text width would not be ideal.  

Checkboxes are small targets which prompted the purpose of extending the hotspot area, but that should be within reason.  A large and touch optimized target area is technically only 48 x 48.  So extending to 176px width is very accessible. 

I don't have really have an issue with the text length defining the clickable space outside of the corner cases I just mentioned, but it seems more complicated to build. At some point that breaks and there needs to be rules and bounds.  **My bigger issue** would be sticking the error icons directly next to the text for checkbox and radio controls, that's not an existing pattern with any other controls and I don't think it scales consistently.  I believe it should have a min size and fill a control slot determined by the context, similar to other control.

**Comment by m-akinc** [comment]
1. In general, we haven't given our components a minimum width (except menus/drop-downs, rich-text, and text-area). Is your recommendation that we impose a 176px min width on every component (except textless components like icon buttons, menu buttons, spinner, etc)?
2. For checkbox components' clickable area (toggles the check), it sounds like you are okay with blank space and text being clickable , but you don't want the clickable area to extend too far from the checkbox. If I'm understanding that right, then it implies that there would be some invisible boundary across which your mouse cursor would change, the hover styling would toggle, and clicking would behave differently. This boundary could be in the middle of text (for a long label) or blank space (for short labels).  That would feel pretty weird and arbitrary. More importantly that would be contrary to how native HTML elements work, where an associated label focuses/operates the control. I think we likely need to make the clickable area of a checkbox exactly the the box and the label text. We should not allow clicks in blank space (which is not obviously part of the control) to toggle the state.

**Comment by NIbokeefe** [comment]
1. I think I miss spoke with how I phrased that, what I meant to imply is that I've drawn my minimum-default size as 176 in width (which is my smallest ideal width). So that size is meant as a design default vs an actual locked "minimum width" as I incorrectly stated above. There are most likely window resizing - reactive instances where we would want the controls to shrink down more narrow than 176px.  However, in most cases it's not ideal to build controls with the intention of them being smaller than 176px in their native design, as it does not allow for an adequate amount of characters.
2. I agree
