### ISSUE TITLE
nimble-table - Error State visual design request

### ISSUE THREAD

**Issue by fredvisser** [ni/nimble#1776]
## 📌 Request Background

With user generated content, the table needs the ability represent that one or more table data cells are invalid. 

For example:
- A column is configured to display `numeric` data, but some rows contain `string` data. 
- A column is configured to display 'hyperlinks', but some rows contain external or poorly formated links.

In each case, we need to inform the user that the is an issue parsing or formatting the data and how they can resolve it.

Today, columns like the custom property column use placeholder text to show error strings. We should have a first class way to show this information.

![Image](https://github.com/ni/nimble/assets/1458528/3b757874-5154-4518-9049-78d8abf207a6)

## 🎯 Core Requirements

- Need a visual representation that there is an issue/error with the data in the cell.
- Need a way for users to **learn more** about the nature of the error.
- Null or no values will not typically display with an error (instead will use placeholder text), but should be supported for future use cases.

Consider also how we could display the unformatted data within the error state.

For example,

![Image](https://github.com/ni/nimble/assets/1458528/7dd8d324-6da2-45aa-8455-2812c3885297)
[Reference](https://js.devexpress.com/Angular/Demos/WidgetsGallery/Demo/DataGrid/DataValidation/MaterialBlueLight/Compact/)

## 🍆 Non-requirements
TBD

## 🥅 Acceptance Criteria

- [x] Visual Design Spec submitted ([link](https://www.figma.com/file/PO9mFOu5BCl8aJvFchEeuN/Nimble_Components?type=design&node-id=5453-19325&mode=design))
- [ ] ~~Visual Design Spec reviewed by design team~~
- [ ] Visual Design Spec reviewed by dev team

**Comment by jattasNI** [comment]
This came up again in the context of [Feature 2605261](https://dev.azure.com/ni/DevCentral/_workitems/edit/2605261): Plot the results of the analysis

**Comment by jattasNI** [comment]
Action item is to @fredvisser to prep this for the team to review the designs.

**Comment by fredvisser** [comment]
@NIbokeefe - Need to discuss the open question on how the error outline and the cell focus state coexist on the table.

**Comment by NIbokeefe** [comment]
> @NIbokeefe - Need to discuss the open question on how the error outline and the cell focus state coexist on the table.

Lets look into that at our Thursday sync.
