### ISSUE TITLE
nimble-pause-and-stop-icons visual design request

### ISSUE THREAD

**Issue by searly** [ni/nimble#1785]
## 📌 Request Background

Armstrong project needs nimble icons for the pause and stop buttons. 

https://nio365.sharepoint.com/sites/HylandSpecifications/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FHylandSpecifications%2FShared%20Documents%2FArmstrong%5FProject%2FFigmaWireframes%2FArmstrong%5FWireframes%5Fv4%5FNoTableHeaders%2Epdf&parent=%2Fsites%2FHylandSpecifications%2FShared%20Documents%2FArmstrong%5FProject%2FFigmaWireframes&p=true&ct=1706111827313&or=Teams%2DHL&ga=1

## 🎯 Core Requirements

Need new illustrator files for the two new icons in the execution toolbar.
![image](https://github.com/ni/nimble/assets/5291443/eb1524eb-3892-4fca-9000-ca3e3295fb1f)

## 🍆 Non-requirements

Don't need the play button, we will just use the NimbleIconTriangleFilled.

## 🥅 Acceptance Criteria

- [ ] Visual Design Spec submitted (link)
- [ ] Visual Design Spec reviewed by design team
- [ ] Visual Design Spec reviewed by dev team

**Comment by m-akinc** [comment]
Even though a "play" icon was explicitly a non-requirement, I think it makes sense to provide one rather than applying some rotation to the generic triangle icon. Especially if the `NimbleIconSkipArrow ` were to be redesigned, we would want the "play" icon to match.

**Comment by NIbokeefe** [comment]
> Even though a "play" icon was explicitly a non-requirement, I think it makes sense to provide one rather than applying some rotation to the generic triangle icon. Especially if the `NimbleIconSkipArrow ` were to be redesigned, we would want the "play" icon to match.

Good catch @m-akinc I actually just stopped into this task trying to figure out where the play icon came from, I couldn't find it on my Illustrator document.  I'll include a proper play button with the export.

**Comment by rajsite** [comment]
Released in #1789
