### ISSUE TITLE
Add Text Token for a Body XL font

### ISSUE THREAD

**Issue by NIbokeefe** [ni/nimble#1831]
We need to update our body font collection with our XL Size.  Ethan Searl and James Highland are using our Figma XL Body token for a design in the Armstrong Sequence Step and would immediately benefit from the update.

2 tokens needed:

BodyEmphasized_XT-Large
Source Sans Pro Semi-bold size 16
![Image](https://github.com/ni/nimble/assets/106594349/0e2975bf-3bc9-475d-9cc4-cc84ae06be04)

Body_XT-Large
Source Sans Pro Regular size 16
![Image](https://github.com/ni/nimble/assets/106594349/478fa4c5-a1cc-4798-87fc-67a397d9b043)

**Comment by searly** [comment]
@fredvisser I now see `--ni-nimble-body-emphasized-plus-1-font` but I still don't see `--ni-nimble-body-plus-1-font` token. Is there a token for the 16pt (non-bold) font?

**Comment by rajsite** [comment]
@searly FYI in #1944 we are adding the ` --ni-nimble-body-plus-1-font` token but realized we didn't follow our naming conventions correctly and will have a breaking change to rename ` --ni-nimble-body-emphasized-plus-1-font` to ` --ni-nimble-body-plus-1-emphasized-font`.
