### ISSUE TITLE
Remove static design tokens when backdrop inheritance available

### ISSUE THREAD

**Issue by rajsite** [ni/nimble#1835]
## 🧹 Tech Debt

We have a concept of static tokens used in the dialog and drawer because `::backdrop` pseudo-elements previously did not inherit from their owning element. This is fixed in spec in https://github.com/whatwg/fullscreen/issues/124 and is starting to [release in browsers](https://caniuse.com/mdn-css_selectors_backdrop_inherit_from_originating_element).

As of March 2024, this is released in all browsers. That means we should be able to remove the `design-tokens-static` workarounds by Sept/Oct 2024:

https://github.com/ni/nimble/blob/f041266ec1ab47fff4e4d1908aaf1c40dade14de/packages/nimble-components/src/theme-provider/design-tokens-static.ts#L7-L18

**Comment by rajsite** [comment]
@jattasNI if I address this tech debt (allow us to use design tokens to style the backdrop instead of hard coding), then we could have a "reasonable" workaround for https://github.com/ni/nimble/issues/2304 (they can "temporarily" override the token value).

Think of any concern doing this a little closer to our 6 month window?

**Comment by jattasNI** [comment]
Adopting a feature a month or two before the 6 month window seems fine to me given the lag between when SLE code goes into mainline and when that code actually ends up on a customer machine.
