### ISSUE TITLE
Make tree's selected APIs more consistent with other components

### ISSUE THREAD

**Issue by brianehenry** [ni/nimble#184]
We have a few controls (tree, select, tabs, and listbox in the future) that have two things in common:

1. They use nested elements for declarative configuration
2. They have a concept of "value" or "selected" which can change on user interaction

But the APIs for getting and setting the value of these controls are kind of inconsistent.

Select:
Get: `change` event on main element (`select`)
Set: `value` property on main element (`select`) or `selected` attribute on nested element (`listbox-option`)
Represents the selected item by its `value` attribute

Tabs:
Get: `change` event on main element (`tabs`)
Set: `activeid` property on main element (`tabs`)
Represents the selected item by its `id` attribute

Tree:
Get: `selected-change` event on nested element (`tree-item`)
Set: `selected` attribute on nested element (`tree-item`)
Doesn't have string representation for tree items

It seems like the tree is most out of line here, without top-level properties and events for the selected item(s). This is especially apparent in Angular, since you can't use a two-way binding on the `tree-view` to get and set the selected item. The tree also doesn't have string representations for tree items.

I think it would be nice (though not necessary) to make these APIs more consistent. We could make feature requests to FAST to add the APIs to the Tree or we could make the changes ourselves in Nimble.

**Comment by rajsite** [comment]
Closing as low ROI for a breaking change. Would be a different story if aligning with the events / properties API of a native HTML element but there are none that I am aware of.
