### ISSUE TITLE
Preserve spaces between inline elements, "captureSpacesBetweenElements"

### ISSUE THREAD

**Issue by leanderhoedt** [ni/nimble#1840]
## 😯 Problem to Solve

Currently xliff contents don't keep the spaces between inline elements.

```
<?xml version="1.0" encoding="UTF-8"?>
<xliff version="1.2" xmlns="urn:oasis:names:tc:xliff:document:1.2">
    <file source-language="en-US" datatype="plaintext" original="ng2.template" target-language="de-DE">
        <body>
            <trans-unit id="5478462691360784268" datatype="html">
                <source><x id="PH" equiv-text="fileName1"/> <x id="PH_1" equiv-text="fileName2"/> + 1 other</source>
                <target state="final"><x id="PH" equiv-text="fileName1"/> <x id="PH_1" equiv-text="fileName2"/> + 1 weitere</target>
            </trans-unit>
        </body>
    </file>
</xliff>
```

Is converted to: `{$PH}{$PH_1} + 1 weitere`

While the expected behaviour is that the space between the first & second tag is preserved, resulting to: `{$PH} {$PH_1} + 1 weitere`

## 💁 Proposed Solution

As suggested in one of the github issues in xliff library, the method _xliff12ToJS_, now supports an option `captureSpacesBetweenElements` : https://github.com/locize/xliff/issues/55
since version xliff v6.1.0

My suggestion is to pass `captureSpacesBetweenElements: true` as default option to _xliff12ToJs_. 

I can create a PR.

## 📋 Tasks
- [ ] This is a subtask of the feature. (It can be converted to an issue.)
-->

**Comment by jattasNI** [comment]
This fix should now be available in [version 1.1.4](https://www.npmjs.com/package/@ni/xliff-to-json-converter/v/1.1.4).
