### ISSUE TITLE
Evaluate volatile template bindings

### ISSUE THREAD

**Issue by mollykreis** [ni/nimble#1843]
## 🧹 Tech Debt
We need to evaluate our template bindings for conditional statements that need to be made into `volatile` getters.

One instance of this was found as a bug in the table and fixed (see #1839), but we need to do a more thorough evaluation of our existing bindings to see if any other ones need to be modified.

If there are only a handful of issues to be fix, this issue can cover fixing them. If there are many, we could split this into separate issues and tackle them over time.

**Comment by mollykreis** [comment]
I've dug into FAST's binding code a bit to better understand what is and is not allowed regarding volatile bindings in templates. Here are some key takeaways:

- Bindings in templates are automatically inspected to determine whether or not they are volatile. A template binding is automatically considered volatile if it contains one of the following: `:`, `&&`, `||`, `if`. [See the check in FAST code](https://github.com/microsoft/fast/blob/2968428e6eff438d3e95f86dd0844b4c29950623/packages/web-components/fast-element/src/observation/observable.ts#L372) which uses [this regex](https://github.com/microsoft/fast/blob/2968428e6eff438d3e95f86dd0844b4c29950623/packages/web-components/fast-element/src/observation/observable.ts#L92).
- Aggregate bindings are _never_ considered volatile. Therefore, conditional statements cannot be used within them.
    - An aggregate binding is something of the form `my-attr="foo ${x => x.bar}"`

Therefore, bindings like the following will work correctly:
- `my-attr="${x => x.foo && x.bar}`
- `my-attr="${x => x.foo || x.bar}`
- `my-attr="${x => x.foo ? x.bar : x.baz}`
- `my-attr="${x => x.foo} ${x => x.bar}"`
- `my-attr="foo ${x => x.bar}"`
- `my-attr="${x => ['foo', x.bar && x.baz && 'cool-value'].filter(Boolean).join(" ")}"`

And bindings like the following will _not_ work correctly:
- `my-attr="${x => x.foo ?? x.bar}`
- `my-attr="foo ${x => x.bar && x.baz}`
- `my-attr="foo ${x => x.bar || x.baz}`

**Comment by rajsite** [comment]
Aside: Looks like in the [signals proposal](https://github.com/tc39/proposal-signals) computed signals are always "volatile" so guess that's what template bindings would be:
> Computed Signals track their dependencies dynamically--each time they are run, they may end up depending on different things, and that precise dependency set is kept fresh in the Signal graph.

**Comment by jattasNI** [comment]
We talked about possibly adding CONTRIBUTING docs with guidance about setting volatile. Personally I'd be fine with closing this without docs. If we find ourselves referring back to this comment frequently then we could revisit that.
