### ISSUE TITLE
Storybook parameter docs with collapsible details content have broken styling

### ISSUE THREAD

**Issue by jattasNI** [ni/nimble#1857]
# 🐛 Bug Report

In some stories we have detailed content in the parameters table which is supposed to be hidden behind a collapsible section using a `<details>` element. In mdx files these are rendering incorrectly, with the section no longer being collapsible and the `</details>` closing tag being visible in the rendered page.

## 💻 Repro or Code Sample

https://nimble.ni.dev/storybook/?path=/docs/components-toggle-button--docs

![image](https://github.com/ni/nimble/assets/10500124/372b170d-8d86-4589-a8ec-1656aca62b53)

It's also present in other stories like https://nimble.ni.dev/storybook/?path=/docs/components-drawer--docs

## 🤔 Expected Behavior

Details can be collapsed, no HTML tags in the docs.

## 😯 Current Behavior

See screenshot above

## 💁 Possible Solution

We could either fix this or make an effort to stop putting so much content in the parameters table and instead move it to markdown content outside the table.

## 🌍 Your Environment

macOS Firefox

**Comment by rajsite** [comment]
weird, I only see that in firefox, not chrome

**Comment by m-akinc** [comment]
Firefox gets a completely different DOM than Chrome. Interestingly, if I insert a premature closing `</details>` tag right after the opening one [in the source](https://github.com/ni/nimble/blob/7dacc3221f2e433629c9e9a2192123e70e5d7180/packages/nimble-components/src/patterns/button/tests/doc-strings.ts#L9), I end up with exactly the same DOM and behavior in Chrome, too.

**Comment by fredvisser** [comment]
Fixed in Storybook 8 - see [beta PR](https://60e89457a987cf003efc0a5b-oxsksigtfw.chromatic.com/?path=/docs/components-toggle-button--docs)
