### ISSUE TITLE
Research using 'Field' component to support labels, required state, toggle-tips, helper text, etc. on input controls

### ISSUE THREAD

**Issue by fredvisser** [ni/nimble#1861]
# 🎙 Discussion

[Fluent 2](https://fluent2.microsoft.design/components/web/react/field/usage) uses a `field` which is a combination of a label and any form component, like an input or a select. Optionally, fields can also have info buttons, helper text, and validation states to give people clues about the information they need to enter."

Before we add required states and [toggle-tips](https://github.com/ni/nimble/issues/1690) to all controls, we should evaluate whether we should adjust our current approach, or just go ahead and implement these common patterns directly on each control.

**Comment by jattasNI** [comment]
Discussed in a team meeting and we realized that there are some reasons not to go with this approach:
1. we already have good patterns for sharing things like error text. We think we can come up with similarly good patterns for labels.
2. we want to maintain the flexibility to provide error styling that's specific to a component (e.g. the border color of a switch being red isn't something that could be implemented with this pattern)
3. we don't have a way to have good accessibility where ARIA attributes like labeledby cross the shadow DOM boundary (which this would depend on)
