### ISSUE TITLE
Filterable Select should support dynamic options

### ISSUE THREAD

**Issue by atmgrifter00** [ni/nimble#1866]
## 😯 Problem to Solve

There is a desire to have the `Select` be able to dynamically populate its options according to current filter input. This is primarily useful when all of the possible options are too numerous to include initially, and it's desirable to retrieve subsets of the options as needed by filtered input.

## 💁 Proposed Solution

There are a couple of aspects to supporting this feature properly:
- We need to supply an event that represents input in the filter.
- It is likely we want to create a new `filterMode` setting that represents a mode where we expect clients to provide the set of options dynamically. This is so that the `Select` does not perform its own filtering scheme against the dynamically provided options.

Unanswered Questions:
- What should the `Select` display as its options on successive openings (after providing a previous filter)?
    - Currently the filter string always starts as blank on open. Does this mean that in the new proposed filter mode, every time a user opens the `Select` it's up to the app author to define what options should be provided (is it always just the previous filtered set?)?
- Does the `Select` need to support the "loading" state while its options are being populated (Issue #1311)?

**Comment by jattasNI** [comment]
One use case for this is the work order picker in SLE 
![image](https://github.com/ni/nimble/assets/10500124/65e5db24-e331-4f00-8d08-88016ba71626)

**Comment by jattasNI** [comment]
Note that Blazor support for this feature was split off into #2253
