### ISSUE TITLE
Limit height of dropdown listbox to 10 1/2 elements 

### ISSUE THREAD

**Issue by fredvisser** [ni/nimble#1870]
## 😯 Problem to Solve

The select and combobox listbox has a max-height set to prevent overflow beyond the browser viewport. However, when dealing with a long list of items, there is no specific guideline for limiting the height.

Considering that both the select and combobox controls support autocomplete/filtering, our usage guidance allows for a potentially large number of elements.

To improve user experience, we aim to avoid forcing users to visually scan lengthy dropdown lists. Therefore, we will display a maximum of 10 items at a time. Additionally, we should partially show the 11th item to indicate the presence of more items in the listbox.

**Comment by rajsite** [comment]
This issue only partially addressed our dropdowns (combobox and select) the remainder are split and captured in https://github.com/ni/nimble/issues/2217 (rich text user mention)
