### ISSUE TITLE
Delete old spright npm packages and nuget

### ISSUE THREAD

**Issue by m-akinc** [ni/nimble#1890]
## 🧹 Tech Debt

We changed our plan to no longer have product-scoped Spright packages, so we should remove these published packages:
- `spright-components-stratus`
- `spright-components-armstrong`
- `spright-components-core`
- `spright-angular-stratus`
- `spright-angular-core`
- `SprightBlazorArmstrong`

**Comment by rajsite** [comment]
Nuked them all, and `@ni/nimble-angular-schematics` for good measure

**Comment by rajsite** [comment]
FYI to anyone trying to delete a package in the future. Followed instructions here: https://docs.npmjs.com/unpublishing-packages-from-the-registry

In particular:

> Note: Removing all the collaborators or teams from the package will not unpublish it.

Was a stickler. Using the cli gives no feedback if the package fails to unpublish. I had to do the following:
- Create a new team under the `ni` npm org with just me as a member with Owner permissions in the org
- Move the package to the new team and remove it from all other teams (so I'm effectively the only owner of the package)
- Then in the Web ui on npmjs.com for the package a settings tab pops up where you can delete the package
  - I found that the tab took 5-10 minutes to pop-up after a settings change
  - If the package you are trying to delete has dependents, those packages need to be deleted first. And similarly deleting the dependent took 5-10 minutes before the settings updated and I could delete the parent
