### ISSUE TITLE
Accent appearance variant for nimble-menu-button

### ISSUE THREAD

**Issue by codrutaserban** [ni/nimble#1906]
# 🙋 Feature Request

## 😯 Problem to Solve

In sl-lib-angular a split-button is implemented with a nimble-button and a nimble-menu-button. This split button can be used as a primary button too, and for this, each nimble component needs appearance-variant to be set to accent. 

## 💁 Proposed Solution

Add appearance-variant attribute to nimble-menu-button, as it's available for nimble-button.

<img width="242" alt="Screenshot 2024-03-07 at 10 00 12 AM" src="https://github.com/ni/nimble/assets/1458528/6499148e-45bd-4dbb-be97-d6bf3b11a86b">

Design is available in [Figma](https://www.figma.com/file/PO9mFOu5BCl8aJvFchEeuN/Nimble_Components?type=design&node-id=1295-77205&mode=design)

**Comment by TrevorKarjanis** [comment]
@m-akinc The variant was not added to the [NimbleMenuDirective](https://github.com/ni/nimble/blob/main/angular-workspace/projects/ni/nimble-angular/src/directives/menu-button/nimble-menu-button.directive.ts).

**Comment by m-akinc** [comment]
> @m-akinc The variant was not added to the [NimbleMenuButtonDirective](https://github.com/ni/nimble/blob/main/angular-workspace/projects/ni/nimble-angular/src/directives/menu-button/nimble-menu-button.directive.ts).

Thanks, the issue shouldn’t have been closed yet, as the new attribute needs both Angular and Blazor support. I’ll have a PR up for that later today.
