### ISSUE TITLE
Dependency update PR broke Storybook source snippets

### ISSUE THREAD

**Issue by fredvisser** [ni/nimble#1913]
# 🐛 Bug Report

It looks like PR #1905 was responsible for breaking Storybook source snippets. I.e. 

<img width="1052" alt="Screenshot 2024-03-07 at 3 57 53 PM" src="https://github.com/ni/nimble/assets/1458528/95afd139-6285-4a0c-b336-3eafc6b9dec8">

## 💻 Repro or Code Sample

Source snippets worked with the "Select placeholder (#1842)" PR – [Chromatic Storybook](https://60e89457a987cf003efc0a5b-xtrrplxpre.chromatic.com/)

Source snippets fail with `[object Promise]` with the "Dependency Updates March 2024 (#1905)" PR – [Chromatic Storybook](https://60e89457a987cf003efc0a5b-oqkmtpqxjr.chromatic.com/)

## 🤔 Expected Behavior

<img width="1018" alt="Screenshot 2024-03-07 at 4 02 59 PM" src="https://github.com/ni/nimble/assets/1458528/6572ccdf-bab0-4183-8c3a-09795888abdd">

## 😯 Current Behavior

<img width="1052" alt="Screenshot 2024-03-07 at 3 57 53 PM" src="https://github.com/ni/nimble/assets/1458528/b1648065-d724-4ae1-a1ec-3e5c52e73960">

## 🌍 Your Environment

* OS & Device: macOS 
* Browser: all

**Comment by rajsite** [comment]
Prettier was updated as part of the dependency updates which formats the snippets and [made their APIs async](https://prettier.io/blog/2023/07/05/3.0.0.html#api-1). The transform function in storybook [does not support async](https://github.com/storybookjs/storybook/discussions/24236#discussioncomment-7053590) yet and it's not on the roadmap.
