### ISSUE TITLE
Drawer and dialog tests disabled on Firefox and Webkit due to unexpected DOM contents

### ISSUE THREAD

**Issue by jattasNI** [ni/nimble#1943]
# 🧹 Tech Debt

Two drawer / dialog tests fail in Firefox and WebKit with the following error. They are currently disabled and either need to be fixed and re-enabled or have issues filed upstream and this one marked blocked.

Drawer with default setup supports opening multiple drawers on top of each other #SkipWebkit FAILED
        Expected <nimble-drawer>...</nimble-drawer> to be <nimble-button>. Tip: To check for deep equality, use .toEqual() instead of .toBe().

Dialog supports opening multiple dialogs on top of each other
        Expected <nimble-dialog>...</nimble-dialog> to be <nimble-button current-value appearance="outline">. Tip: To check for deep equality, use .toEqual() instead of .toBe().

**Comment by mollykreis** [comment]
These two tests are failing because of #1936. I don't see a reason to track them separately, so I'm going to update the comments for the disabled tests to point to issue 1936.
