### ISSUE TITLE
Spright documentation and cleanup

### ISSUE THREAD

**Issue by m-akinc** [ni/nimble#1979]
# 🧹 Tech Debt

- [x] Ensure proper CODEOWNERS
- [x] Update repo-wide README and CONTRIBUTING (@rajsite addressing)
- [x] Update spec instructions and templates to consider Spright (e.g. annotate existing templates to say which sections are skippable for Spright contributions)
- [x] Update Storybook to describe / link to info about the purpose of Spright (see ideas in comment below)
- [x] Delete [spright storybook](https://www.chromatic.com/manage?appId=6567b4559057026ee7d80680&view=configure)
- [x] Deprecate [spright repo](https://github.com/ni/spright) and turn off Renovate
- [x] Mark spright repo `internal archive`
   - Delete spright repo (and potentially other deprecated nimble repos) tracked separately in: #2106 
- [x] Delete npm and nuget packages: #1890
- [ ] Bump the spright packages to v1.0 to signify ready for contributions (and start using semver)
- [x] Get Spright logo? _No current or planned need_

**Comment by m-akinc** [comment]
@rajsite 

> Update repo-wide README and CONTRIBUTING (@rajsite addressing)

The README has some Spright references, but CONTRIBUTING does not. Is there more to do for this?

> Deprecate/delete [spright repo](https://github.com/ni/spright)

It has been deprecated, but shouldn't we just delete it? Can't think of any reason we'd want it anymore.

**Comment by rajsite** [comment]
> The README has some Spright references, but CONTRIBUTING does not. Is there more to do for this?

The top-level CONTRIBUTING doesn't discuss dev for the specific packages, it's Getting Started ends with "Now that you can build the monorepo see the CONTRIBUTING.md for the packages you would like to contribute to."

Nothing more to do for that.

> It has been deprecated, but shouldn't we just delete it? Can't think of any reason we'd want it anymore.

Yep. Think @fredvisser was gonna reach out to RDSS to delete all of:
```
https://github.com/ni/nimble-angular/
https://github.com/ni/nimble-angular-schematics/
https://github.com/ni/nimble-blazor/
https://github.com/ni/nimble-tokens/
https://github.com/ni/spright
```

**Comment by jattasNI** [comment]
@m-akinc Taylor pointed out that it would be good to have some pointers about the purpose of Spright in Storybook now that its components are hosted there. Some ideas for this (just a brain dump, I don't feel strongly about doing all of them).
1. a brief blurb on Getting Started that links to a README / CONTRIBUTING / ADR describing Spright's purpose
2. a separate table in Component Status
3. A Docs page for the Spright section (and Nimble components section?) similar to [what we have for the Incubating section](https://60e89457a987cf003efc0a5b-nkfjiskupk.chromatic.com/?path=/docs/incubating-docs--docs)

I'm going to add a new bullet to the checklist in this work item to cover this. I don't mind helping with it but probably won't have time today.
