### ISSUE TITLE
Verify anchor design and update styling if necessary

### ISSUE THREAD

**Issue by m-akinc** [ni/nimble#2011]
# 🧹 Tech Debt

There are a couple differences between our anchor styling and the [Figma design](https://www.figma.com/file/PO9mFOu5BCl8aJvFchEeuN/Nimble_Components?type=design&node-id=1295-76706&mode=design&t=tRlgHtHiOWeXNCIe-0):

1. Visited links have a distinct color (purple)
2. Keyboard focus is indicated by an outline rather than double underline
    - ~~note: we should push back on this visual design since the text could flow across multiple lines, which would look weird if we try to draw a box around it~~
    - An outline will work fine – 
![Screenshot 2024-05-09 at 2 37 18 PM](https://github.com/ni/nimble/assets/1458528/2f60dc3f-b6e2-468c-abc3-0ceb58b31044)

These were not the designs when we implemented the anchor. We should confirm whether they are what we want (with Brandon) and implement if so.

**Comment by jattasNI** [comment]
We decided yesterday to go forward with the box approach. Moved to Current Iteration since the table keyboard navigation feature revealed that the current focus styling isn't prominent enough.

**Comment by m-akinc** [comment]
After further discussion, we've decided:
1. Visited links will not have a different color. This decision may be revisited in the future based on specific use cases or client requests.
2. Keyboard focus will continue to use a double underline, but the link color will change to make it more visually prominent. There is a technical issue with having an outline that goes outside of the bounds of the link (and remain visible) and being able to ellipsize truncated text, because of the need to use `overflow: hidden`.
