### ISSUE TITLE
New icons for table expand – visual design request

### ISSUE THREAD

**Issue by fredvisser** [ni/nimble#2046]
# 🎨 Visual Design Request

1. The icons used in the 'table-fullscreen' and 'table-not-fullscreen' buttons are on the top-right of the screen, so the arrows should point up and to the right. Our current icons would work if the buttons were on the top-left, but alas. Can we make new icons with each turned 90º?

<img width="295" alt="Screenshot 2024-04-29 at 10 12 24 AM" src="https://github.com/ni/nimble/assets/1458528/f04c41a0-06aa-4aed-8306-6a6116193f72">
<img width="58" alt="Screenshot 2024-04-29 at 10 13 05 AM" src="https://github.com/ni/nimble/assets/1458528/863eddd4-8d22-4bf6-8619-6ebbd73beb8f">

**Comment by NIbokeefe** [comment]
@fredvisser @jattasNI 

Please the related task icon tokens plus additional icon tokens 

arrow-down-left-and-arrow-up-right_16x16
![Image](https://github.com/ni/nimble/assets/106594349/ebb7f715-bd6d-487e-9892-298be0492b2c)

Tags: Collapse, Shrink, Reduce Size

arrow-up-right-and-arrow-down-left_16x16
![Image](https://github.com/ni/nimble/assets/106594349/0a8c0ab5-2b72-4317-9c5d-544a035d0227)

Tags: Expand, Grow, Enlarge Size

Additional adds:

debug_16x16
![Image](https://github.com/ni/nimble/assets/106594349/2fb5d9fe-f6c4-401d-8451-fbffa7d2ac60)

Tags: Debug, Troubleshoot

ai-magic-circle_16x16
![Image](https://github.com/ni/nimble/assets/106594349/326d0de0-0aef-4843-b946-cf4c4a6069df)

Tags: Artificial Intelligence, Magic, Advanced Automate

**Comment by jattasNI** [comment]
@NIbokeefe I've got a PR up to add these icons (and the clean icon). Just want to double check that the intent with the multi-colored AI icon is that it shouldn't change at all in dark/color theme and that clients wouldn't ever set its "severity" to error/warning. 

You can see what this looks like here: https://60e89457a987cf003efc0a5b-gmwijpogcx.chromatic.com/?path=/story/components-icons--icons&globals=backgrounds.grid:!false;backgrounds.value:!hex(252526)

**Comment by NIbokeefe** [comment]
@jattasNI All good questions and points.  

Looks like that version is only going to be good for light UI.  Color UI could can only be White, so that's an interesting aspect where it would not be in full color.

I don't imagine allowing status to this one.

Let me circle back around for these questiions, I'm not entirely sure the whole scope of where and how the AI team will use this asset.  I'm glad to have the Light UI version for now so they have something, and hopefully should have more info later.
