### ISSUE TITLE
Remove peerDependency on `@types/linkify-it`

### ISSUE THREAD

**Issue by rajsite** [ni/nimble#2061]
# 🧹 Tech Debt

In #2056 a peer dep was added on `@types/linkify-it` to nimble-components due to: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/69355#issuecomment-2088994473

If that thread is resolved we can remove the manual peer dep on `@types/linkify-it`.

**Comment by brc-dd** [comment]
Can you try removing it and regenerating lock file? `@types/markdown-it` v13.0.8 is out with the fix.

**Comment by rajsite** [comment]
@brc-dd that seems to have worked nicely!
