### ISSUE TITLE
Move angular-workspace into packages

### ISSUE THREAD

**Issue by rajsite** [ni/nimble#2084]
# 🧹 Tech Debt

As apart of [creating SprightBlazor](https://github.com/ni/nimble/issues/1976) and forming blazor-workspace in the packages folder it was determined we likely could also move the angular-workspace to the packages folder for consistency.

- [x] Move `angular-workspace` into the packages folder. 
   -  As part of this also flatten the unnecessarily deep hierarchy, ie `/angular-workspace/packages/ni/nimble-angular` -> `/angular-workspace/nimble-angular`
- [x] Update external documentation (AzDo wikis) to reference the new nimble-angular location
- [ ] Ignore the [refactoring commit](https://github.com/ni/nimble/commit/e83c8ba9f06850acd6a303d257ec9033c0c5d115) in blame history: https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view

**Comment by jattasNI** [comment]
Links are being updated in this PR so I checked off that task item. https://dev.azure.com/ni/DevCentral/_git/Skyline/pullrequest/749596

@rajsite I'll leave it up to you to decide whether you still want to do the git history cleanup or just close this out.

**Comment by rajsite** [comment]
@jattasNI thanks for putting that up and naw lets close this
