### ISSUE TITLE
Error icon is incorrectly spaced in nimble-text-field

### ISSUE THREAD

**Issue by mollykreis** [ni/nimble#2090]
# 🐛 Bug Report

In the nimble-text-field, the error "!" icon should be 8px from the edge of the component. However, it is currently 8px from the border, which makes it 9px from the edge of the component.

We should evaluate whether this is the case with other components as well.

## 🤔 Expected Behavior

The error icon in components should be 8px from the edge of the component, not 8px from the border of the component.

## 😯 Current Behavior

The error icon is 8px from the border of the component.

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* Version [e.g. 1.8.0]

**Comment by mollykreis** [comment]
When this is fixed, we should remove the workaround added in [this azdo PR](https://dev.azure.com/ni/DevCentral/_git/Skyline/pullrequest/707074) to make the checkbox error icon align with the textfield error icon. Specifically, an extra 1px of padding was added to the right of the checkbox's error icon.

**Comment by mollykreis** [comment]
The current visual designs have the spacing as 4px rather than 8px. We should double-check the current state of the designs before fixing this issue.

**Comment by rajsite** [comment]
I'm gonna capture this old comment here but don't have a precise idea of the outcome yet.

My concern is that trying to include the border size as part of the spacing is a figma problem. Figma's settings can be changed to align with CSS, but not CSS's out of the box behavior. I think trying to fight this everywhere is going to be very difficult to get consistent. Particularly for compositions outside of nimble (even if we accurately handle the spacing everywhere).

From Brandon:
> Milan Raj Jesse Attas Aiden Ducey-Kline Here is an experiment with changing the stroke excluded to included setting.  
> <img width="1045" alt="Untitled" src="https://github.com/user-attachments/assets/c82a61dd-4cc5-43df-bfeb-2dee5b082d1f">
> The summary is that the change can be made if we decide it's truly helpful but will require a fair amount of work to adjust all the margin and padding settings. 
> 
> Also, when the width of the stroke is changed, the reading of the padding in-between is accurate; it does not have the same issue as in code where the width in-between stays the same regardless of the stroke width.
