### ISSUE TITLE
nimble-checkbox has incorrect height

### ISSUE THREAD

**Issue by mollykreis** [ni/nimble#2091]
# 🐛 Bug Report

The nimble-checkbox height currently is driven by the line height of its text, which isn't the way the component should be. As a result, the checkbox without text is 16px tall, and the checkbox with text is 18px tall.

## 🤔 Expected Behavior

The checkbox should have a height that isn't controlled by the line height of the text. According to @NIbokeefe, we also need to make sure it is a multiple of 4, since that is standard for all nimble sizes. We may need to work with him to nail down the exact size it should be (20px?).

## 😯 Current Behavior

The height of the checkbox is the maximum of the checkbox square size (16px) and the text's line height (by default 18px).

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* Version [e.g. 1.8.0]

**Comment by jattasNI** [comment]
@fredvisser will add some more context about a related challenge of figuring out how apps should position a checkbox in a 2-column layout where other components will be 32 pixels tall.

**Comment by NIbokeefe** [comment]
Checkbox are now centered within a 24px and 32px container to solve this issue.  We are mostly moving towards single column layouts where it would not be in horizontal alignment with other controls.  In any context where it is in a multi-column alignment such as toolbars, etc. the control will Top-Center with the control next to it (not top aligned with the control label).  

![Image](https://github.com/user-attachments/assets/ba28c33e-7229-4005-b286-b6afb3f4d99f)
![Image](https://github.com/user-attachments/assets/cb34eb96-f8b4-4cf5-8195-99d37902e869)

![Image](https://github.com/user-attachments/assets/44da269d-e758-48c3-bf95-940e2bd81766)
