### ISSUE TITLE
Prettier not running on storybook files

### ISSUE THREAD

**Issue by m-akinc** [ni/nimble#2136]
# 🧹 Tech Debt

Prettier does not seem to be formatting on save like it used to when the story files were part of the `nimble-components` package.

**Comment by m-akinc** [comment]
Check with Jesse to make sure there aren't painful merges.

**Comment by fredvisser** [comment]
We need to update the .prettierignore file:

```
/*
!/packages
/packages/*
!/packages/storybook
!packages/nimble-components
```
