### ISSUE TITLE
Visual Design for Available and Installed Items in Menu

### ISSUE THREAD

**Issue by NIbokeefe** [ni/nimble#2145]
# 🎨 Visual Design Request

Available and Installed Items in Menu

![Image](https://github.com/ni/nimble/assets/106594349/949477aa-03a7-4b46-910f-5f63c13ffebb)
 

## 🎯 Core Requirements

- display the currently selected item when menu is open and closed
- indicate the current selection in the dropdown list
- indicate if any of the items in the dropdown list are already installed
- support showing both the primary and secondary package versions
- support a unique set of dropdown list items per row

## 🥅 Acceptance Criteria

- [ ] Visual Design Spec submitted (link)
- [ ] Visual Design Spec reviewed by design team
- [ ] Visual Design Spec reviewed by dev team

**Comment by fredvisser** [comment]
A few different options



![Image](https://github.com/user-attachments/assets/2178f0b6-8d3a-4cff-91ec-e4cf1b10a8e4)
