### ISSUE TITLE
Intermittent rich text tests: "should filter and commit first mention into the editor on Enter"

### ISSUE THREAD

**Issue by jattasNI** [ni/nimble#2150]
# 🧹 Tech Debt

These tests are intermittent and are going to be disabled in #2151 and #2160:
"RichTextEditorMentionListbox user mention via mention list box..."
1. "should commit mention into the editor when clicked"
2. "should commit mention into the editor on Enter"
3. "should commit mention into the editor on Tab"
4. "should filter and commit first mention into the editor on Enter"
5. "should filter and commit first mention into the editor on Tab"
6. "should show mention popup for multiple mention configuration elements"

**Failing builds**
1. https://github.com/ni/nimble/actions/runs/9353948801/job/25745664409?pr=2149
2. https://github.com/ni/nimble/actions/runs/9354603119/job/25747812654#step:17:2113
3. https://github.com/ni/nimble/actions/runs/9370555481/job/25797800389#step:17:2095
7. https://github.com/ni/nimble/actions/runs/9374325766/job/25810106139?pr=2158

**Error message**
[test-concurrent:nimble-components] [test-chrome:verbose] 1) should filter and commit first mention into the editor on Enter
     RichTextEditorMentionListbox user mention via mention list box
     Uncaught InvalidStateError: Failed to execute 'collapseToEnd' on 'Selection': there is no selection. thrown

**Context**
Nimble updated dependencies recently in #2148 and that included a change to prosemirror so it's possible that contributed to this.

**Comment by jattasNI** [comment]
@vivinkrishna-ni let me know if you'd like an AzDO bug to track this

**Comment by m-akinc** [comment]
Added three more tests that I had fail on me.
