### ISSUE TITLE
Several SLE tests failing with latest version of nimble-select

### ISSUE THREAD

**Issue by jattasNI** [ni/nimble#2175]
# 🐛 Bug Report

In [this Renovate PR](https://dev.azure.com/ni/DevCentral/_git/Skyline/pullrequest/731263), several tests that use select are failing because an unexpected item is selected.

There are also tests failing in app PRs ([example](https://dev.azure.com/ni/DevCentral/_git/Skyline/pullrequest/731279))

## 💻 Repro or Code Sample

[Failing unit tests](https://dev.azure.com/ni/DevCentral/_build/results?buildId=9226029&view=ms.vss-test-web.build-test-results-tab&runId=23213713&resultId=101737&paneView=debug)

[Failing acceptance tests](https://dev.azure.com/ni/DevCentral/_build/results?buildId=9228723&view=ms.vss-test-web.build-test-results-tab&runId=23216184&resultId=100007&paneView=debug)

## 🤔 Expected Behavior

Tests pass

## 😯 Current Behavior

Tests fail with errors like 
`Expected 'Select workspace' to be 'Default'.`

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* Version [e.g. 1.8.0]

**Comment by rajsite** [comment]
This issue was closed by the revert in https://github.com/ni/nimble/pull/2176
The follow-up issue for the reverted behavior to address in the future is https://github.com/ni/nimble/issues/2177
