### ISSUE TITLE
Address FAST project re-alignment

### ISSUE THREAD

**Issue by jattasNI** [ni/nimble#2207]
# 🧹 Tech Debt

Various FAST packages that we depend on are going away or changing their mission:
https://github.com/microsoft/fast/issues/6955

We need to come up with a migration plan so that we don't get stuck in a situation where there is a bug / feature gap in our dependency that can't be fixed.

This is the high level issue to trigger brainstorming; we'll probably break it into separate issues / HLDs.

Decision points include:
1. `fast-foundation` component base classes are going away
2. `fast-foundation` utilities are going away
3. `fast-element` legacy branch is receiving very little attention in favor of their vNext branch

**Comment by jattasNI** [comment]
First step is for @rajsite to schedule a team brainstorming session to sketch out a rough plan.

**Comment by rajsite** [comment]
HLD for direction merged
