### ISSUE TITLE
Unexpected multiselect behavior in table

### ISSUE THREAD

**Issue by m-akinc** [ni/nimble#2239]
# 🐛 Bug Report

I ran into some use patterns that resulted in behavior that seems wrong.

## 💻 Repro or Code Sample

In this clip, we can see that deselecting a row causes it to be "registered" as the starting point for a shift+click/space multi-select. I would have expected that shift+clicking Sam while nothing else is selected would only select Sam.
![deselect_becomes_anchor](https://github.com/ni/nimble/assets/7282195/c4e02d71-7863-478d-b93a-7656b5001675)

Here is another case where deselecting a row results in weird behavior. We deselect a row inside a selected range, then shift+click a row beyond the range. I'm not sure what the right behavior is, but I would probably have expected:
1. Only Sam is added to the selection (i.e. same as without the shift key)
2. Everything between Sam and Michael (in this clip there aren't any other rows) inclusive is added to the selection

The fact that Joe, which we just deselected, gets re-selected seems wrong.
![deselect_becomes_anchor2](https://github.com/ni/nimble/assets/7282195/eab769b1-8fe3-4834-919b-a47a02e24a4e)

I looked for some documentation to use as the basis for what is and isn't correct behavior, but I couldn't find any. The [ARIA treegrid guidance](https://www.w3.org/WAI/ARIA/apg/patterns/treegrid/) doesn't even suggest using shift+space, but instead talks about shift+arrow.

**Comment by msmithNI** [comment]
One note about `Shift-Space`: if a cell is focused, `Shift-Space` will select the row that cell is in (and that did come from the ARIA guidance, plus it makes it easier to select a row without needing to `ArrowLeft` all the way back to row selection, if you're in cell selection mode).
We probably want to maintain that behavior, so we'll need to reconcile the logic for that with whatever we decide for general Shift-key row selection.

2 general options for Shift-Space come to mind:
- Shift-Space will select all rows between the selected rows and the currently focused row. (This is what our [older row selection HLD](https://github.com/ni/nimble/blob/main/packages/nimble-components/src/table/specs/table-row-selection.md#general-behavior-and-design) says. It probably has corner cases to consider, like non-contiguous selections though.)
- Shift-Space will only ever select/unselect a single row (the row that's focused) (even in multiselect mode) for keyboard selection. You could still Shift-click to select a range with mouse selection.
