### ISSUE TITLE
Finalize styling of menu button table column

### ISSUE THREAD

**Issue by mollykreis** [ni/nimble#2247]
# 🐛 Bug Report

There are some changes that have been proposed to the styling of the menu button column that are not being addressed in the initial submission (#2204). Specifically, the following changes have been proposed by Brandon and Fred:

- Make the button the standard height (32px) rather than the slim control height
- ~~Change the left/right padding within the button to 8px rather than 16px~~ _Conceding that the 16px padding is sufficient given that there isn't a supported way to update the padding._
- ~~Change the font of the button to no longer be bold so that the text doesn't stand out from the rest of the table~~ _Leaving the font bold because this is the convention within nimble to show that text is interactable (such as in a ghost button)_

~~These changes, however, are not easily achieved using supported styling on the button.~~ We also need to evaluate how a 32px button looks with hover and focus states of the row/cell in the table.

We should also look into creating a focus theme matrix for the column to have chromatic testing for the focus state of the button within the table.

## 🤔 Expected Behavior

The goal is to make the menu button look more like a select within the table.

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* Version [e.g. 1.8.0]

**Comment by mollykreis** [comment]
I chatted with @fredvisser, and we've come to the decision that the only change we'll make at this time to the styling of the menu button is to make it the default height of 32px rather than as-is (24px).

**Comment by rajsite** [comment]
@mollykreis for future reference can you capture on the struck out lines in the description why we aren't pursing the padding change and non-bold text?
