### ISSUE TITLE
Table rows have incorrect indention after grouping & ungrouping column

### ISSUE THREAD

**Issue by mollykreis** [ni/nimble#2284]
# 🐛 Bug Report

When the `nimble-table` has hierarchy enabled (`parentIdFieldName` set), grouping and then ungrouping a column causes the first cell to be incorrectly misaligned with the header.

This is due to a bug in TanStack that was discussed on the TanStack discord: https://discord.com/channels/719702312431386674/803508359378370600/1174456230790561902

Nothing, however, came from the discussion on discord other than confirmation that the behavior we're seeing is likely a bug in TanStack.

## 🤔 Expected Behavior

Grouping and then ungrouping a column with hierarchy enabled should result in the initial cell indentation.

## 😯 Current Behavior

Grouping and then ungrouping a column with hierarchy enabled does not return cells to their initial indentation.

![Grouping With Hierarchy Bug](https://github.com/user-attachments/assets/d33afbdf-5b0a-4e35-b88e-dd0076c41813)

## 💁 Possible Solution

File a bug to TanStack and potentially try to upstream a fix. 

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* Version [e.g. 1.8.0]

**Comment by m-akinc** [comment]
May be fixed in `18.19.3`?

**Comment by jattasNI** [comment]
(which can be uptaken once #2289 is fixed)
