### ISSUE TITLE
Allow hiding the dialog backdrop on a NimbleDialog

### ISSUE THREAD

**Issue by epetersoni** [ni/nimble#2304]
# 🙋 Feature Request

Provide a way for a `NimbleDialog` to hide the drop shadow.

## 😯 Problem to Solve

The drop shadow causes some issues with the way we're using a popup `NimbleDialog` with `InstrumentStudio`.

We're creating a modal WPF window that uses the same size as the WPF application and fill itself with a `WebView2` that is just showing the `NimbleDialog`. This allows Nimble to center the dialog content within the modal window.

* The drop shadow is inconsistent with other `InstrumentStudio` modal dialogs.
* There are issues if the main WPF window is partly offscreen. The modal window gets positioned to be entirely on screen, which makes the drop shadow visible over parts of whatever is behind the `InstrumentStudio` window. It seems like any solution to this would get complex.

## 💁 Proposed Solution

Provide a new property on the `NimbleDialog` that allows the drop shadow to be hidden.

The property could be a `bool` that allows the shadow to be shown or hidden.
Or maybe a floating point value allowing the opacity of the shadow to be set.

**Comment by jattasNI** [comment]
Here's a screenshot illustrating the issue about the window being partly offscreen. The second webview in which the dialog is presented is not partly offscreen, so the overlay isn't positioned correctly. The suggestion from designers is that the dialog positioning would be ok if the overlay weren't visible.

<img width="1229" alt="Screenshot 2024-07-29 at 2 43 50 PM" src="https://github.com/user-attachments/assets/6ffe5406-8be1-4a94-947f-4406ce35c549">

**Comment by jattasNI** [comment]
Assigned to @rajsite to document his concerns with exposing a first class API for this but also to see if we can find a workaround for this narrow use case.

**Comment by searly** [comment]
@jattasNI @rajsite Should we be able to workaround this after the linked token change now? Can we get an updated version of the NimbleBlazor nuget published to try it out?

**Comment by rajsite** [comment]
Sorry about that, I meant to get back to y'all last week 😅. The summary is:

- We aren't sure about adding this configurability as a supported feature yet.
  - A big part of supporting a new configuration is having crisp recommendations and usage guidelines
  - We wouldn't recommend disabling the backdrop for any browser running nimble apps or desktop running nimble apps using just blazor for the UI.
  - We are also not sure if it makes sense as a general feature we would recommend for all hybrid apps either yet. Some considerations:
    - Feels like ideally we should be able to fit the browser window canvas to cover the application view port better, in which case the drop shadow would cover the full app window and be centered in the window space regardless of window placement. It seems like some more investigation might be needed before we propagate the pattern / recommend it generally.
    - Alternatively if we do start building up a set of styling tweaks that apply only to the hybrid nimble + wpf use-case we probably want that to be easier to opt-in / opt-out instead of needing per control configuration.
- I think we need to keep collecting the points on hybrid nimble integration so we have clear recommendations to give across apps and a good api surface. 

Given the above I did put a change in that configures the backdrop for all modals (currently dialog and drawer) with a design token. As a workaround the design token value can be overridden with CSS like the following (with the known caveat that overriding token values is generally not recommended but we are aware of the usage here and why the workaround is being used): 

Component razor template:

```html
<NimbleDialog class="my-dialog" TCloseReason="DialogResult" @ref="_dialog">
    <span slot="title">Have a nice day</span>
    <div>And also a nice week</div>
</NimbleDialog>
```

Component css:
```css
::deep nimble-dialog.my-dialog {
    --ni-nimble-modal-backdrop-color: transparent;
}
```

**Comment by rajsite** [comment]
> Can we get an updated version of the NimbleBlazor nuget published to try it out?

Oh, interesting, I would have expected a release to be made. I think I see the issue. I'll get a fix up for that.

**Comment by rajsite** [comment]
@searly @epetersoni workaround described above should be in `NimbleBalzor@17.6.2` 👍

**Comment by searly** [comment]
Thanks @rajsite ! Its working as expected.
