### ISSUE TITLE
Don't change row hover highlight during table scroll

### ISSUE THREAD

**Issue by fredvisser** [ni/nimble#2312]
# 🐛 Bug Report

The nimble-table moves the row hover highlight during page or table scroll, which adds unnecessary visual noise to the scrolling process. 

For example, compare nimble-table:
https://github.com/user-attachments/assets/00cb4136-b37e-4071-9bff-24d412e9f106

with ag-grid:
https://github.com/user-attachments/assets/24b4b240-dde6-496e-98f0-f1bffb81d41d

## 💻 Repro or Code Sample

https://nimble.ni.dev/storybook/?path=/story/components-table--table&args=data:LargeDataSet;selectionMode:single

## 🤔 Expected Behavior

[NNGroup suggests](https://www.nngroup.com/articles/timing-exposing-content/) that:

>For hover interactions, the timing guidelines for speed of visual feedback and exposing hidden elements must be broken down into more steps:
>Mouse cursor enters target area: display visual feedback within 0.1 seconds.
>Wait 0.3–0.5 seconds.
>If cursor remains stopped within target area, display corresponding hidden content within 0.1 seconds.
>Keep displaying the exposed content element until the cursor has left the triggering target area or the exposed content for longer than 0.5 seconds.

But we can evaluate if that is consistent with other tables.

**Comment by m-akinc** [comment]
See if it can be done quickly and easily. If not, throw it back on the backlog.

**Comment by rajsite** [comment]
Wonder if this behavior on mobile (Android Chrome) is related. With single selection choose a row and then as scrolling looks like a hover state moves around. Have to tap outside the table to get it to stop.

https://github.com/user-attachments/assets/8b66b166-22c0-42df-9a50-4a72281f9fe7

**Comment by fredvisser** [comment]
Yeah - I see the same thing ☝️ with mobile Safari

https://github.com/user-attachments/assets/fb2722b7-3a95-4e71-988e-87bf481f858e

**Comment by rajsite** [comment]
Oh, for the mobile examples this dude noticed it last year and commented on the chrome issue for this currently expected behavior: https://issues.chromium.org/issues/40364091#comment40
