### ISSUE TITLE
Drop down height of nimble-select fixed to 350px instead of full available height

### ISSUE THREAD

**Issue by PetitCalgon** [ni/nimble#2323]
# 🐛 Bug Report

In previous version of nimble-select (<26.0.0 and Angular 17) the drop down of the nimble-select would take the full available height till browser bottom border, since version 26.0.0 (oder little bit older, i dont know exactly) the drop down height is fixed to 350px and i see no possibilities to change it

## 💻 Repro or Code Sample

Open your Storybook and select under slots "Many options", then open the select drop-down
https://nimble.ni.dev/storybook/?path=/docs/components-select--docs

## 🤔 Expected Behavior

The drop down sould take the full available height till browser bottom border

## 😯 Current Behavior

The drop down is limited to 350px

## 🔦 Context

Seems to been seen first after Angular update and version 26.0.0 of @ni/nimble-angular.
The behavior is correct with version 24.4.6 of @ni/nimble-angular.

## 🌍 Your Environment

* OS & Device: Windows 10
* Browser: Edge version 127, Firefox version 127

**Comment by rajsite** [comment]
@PetitCalgon there was an intentional change to limit dropdown heights to 10.5 items, see: https://github.com/ni/nimble/issues/1870

The intention is that for a large set of options (>15) that the select is configured as filterable to enable quick navigation / inspection of large sets: https://nimble.ni.dev/storybook/?path=/docs/components-select--docs

And very large sets enable dynamic filtering and showing only partial sets: https://nimble.ni.dev/storybook/?path=/docs/components-select--docs#dynamic-options

Those are the expected workflows for managing large sets of options. Do those cover the workflow you are implementing? If not can you give details into how your workflow differs?

**Comment by PetitCalgon** [comment]
Thank you.
Our usecase is little bit different.
We use the nimble-select (and never the combobox) for medium list (about 25 items)
Two worklows:
- a list of date intervals (a selection of week, months, quartals)
- a list of jupyter notebooks (grouped with nimble-list-option-group)

For larger list with runtime values (for example batches, serial numbers, etc.), we have a nimble-drawer with a textbox to filter the entries and for every entry a checkbox or radio button (for multi/single choice) + buttons ok/cancel

Displaying only 10 1/2 items in my intervals / jupyter notebooks list is unclear for our users.

Is ther a way to change the height, or giving me the possibility to choose which height I want, standard (=10 1/2 items), big (~ 20/21 items), no limit ?

**Comment by rajsite** [comment]
> Displaying only 10 1/2 items in my intervals / jupyter notebooks list is unclear for our users.

**Can you give screenshots and explain why it is unclear?**

In addition some things to consider: 
- the list does scroll so users can scroll to their need option
- long lists by default mean lots of mouse travel for users when many options are shown
- the window can be various sizes as set by the user, and the select dropdown will only fill the space available. So it should clear that more options are available regardless of current window size. All 20+ items will not be visible in a small window / mobile window.
- for a list of 25 items filtering should be enabled. Particularly for a list of intervals with a known structure, I'd hope users can quickly filter the list in a couple characters. Typing "3/" or "Mar", etc to filter quickly, etc

**Comment by PetitCalgon** [comment]
Hello Raj,

I'm sorry "unclear" is the wrong translation, i meant something like too few items are displayed.

Here are some screenshot for you:
Old select dates version with long list
![old-select-dates](https://github.com/user-attachments/assets/d4ff0b40-bb3b-4f26-9f83-4ec8f0174db5)

Versius new select dates version with short list:
![new-select-dates](https://github.com/user-attachments/assets/c4f13496-d10f-40a1-8950-07db3c4cc5f4)

Same for old jupyter notebooks (with own CSS style for grouping, older version where nimble-group-item was not available)
![old-select-notebooks](https://github.com/user-attachments/assets/6c820dae-85cf-46ee-b3b2-5bbaa02e2950)

Versius new version
![new-select-notebooks](https://github.com/user-attachments/assets/d8873d93-e877-4971-82a8-bfcc625b42bc)

Don't forget, that the users (for example managers) are pretty bad UX user, they can't assimile the difference between a combobox, an auto-complete and a select.

With the old version of the select, in 2 mouse-click, they would have select the notebook or the wanted date intervall.
With your solution and autocomplete / filter, they would have to click on the combo, delete the text (with delete key, or better right key and countless backspace till everything is gone), then would type something, choose it with the mouse ...

So 2 mouse-click or countless keystrokes?

**Comment by rajsite** [comment]
@PetitCalgon Thank you for showing some screenshots. Neither of your new version examples demonstrate the above recommendation of [enabling `filter-mode: standard` for the select](https://nimble.ni.dev/storybook/?path=/story/components-select--select&args=filterMode:standard;optionsType:ManyOptions) for large sets of options.

We do believe that for both of these use cases enabling filtering on the select (not switching to a combobox, etc) will give a consistent user experience across NI products for selecting an option amongst a large list of options. If you are employed at NI / Emerson I'd recommend reaching out to @fredvisser to discuss the use-cases further and to share your application with the Nimble team so we are aware of your designs / use-cases.

**Comment by PetitCalgon** [comment]
We'll give it a try, but please provide an option to localize the "Search" placeholder
`<input class="filter-input" aria-controls="listbox-1" aria-activedescendant="option-27" placeholder="Search" value="">`

Our application has english, german, french and japanese languages.

**Comment by rajsite** [comment]
Specifically for the search field localization see configuring the "filter search" text configuration in the docs Meyers referenced: https://nimble.ni.dev/storybook/?path=/docs/tokens-label-providers--docs

Also @PetitCalgon if you are an NI employee, please reach out to @fredvisser on teams to make sure you're added to the NI org on GitHub and to introduce yourself and your app. Thanks.

**Comment by PetitCalgon** [comment]
I'm not an NI employee, I'm an Hensoldt employee in Germany working with SystemLink and writing plugins for SystemLink.

**Comment by rajsite** [comment]
> I'm not an NI employee, I'm an Hensoldt employee in Germany working with SystemLink and writing plugins for SystemLink.

Ah, good to know and welcome! 🎉
