### ISSUE TITLE
Select component resizes when an option with long text is selected

### ISSUE THREAD

**Issue by jattasNI** [ni/nimble#2336]
# 🐛 Bug Report

The width of the select has started changing depending on which option is selected. It's supposed to stay the same width and show an ellipsis if the option is too long to fix.

## 💻 Repro or Code Sample

https://nimble.ni.dev/storybook/?path=/docs/components-select--docs

Change the default slot to "wide options" and toggle the value between a wide and a narrow option

https://github.com/user-attachments/assets/afdd61c0-b458-41e6-b6d9-af9cd7fa3f70

## 🤔 Expected Behavior

The component doesn't resize

## 😯 Current Behavior

The component resizes

## 💁 Possible Solution

I suspect this broke with #2315 because that PR touched the component's styling and a build from shortly before then doesn't exhibit the bug. FYI @msmithNI 

## 🌍 Your Environment

macOS Firefox

**Comment by msmithNI** [comment]
I don't think this is a bug - if you change the component style from `min-width: 250px` to `width: 250px`, the component stays the same width and ellipsizes.

Won't close this issue yet so we can discuss if we want to take out the `min-width` style in some or all cases. I changed it so long labels entered interactively would auto-grow the component, as you can see in other stories like for the text field. But we could change it back if we want to show the ellipsizing behavior.

**Comment by jattasNI** [comment]
Ah right, I forgot about that discussion. The current behavior in storybook doesn't feel like the right default to me (obviously, since I thought it was a bug). I'm ok with the text field storybook behavior where long labels will grow the control but long entered values won't. Ideally we could achieve the same for the select but if not then my vote would be to turn off the behavior of long labels growing the control in storybook.

Regardless of what default we choose in storybook it might still be worth a discussion of whether we want to document any of these sizing behaviors.

**Comment by m-akinc** [comment]
Update storybook and usage guidance
