### ISSUE TITLE
Scrollable tabs visual design request

### ISSUE THREAD

**Issue by fredvisser** [ni/nimble#2337]
# 🎨 Visual Design Request

## 📌 Request Background

We've received [multiple requests](https://github.com/ni/nimble/issues/1509) to handle tabs that end up being wider than the parent container. I.e. Long titles on the tabs or many tabs, or both.

I'm proposing that we use a common pattern, and allow the tabs to scroll on overflow. 

## 🧑‍🔬 Research

The following design systems scroll the tabs controls on overflow. To pick one, [Shoelace](https://shoelace.style/components/tab-group#scrolling-tabs) does a nice job of showing that the view is scrollable with clickable arrows.

- https://opensource.adobe.com/spectrum-web-components/components/tabs-overflow/
- https://js.devexpress.com/Angular/Demos/WidgetsGallery/Demo/Tabs/Overview/MaterialBlueLight/
- https://base.uber.com/6d2425e9f/p/2345e5-tabs
- https://polaris.shopify.com/components/navigation/tabs?example=tabs-default
- https://carbondesignsystem.com/components/tabs/style/
- https://shoelace.style/components/tab-group
- https://workbench.gusto.com/components/tabs/usage/#reach-skip-nav
- https://vivid.deno.dev/components/tabs/
- https://mesadesignsystem.lanl.gov/components/tabs/overview

## 🎯 Core Requirements

If we were to implement the [Shoelace pattern](https://shoelace.style/components/tab-group#scrolling-tabs), I assume it would look something like the following:

![image](https://github.com/user-attachments/assets/1a8740cf-81e0-4826-bfff-bf801f1567d8)

We wouldn't reserve space for the arrows, but if they're required they would appear.

Any concerns with this approach? 

## 🥅 Acceptance Criteria

- [x] Visual Design Spec submitted ([link](https://www.figma.com/design/PO9mFOu5BCl8aJvFchEeuN/Nimble_Components?node-id=11133-60362&t=m8ZyqYTEG431ZRnJ-4))
- [x] Visual Design Spec reviewed by design team
- [x] Visual Design Spec reviewed by dev team

**Comment by jattasNI** [comment]
Notes from team review:

1. there shouldn't be a visible scrollbar on any OS
2. when a tab has keyboard focus, left/right arrow keys should continue to move to the next tab as they do today. That tab should scroll into view if it was off screen.
3. don't need to worry about keeping the current tab within view
4. start by matching shoelace's behavior when an arrow button is clicked: scrolling one "page width" (i.e. all the currently visible tabs scroll out of view). We can start there, play with it and see how it feels.
5. we should have usage guidance that tabs shouldn't be given very long names. In case that's out of an app's control (e.g. user-specified names) we could consider following our established pattern of having a reasonable default max-width on each tab but allowing apps to override it. This will probably require other styling changes to behave well.
