### ISSUE TITLE
Add new color token for Soliton Calendar Dark UI Text

### ISSUE THREAD

**Issue by NIbokeefe** [ni/nimble#2351]
# 🧹 Tech Debt

This request is to add a new color token for Dark UI text in the Calendar (work for Soliton team).

Token name: PowerGreen-Text-100
Color: Hex #98F5CA

![Image](https://github.com/user-attachments/assets/917a638c-e53c-49f9-a657-32eaa5ad586c)
![Image](https://github.com/user-attachments/assets/65ed4eb7-89de-4dfd-b981-423d3f4481a5)

**Comment by sandeep-ni** [comment]
The new color token has been added.

Token name: PowerGreenDark50
Color: Hex #98F5CA
