### ISSUE TITLE
Install software icon request

### ISSUE THREAD

**Issue by TJ-G** [ni/nimble#2354]
# 🎨 Icon Request

## 📌 Request Background

Systems application :: Users will click install software button to initiate the new, streamlined software installation flows

## 🧪 Research

I kinda like the simplicity of this one on the noun project:
<img width="220" alt="image" src="https://github.com/user-attachments/assets/a945fd00-df33-4915-b6f9-d16aea1bc9df">

## 🥅 Acceptance Criteria

- [ ] Icon [name](https://github.com/ni/nimble/blob/main/packages/nimble-tokens/CONTRIBUTING.md#icon-naming) approved by PO and owners
- [ ] Icon reviewed by design team
- [ ] Icon available in [Nimble_Iconography](https://www.figma.com/design/aOmrur2iA2Abc6Pp59NVGV/Nimble_Iconography?node-id=0-1&t=KGtldxWuPIvzgHCo-0) (link)
- [ ] Icon published in Nimble Storybook (link)

**Comment by NIbokeefe** [comment]
@TJ-G @jattasNI 

My first instinct is we should be using our standard download icon rather than creating a new one.  What are we trying to convey with a new metaphor?  Especially looking at this inspiration icon, it looks like someone's unique interpretation of the standard download icon and doesn't provide any additional value about specifics of the download through its visual design.  

If we aren't using this in tandem with another option to download differently, what are the thoughts behind needing a new one?

**Comment by NIbokeefe** [comment]
@TJ-G @jattasNI 

Traditionally we've used the icons download and install interchangeably, but I'm happy to update them so they are unique. 

<img width="969" alt="Screenshot 2024-09-03 at 11 00 09 AM" src="https://github.com/user-attachments/assets/f9eea867-128b-4de6-970b-f484960117ef">
<img width="1037" alt="Screenshot 2024-09-03 at 11 00 43 AM" src="https://github.com/user-attachments/assets/2e975343-546a-4a8e-934a-3c438ab49cf0">

Here's an elegant solution that works well with our existing assets.  The subtle difference you'll see as a standard between download and install (when not drawn exactly the same) is install will be a package or abstractly drawn as a box.  

<img width="630" alt="Screenshot 2024-09-03 at 11 36 06 AM" src="https://github.com/user-attachments/assets/3521dbd5-cd75-40f6-8f84-b48eecfdfe0d">

**Comment by NIbokeefe** [comment]
@jattasNI @fredvisser @m-akinc 

Please add these two icons into the token library.

**arrow-down-box_16x16**
Tags:  install, rectangle, arrow, down, drive, package
![arrow-down-box_16x16](https://github.com/user-attachments/assets/f1fb39d8-f581-458d-bf81-b87dfb5a725e)

**arrow-up-box_16x16**
Tags:  uninstall, rectangle, arrow, up, drive, package
![arrow-up-box_16x16](https://github.com/user-attachments/assets/e1b599c7-5a6a-4fc4-9f1d-4290f1d75e17)

**Comment by jattasNI** [comment]
@TJ-G these icons are available in Nimble now
