### ISSUE TITLE
Regression with storybook-addon-pseudo-states v4

### ISSUE THREAD

**Issue by rajsite** [ni/nimble#2371]
# 🧹 Tech Debt

Upgrading to the latest [storybook-addon-pseudo-states](https://github.com/chromaui/storybook-addon-pseudo-states) (v4.0.1 as of writing) seems to fail to render the pseudostates in our stories. We should figure out how to adopt the v4 change or report a bug upstream.

Example diff trying 4.0.1 where all psedostates seem to no longer apply:
![image](https://github.com/user-attachments/assets/edda8440-2c10-445d-9992-405647e6292b)

**Comment by m-akinc** [comment]
Thank goodness this seems to be fixed in version 4.0.2
