### ISSUE TITLE
[select] Selected option text content can get out of sync with displayed selected value

### ISSUE THREAD

**Issue by mollykreis** [ni/nimble#2379]
# 🐛 Bug Report

When the text content of the selected item in the `nimble-select` is updated, the display value in the select isn't updated.

## 💻 Repro or Code Sample

1. Go to the `nimble-select` storybook page: https://nimble.ni.dev/storybook/?path=/docs/components-select--docs
2. In dev tools, update the text of the selected option
3. Notice that the text in the drop-down is updated but the text in the control is not

![image](https://github.com/user-attachments/assets/4b3b2948-ed3c-4ad1-a954-6a2feba9c757)

## 🤔 Expected Behavior

The display value in the `nimble-select` should always mirror the text content of the selected option.

## 😯 Current Behavior

The display value in the `nimble-select` can get out of sync with the text content of the selected option.

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* Version [e.g. 1.8.0]

**Comment by m-akinc** [comment]
If it can't be fixed in a few hours, put it in the backlog
