### ISSUE TITLE
Research/document best approach for handling uppercasing nimble-button text

### ISSUE THREAD

**Issue by msmithNI** [ni/nimble#240]
TL;DR: Sounds like screen readers treat uppercase words as acronyms so ADD is pronounced "A D D". Sounds like we might need to use aria-label to address it correctly

[See discussion from pull request here for more info](https://dev.azure.com/ni/DevCentral/_git/Skyline/pullrequest/242899?_a=files&path=/Web/Workspaces/SystemLinkShared/projects/systemlink-lib-angular/src/components/sl-slide-out/sl-slide-out.component.html&iteration=3&discussionId=2602002)

Important info copied below:

>Was curious how this impacts accessibility and found this article: https://blog.benmyers.dev/css-can-influence-screenreaders/ 

>Sounds like screen readers treat uppercase words as acronyms so ADD is pronounced "A D D". I thought that using CSS text-transform instead might prevent that but it does not seem to be the case based on the article.

>Sounds like we might need to use aria-label to address it correctly: https://www.essentialaccessibility.com/blog/css-and-accessibility 

>Can you create an issue in nimble so we can consider how this case should be addressed broadly (guessing by documentation ultimately)?

>I also think adding an aria-label here with the unmodified text would be nice but wouldn't block if it's decided to skip until we decide a common pattern (which I wouldn't be surprised if we just have guidelines saying to add an aria-label eventually).

**Comment by nate-ni** [comment]
Follow-up on Jan 05, 2023

Maybe things have changed but uppercasing words seems to be fine in screen readers.

All of these were read as "Add". Never was it read as "A.D.D"
```html
<p>ADD</p>
<p aria-label="Name">ADD</p>
<p style="text-transform: uppercase;">Add</p>
<p style="text-transform: uppercase;" aria-label="Add">Add</p>
```
    
 Tried it on macOS with VoiceOver in Chrome

Also works with NVDA on Windows 

It doesn't alway work as expected, or consistently when mixing case though.

Example from macOS VoiceOver:
ADD TWO NUMBERS -> "Add two numbers"
ADD two numbers -> "A.D.D. two numbers"
HELLO THERE -> "Hello there"
HELLO there -> "Hello there"

All of these work correctly if you use aria-label
