### ISSUE TITLE
Request to add icons to Token Library for Client Teams (8 icons)

### ISSUE THREAD

**Issue by NIbokeefe** [ni/nimble#2466]
# 🧹 Tech Debt

@m-akinc @jattasNI @fredvisser 

**High Priority (ASAP)** for task https://dev.azure.com/ni/DevCentral/_workitems/edit/2905095?src=WorkItemMention&src-action=artifact_link

star-8-point_16x16
Tags: create new, burst
![Image](https://github.com/user-attachments/assets/796e058e-ac97-4a59-8955-f3dde4d096c1)

rectangle-lines_16x16
Tags: defined, paper, paragraph, sentence, words
![Image](https://github.com/user-attachments/assets/0b9f626e-3f51-4812-a0a2-b361863ab223)

-------------------------------------------------------------------------------------------------------------

**Additional icons (not high priority):** for AI work

lightbulb_16x16
Tag: suggested, prompt, idea, think
![Image](https://github.com/user-attachments/assets/54ceb3f4-1f75-4a14-9a4f-3fb5b316c6bd)

microphone16x16
Tag: talk to text, speech, speak, sound
![Image](https://github.com/user-attachments/assets/744a5cac-637b-4f1a-8264-077e124b1b1f)

mountain-sun_16x16
Tag: image, browse
![Image](https://github.com/user-attachments/assets/86fa485a-3fd1-4699-9cd8-aa7511353a19)

paper-airplane_16x16
Tag: send, relay, submit
![Image](https://github.com/user-attachments/assets/81548b1a-e33c-4708-98c2-5162074b0ded)

paperclip_16x16
Tag: attachment, add document, browse
![Image](https://github.com/user-attachments/assets/9b960f14-ebe6-4af0-9a36-2822a4a66db4)

-------------------------------------------------------------------------------------------------------------

**Update Existing token:**  replaces the existing icon design for Edit/Pencil 

pencil_16x16
![Image](https://github.com/user-attachments/assets/a31bc607-e849-4a29-8ffe-0dce73d9ae0d)

**Update Existing token:** replaces the existing icon design
floppy-disk-pencil_16x16
![Image](https://github.com/user-attachments/assets/5121ba5d-9ddd-4f40-b9ba-c83abfdc7dd7)

**Comment by jattasNI** [comment]
@NIbokeefe these icons will be available in a few minutes once the latest build finishes. Heads up that I renamed `paper-airplane` to be `paper-plane` to match FontAwesome more closely. Also we had an existing icon called `floppy-disk-pen` but not `floppy-disk-pencil`. I kept the original name to avoid breaking existing clients even though it doesn't align with the existing `pencil` icon.
