### ISSUE TITLE
Add example and documentation of importing and consuming an icon

### ISSUE THREAD

**Issue by m-akinc** [ni/nimble#287]
## 📌 User Story
When Christine tried to use some nimble icons in the TestInsights app, she had to do some reverse engineering to figure out the pattern to import and consume an icon. We should have prominent usage docs to make this easier.

It should include:
- the path to import from
- the HTML to show an icon

**Comment by rajsite** [comment]
The test insight challenges, now duplicated in [at least one other app](https://dev.azure.com/ni/DevCentral/_search?action=contents&text=status-icon.pipe%20%20NOT%20ext%3Axlf&type=code&lp=code-Project&filters=ProjectFilters%7BDevCentral%7DRepositoryFilters%7BSkyline%7D&pageSize=25&result=DefaultCollection/DevCentral/Skyline/GBmaster//Web/Workspaces/ExecutionManager/src/app/pipes/status-icon.pipe.ts), all seem related to trying to treat icons as a pipe to use in the jqx grid (as raw HTML strings).

This use-case should be superseded by the nimble-table support of icon columns. I think this can stay as tribal knowledge until the need is replaced with the nimble-table.

Also when the icons were first integrated in test insights I believe that was before we were generating Angular directives for the nimble icons. Now integration of icons aligns with all other components and I don't think there are icon-specific concerns.

Closing as won't fix.
