### ISSUE TITLE
Establish process for upgrading dependencies

### ISSUE THREAD

**Issue by m-akinc** [ni/nimble#291]
## 😯 Problem to Solve

Going long periods of time without updating dependencies can make the eventual update more difficult, and also leads to missing out on improvements and bug fixes.

## 💁 Proposed Solution

We should establish a process to make sure the NPM dependencies of the nimble repo stay up to date.

During the July innovation week we investigated dependabot, but it had [some issues](https://teams.microsoft.com/l/message/19:c156be2f1ddd480fa9e72105f14d30e7@thread.tacv2/1625162683530?tenantId=87ba1f9a-44cd-43a6-b008-6fdb45a5204e&groupId=9ee065d7-3898-4245-82f6-76e86084b8b1&parentMessageId=1625162683530&teamName=Web%20Design%20System&channelName=Design%20System%20Innovation%20Week%20-%20Summer%202021&createdTime=1625162683530) (copied below in comment). We could either resolve these issues, look into other tools, or document a manual process to update dependencies on a regular cadence.

## Acceptance Criteria
1. Dependencies are updated to latest at least once per quarter. If done in an automated way, it should not require too much burdensome manual intervention.
1. Client apps are not forced to upgrade their Angular or TypeScript version for every minor version bump
1. If there are any remaining security vulnerabilities identified by dependabot or "npm audit", the team agrees that they are not legitimate vulnerabilities
1. If the approach chosen is not dependabot, the dependabot tooling from innovation days is deleted

## Related PRs
- [ ] #826 
- [ ] #957

```[tasklist]
### Tasks
```

**Comment by jattasNI** [comment]
I enabled Renovate in #826. I'll mark this as closed: any follow up work that's revealed when we start seeing Renovate PRs can be tracked with new issues.
