### ISSUE TITLE
Update background colors in Storybook

### ISSUE THREAD

**Issue by m-akinc** [ni/nimble#322]
From Brandon O'Keefe:

There was a question about what colors should we add or have in storybook for backgrounds.  Final decisions on this are still being looked at in contextual scenarios and is requiring consideration for alignment between multiple products. 

I plan to have more guidance in the Nimble design spec eventually.

For now variations would be:

**Light UI**
Background: White | Black7
Header: Black15 | Black30

**Dark UI**
Background: Black85 | Black88 | 
Header: Black80 | Black85 | Black 91

**Comment by fredvisser** [comment]
Done - a while back
