### ISSUE TITLE
Validate password reveal styling

### ISSUE THREAD

**Issue by rajsite** [ni/nimble#331]
## 🧹 Tech Debt

We currently have a specific workaround for styling the password reveal icon in Edge.
From a PR discussion it sounds like there might also be one in Safari.
There also might be a clear password icon for fields in Edge.
We should check if we need to handle those things (didn't attempt to confirm they exist).

discussion: https://github.com/ni/nimble/pull/316#discussion_r795972273

**Comment by mollykreis** [comment]
I've performed the following validation and come to the conclusion that there is no work to be done for this issue at this time:
- Verified that the reveal password button looks correct in Edge for all three themes
- Verified that there is not a clear password button on Edge that needs to be styled
- Verified that there is nothing to be styled on Chrome
- Verified that there is nothing to be done for Safari (verified in webkit and Safari for iOS)
