### ISSUE TITLE
Create Nimble Filterable select with Multi-select

### ISSUE THREAD

**Issue by vikisekarNI** [ni/nimble#341]
## 😯 Problem to Solve

To search dropdown list items and select them with checkboxes. This comes from one of HLD requirement's in  #Argon [here](https://ni.visualstudio.com/DevCentral/_git/srd-semi-ses-software/pullrequest/262099)

![image](https://user-images.githubusercontent.com/94439533/153156166-71b45e82-510a-4fab-a9c8-340b726d410d.png)
![image](https://user-images.githubusercontent.com/94439533/153156549-ed90a040-3e81-4be6-8f4a-75d3717ba0f1.png)

## 💁 Proposed Solution

Create a combo box which will search for dropdown list items and then select the desired item. This feature is inspired from [Material library's Autocomplete](https://material.angular.io/components/autocomplete/overview).

[Example ](https://stackblitz.com/edit/angular-mat-multiselect-with-autocomplete) for Material Autocomplete with Multi-select added for reference

**Comment by fredvisser** [comment]
Closing in favor of https://github.com/ni/nimble/issues/1214
