### ISSUE TITLE
Placeholder for nimble-select when nothing is selected

### ISSUE THREAD

**Issue by gokulakrishnan-ni** [ni/nimble#350]
## 😯 Problem to Solve

Currently, the nimble dropdown displays the first item in the list as the default selection but the corresponding form control value doesn't reflect the displayed value.

## 💁 Proposed Solution

By default, if the form control value
1. doesn't match any of the values in the dropdown list, the dropdown shall display a placeholder which is passed as a property value
2. matches any of the value in the list, the corresponding item shall be displayed as the selected value

**Comment by jattasNI** [comment]
Note that Blazor support is tracked separately #1952 so I think we can close this once we're satisfied with the web component and Angular integration.

**Comment by fredvisser** [comment]
Looks great in Storybook and example Angular app!
