### ISSUE TITLE
Nimble Dropdown List needs to be dismissed on window resize

### ISSUE THREAD

**Issue by gokulakrishnan-ni** [ni/nimble#355]
# 🐛 Bug Report

When nimble dropdown list is toggled and the window is resized to be smaller, the dropdown list overflows the page causing display of scrollbar

## 🤔 Expected Behavior

The nimble dropdown list should be dismissed on window resize

## 😯 Current Behavior

The nimble dropdown list is not dismissed on window resize and it causes overflow displaying the page scrollbar

![image](https://user-images.githubusercontent.com/95460469/154058459-1356d731-67e3-4377-bd58-456685fc63b1.png)

## 💁 Possible Solution

The nimble dropdown should be dismissed on window resize

**Comment by m-akinc** [comment]
The FAST issue was fixed in a way that won't be cherry-picked into the legacy branch we use. We will likely have to live with this behavior until we upgrade to FAST 2.0.

**Comment by fredvisser** [comment]
This should be fixed in FAST 2.0, but we won't prioritize fixing this in the current stack. Closing as low ROI.
