### ISSUE TITLE
Consider using an npm task orchestrator to improve build time

### ISSUE THREAD

**Issue by rajsite** [ni/nimble#376]
## 🧹 Tech Debt

Currently we rely on an [ordered list of packages](https://github.com/ni/nimble/blob/f6774275bf53b4a225c5b6cf61b3690f655a9aa4/package.json#L33) and the monolithic build run sequentially first running all build sequentially, then test sequentially, then lint sequentially, etc. [Microsoft Lage](https://microsoft.github.io/lage/guide/) can help track dependencies to make, ie build and test run in parallel.

It can also support caching actions which could enable fast monolithic rebuilds (where currently we rely on manual individual package rebuilds during dev).

Created the tech debt as I had alluded to it in https://github.com/ni/stratus/pull/2#discussion_r812501381

**Comment by rajsite** [comment]
> Google wireit is a similar tool https://github.com/google/wireit

Write-it had improved a lot and I think warrants some investigation. Particularly for concerns of build times mentioned in #827

**Comment by jattasNI** [comment]
Moved from "Closed as complete" to "Closed as not planned" purely to capture its current state more accurately. I have no objection to reviving this if build time becomes something we want to focus on.
