### ISSUE TITLE
Labels should ellipsize when control width exceeded

### ISSUE THREAD

**Issue by m-akinc** [ni/nimble#395]
## 😯 Problem to Solve

If a control label would go beyond the width of the component, it should _not_ wrap, be clipped, or just extend beyond the component bounds. It should truncate with an ellipsis, and on hover, the full text should be shown in a tooltip.

## 💁 Proposed Solution

Identify components that have the wrong behavior and fix as many as possible. In general, setting these CSS properties will result in the desired behavior:
```
display: block;
overflow: hidden;
text-overflow: ellipsis;
white-space: nowrap;
```
Currently we don't have a nimble tooltip, but ideally we would use that to display the full text on hover.

**Comment by fredvisser** [comment]
Closing in favor of #312
