### ISSUE TITLE
Improve build times for docs only changes

### ISSUE THREAD

**Issue by rajsite** [ni/nimble#401]
## 🧹 Tech Debt

Changes that are just to docs shouldn't need to run the full build because they do not impact package contents.

For example:
/README.md
/CONTRIBUTING.md
/packages/nimble-*/docs/**

However, some docs **are** part of packages and when updated need to do a full build and be released in a package version so they appear on npm.org, nuget.org etc:

For example:
/packages/nimble-*/README.md
/packages/nimble-*/CONTRIBUTING.md

We can update the main workflow (not publishing) using the paths-ignore flag to make these changes: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-excluding-paths

**Comment by m-akinc** [comment]
We decided that it's more important to keep running prettier on our docs than to try to speed up submissions. Closing this issue.
