### ISSUE TITLE
Visually hide unstyled or undocumented slots

### ISSUE THREAD

**Issue by rajsite** [ni/nimble#451]
## 🧹 Tech Debt

We don't style all the slots that are available in our controls from the fast-foundation templates. For example many controls use the start slots for icon placement but not the end slots.

Ideally we would not expose slots we do not use but that currently requires forking the templates and is not a maintenance burden we currently want to take on for all controls (only as a last resort). FAST is also [not currently planning](https://discord.com/channels/449251231706251264/482296787021856768/951561369034039299) on making that kind of configuration directly available.

For now we should make sure to style our unused slots with display:none and make sure our supported slots and use-cases are documented. This issue should specifically address that unused slots are marked dispaly:none.

**Comment by m-akinc** [comment]
We should hide the `start` slot of the `nimble-tabs` and `nimble-anchor-tabs` controls, but we must leave the `end` slot, because the `nimble-tabs-toolbar` targets that slot.
