### ISSUE TITLE
Attempt to remove unnecessary CA/SA suppressions in Blazor projects

### ISSUE THREAD

**Issue by atmgrifter00** [ni/nimble#481]
## 🧹 Tech Debt
 We've introduced a number of CA/SA suppressions particularly in the Blazor example projects. Locally, I was able to remove the majority of them and successfully build in Release, so it's unclear why they're there at the moment. We should wait until the CI/CD pipeline is established for the Blazor projects, and then attempt to remove them.

**Comment by jattasNI** [comment]
There don't seem to be many instances of suppressions anymore (assuming [searching for "pragma"](https://github.com/search?q=repo%3Ani%2Fnimble%20%23pragma&type=code) is how to find them. Closing as low ROI. @atmgrifter00 @msmithNI tagging you as FYI.
