### ISSUE TITLE
Add invalid styling to more components

### ISSUE THREAD

**Issue by mollykreis** [ni/nimble#486]
## 😯 Problem to Solve

It would be nice if more components had build-in invalid state styling so that the invalid states of components is consistent across apps. For example, Soliton is creating an invalid state style for the select in this PR: https://ni.visualstudio.com/DevCentral/_git/srd-semi-ses-software/pullrequest/288182?_a=files

## 💁 Proposed Solution

Evaluate the components and determine which ones should have invalid states associated with them.

**Comment by m-akinc** [comment]
The numeric and select have already had the invalid styling implemented. That leaves the text area ("comment field") as the last component that still needs invalid styling, and that is implemented in #1119
