### ISSUE TITLE
Clean-up Flex layout align configuration

### ISSUE THREAD

**Issue by rajsite** [ni/nimble#503]
## 🧹 Tech Debt

We had found icons and controls were not aligning property. One workaround was to add the vertical-align: middle property on the button as show here: https://github.com/ni/nimble/blob/47839b3c67586cb98051a2639d9ba2cb6d21b5a4/packages/nimble-components/src/patterns/button/styles.ts#L37

In the FAST issue they found an alternate pattern that just changes flex settings: https://github.com/microsoft/fast/issues/5414#issuecomment-1100791752

We should verify that configuration works and propagate it to our controls where it makes sense. We should also add tests focused on validating inline behavior of the controls (ie inline with text and inline-block images, etc).

**Comment by m-akinc** [comment]
FAST's approach results in alignment that is inconsistent with native `button` elements.

FAST's approach (updated stackblitz to latest FAST packages):
![image](https://github.com/ni/nimble/assets/7282195/6fe399d7-da13-495b-b829-2c9f408ec257)

Nimble's current approach (setting `vertical-align: center` on host):
![image](https://github.com/ni/nimble/assets/7282195/e9b5ea63-8e57-40d1-8f5c-d61a3e1d1c2c)

Native button element:
![image](https://github.com/ni/nimble/assets/7282195/58aa5a66-bb29-47db-abb3-aad14ec0081e)

I tried modifying FAST's approach by setting the inner, native button's `align-items` to something other than `baseline`, but that results in misaligned buttons (i.e. the original problem):
![image](https://github.com/ni/nimble/assets/7282195/7bc595c0-740a-4896-8331-3c8e9682473b)

My conclusion is that we should keep our current approach. I will still create a new Chromatic test for button alignment, though.
