### ISSUE TITLE
Add dynamic option in dropdown of combobox

### ISSUE THREAD

**Issue by atmgrifter00** [ni/nimble#507]
## 📌 Support dynamic dropdown option in combobox

As discussed in the [spec](https://github.com/ni/nimble/blob/main/packages/nimble-components/src/combobox/combobox.spec.md), there is a desire for the combobox to have a typed value in the input field, that doesn't match any current option, as a special dropdown option to select itself (see the [design spec](https://xd.adobe.com/view/33ffad4a-eb2c-4241-b8c5-ebfff1faf6f6-66ac/screen/bd6755d9-8fd2-4b97-9709-939ea20680ae/specs/)).

This user story is meant to track the work for adding that option.

The summary for that work should be:
- A new property that places the combobox in a mode to present the custom value to the user in the dropdown
- Add new slots to the combobox for a user to place the text and the icon for the custom dropdown option.
- While in the new mode, if a user clicks away from the combobox while entering an option not present in the current set of options (so current value is presented as the custom option in the dropdown), the text is reverted to what was there before, and no new value is committed.
- If a user clicks on the dynamic option in the dropdown, or presses `<Enter>`, the new value is committed, and that option is now a permanent option in the dropdown.

**Comment by rajsite** [comment]
- I wonder if this should be for both combobox and filterable select. ie in either of those controls typing text shows that as an option in the list of `Add "my text"` and clicking it just fires an event to the app. The app can then make that option and add it to the control and mark it selected. Making the app do it seems reasonable as the app needs to decide what the "value" representation of that option is. It's not something we can guess.
- How would this kind of feature interact with grouped options? i.e. could you choose what group to add it to as well? Maybe a default group must be defined?
- I'm curious what the use-case is for this concept. This is kind of the idea of an "editable" select / combobox. Should you be able to add / remove / edit entries in the options list? Maybe this is more of a use-case for a picker?

**Comment by fredvisser** [comment]
Closing as low ROI

**Comment by rajsite** [comment]
For future readers this issue closed as low ROI covers users being able to add options interactively to the select / combobox list. It does not cover the dynamic options feature (filter mode manual) that was added to select. That should still be added to combobox
