### ISSUE TITLE
Clean-up storybook contributing documentation

### ISSUE THREAD

**Issue by rajsite** [ni/nimble#512]
## 🧹 Tech Debt

The dev docs for storybook could use some updating after https://github.com/ni/nimble/pull/502

Topics to add:
- General overview and best practices (use FAST templates, source code formatting)
- Matrix documentation and examples
- Discussion of story types (user docs vs tests)

**Comment by jattasNI** [comment]
Closing this as low ROI since most new stories are created by copy-pasting an existing story and we haven't seen issues recently with new stories violating our practices.
