### ISSUE TITLE
Investigate codegen for Nimble enum values for Blazor

### ISSUE THREAD

**Issue by msmithNI** [ni/nimble#565]
## 🧹 Tech Debt

Currently for Nimble Blazor, we are creating (by hand) C# files with enums corresponding to those in nimble-components (like ButtonAppearance).
This is different from nimble-angular (which can just reuse the enums exported by nimble-components as-is).

This is problematic for a couple of reasons:
- Nothing automatically verifying that the enum values of nimble-components match up with kebab casing the C# enum values
- Blazor enums can fall out-of-date with the nimble-components enum. For example, when we added the Frameless appearance mode to the text control, nothing automatically flagged that as missing for Blazor (optimally it would have updated automatically)

See PR discussion: https://github.com/ni/nimble/pull/561#discussion_r873866416

**Comment by msmithNI** [comment]
Looked into this a bit on an Innovation Day.

Prototype: [users/masmith/codegen-blazor-enums](https://github.com/ni/nimble/compare/users/masmith/codegen-blazor-enums) https://github.com/ni/nimble/commit/7ef9eb9950918af6ab05595d01bada439b78548d

Main issue was enums that we're re-exporting from FAST are not currently supported (they're commented out in the generate enums index.js) - if they're re-enabled, Rollup pulls in too much FAST code, including some that references `document`, and that breaks the build script. Tried a few Rollup options to mark FAST with like [external](https://rollupjs.org/configuration-options/#external) and [output.globals](https://rollupjs.org/configuration-options/#output-globals) but couldn't get everything working with those.
In the demo @rajsite suggested that we might be able to generate from type definitions instead to not run into that problem.

**Comment by jattasNI** [comment]
This seems low ROI. We haven't seen many issue with enums getting out of sync and it's very easy to fix when we do discover problems.
