### ISSUE TITLE
Research FastElement 2.0

### ISSUE THREAD

**Issue by mollykreis** [ni/nimble#572]
## 🧹 Tech Debt
We should updated to FastElement 2.0 so that we can use some new features from FAST.

Features we should leverage when we move to FastElement 2.0:
- Advanced event binding to specify things such as _capture: true_ as is done in the nimble-menu-button.
    - FAST comment: https://github.com/microsoft/fast/issues/4531#issuecomment-963323586
    - nimble change that could leverage this feature: https://github.com/ni/nimble/pull/569
- Better typing of `c.parent` in bindings
    - See discussion from nimble PR: https://github.com/ni/nimble/pull/1056#discussion_r1107806254
    - See FAST change that improved typing: https://github.com/microsoft/fast/pull/6397

**Comment by rajsite** [comment]
When switching to FE2 we should update our exported button type:
https://github.com/ni/nimble/blob/f3f0e75635bae19ca3b751b69d0479387cba5bab/packages/nimble-components/src/button/types.ts#L9

To export the newly added actual [foundation ButtonType](https://github.com/microsoft/fast/blob/a42ff75a9130a5ce13006c272c2e2bbbaffdbb41/packages/web-components/fast-foundation/src/button/button.options.ts#L6).

**Comment by jattasNI** [comment]
In #1134 we added an import in `nimble-components/src/menu/index.ts` of the anchored region component so that FAST's implementation could find Nimble's anchored region when using `tagFor`. Both `tagFor` and anchored region have seen big changes in FAST vNext, so this workaround should be revisited and possibly removed.

**Comment by m-akinc** [comment]
We should look at replacing the boolean converter we use in the date-text table column with the FAST `nullableBooleanConverter`.

**Comment by jattasNI** [comment]
Given the slow progress on FastElement 2.0 it doesn't seem worthwhile to proactively track potential issues. Closing as low ROI for now, we can re-open if it comes closer to release.
