### ISSUE TITLE
Visual Design Update Request for Breadcrumbs

### ISSUE THREAD

**Issue by NIbokeefe** [ni/nimble#591]
Updates were made to the styling of breadcrumbs.  Please see the breadcrumbs on the Nimble Design Document.  I made updates to the naming of the breadcrumb components.

The request is to add an additional version:
Breadcrumb_Primary_Single_32

This is a variant of Breadcrumb_Quiet_Single_32, where the current (last) bread crumb is colored green, and all leading (previously visited) breadcrumbs are not green.

https://xd.adobe.com/view/33ffad4a-eb2c-4241-b8c5-ebfff1faf6f6-66ac/screen/7b53bb3e-439b-4f13-9d5f-55adc7da8a2e

**Comment by fredvisser** [comment]
Fixed by #2193
