### ISSUE TITLE
Integrate build pipeline with JFrog Build-Info

### ISSUE THREAD

**Issue by fredvisser** [ni/nimble#603]
## 🧹 Tech Debt

We should define and document a process for integrating with the [JFrog CLI](https://www.jfrog.com/confluence/display/CLI/JFrog+CLI) and create a **Build** in Artifactory that includes the NPM packages used to build the package. 

We can use this Build to define a security and license violation policy, and use Artifactory to manage the approval and exception process. We can also use it to manage all the third-party licenses used within our Angular apps.

References: https://github.com/marketplace/actions/setup-jfrog-cli

This might allow us to remove `npm audit` from our pipeline.

We should investigate whether this can replace/augment Dependabot workflows for tracking out-of-date deps.

**Comment by rajsite** [comment]
The current direction is that nimble as a public package would be managed in the public npm registry and we use renovate for dependency updates. So maybe this can be closed @fredvisser ?

**Comment by jattasNI** [comment]
Closing as low ROI. We can revive if it becomes a priority.
