### ISSUE TITLE
Number field inc/dec disappear when disabled

### ISSUE THREAD

**Issue by m-akinc** [ni/nimble#616]
# 🐛 Bug Report

According to the design spec, when the nimble-number-field is disabled, the inc/dec controls should still be visible but dimmed. 
![image](https://user-images.githubusercontent.com/7282195/175130410-9a0f6d3d-b76f-4ddf-80fe-977873e2c419.png)
Currently, they disappear.

## 💻 Repro or Code Sample

Disable the Number field in Storybook.

## 🤔 Expected Behavior

Inc/dec plus-minus buttons should be visible but disabled.

## 😯 Current Behavior

Inc/dec plus-minus buttons disappear.

## 💁 Possible Solution

This is difficult, because it is the FAST foundation template that is removing the inc/dec buttons when the disabled is set:
https://github.com/microsoft/fast/blob/eec60d5d7a59371d2429cbd7147f2671f35d705c/packages/web-components/fast-foundation/src/number-field/number-field.template.ts#L72

## 🔦 Context

N/A

## 🌍 Your Environment

N/A

**Comment by nate-ni** [comment]
Since the current implementation is deemed workable, I'm moving this work from a Bug to an Enhancement.

Tracking in:
- #981
