### ISSUE TITLE
Improve CONTRIBUTING docs on component API design

### ISSUE THREAD

**Issue by jattasNI** [ni/nimble#627]
## 🧹 Tech Debt

We should have better guidance about when to use a class / attribute / property to specify parts of a component API. This came up in a discussion about tooltip states. Should error/info/warning and the visibility of icons be one class? Separate classes? Attributes?

We should write down our guidance (current direction: prefer classes for style-only appearances) and evaluate if there are existing APIs that we want to revisit to ensure they're consistent with the guidance

@rajsite volunteered to take a stab at a PR for this

**Comment by rajsite** [comment]
These docs have been updated with the classes to attributes transition and is captured in:

https://github.com/ni/nimble/blob/8658ad8d97cb3e47494d9d89f797a620074d7ef9/packages/nimble-components/CONTRIBUTING.md#represent-control-states-as-attributes
