### ISSUE TITLE
Improve nimble-dialog handling of detached state

### ISSUE THREAD

**Issue by m-akinc** [ni/nimble#677]
## 🧹 Tech Debt

From discussion here: https://github.com/ni/nimble/pull/658#discussion_r942539836

The Nimble dialog needs logic to handle:

- disconnecting while the dialog is open (this should leave the dialog in a consistent state)
- calling show() while disconnected
- calling close() while disconnected?

You should be able to disconnect (while the dialog is open), reconnect, and re-open the dialog.

Any new scenarios handled need tests as well.

**Comment by jattasNI** [comment]
Closing in favor of #1769
