### ISSUE TITLE
Tokens for Drop Shadows

### ISSUE THREAD

**Issue by NIbokeefe** [ni/nimble#696]
There are 3 drop shadows right now that require different settings.

Top level: Application intensity - Dialogs, pop-ups, overlays

Mid level: Control intensity - Menus, banners, text scrolling, etc.

Low level: Control states - Rollover, Drag

**Comment by nate-ni** [comment]
Tokens added to XD document at: https://xd.adobe.com/view/33ffad4a-eb2c-4241-b8c5-ebfff1faf6f6-66ac/screen/e31b6fca-c37d-40d1-b3dc-9964311cb0c9
