### ISSUE TITLE
Color Theme for Table Design

### ISSUE THREAD

**Issue by NIbokeefe** [ni/nimble#698]

**Comment by NIbokeefe** [comment]
I have provided a color theme to accommodate both light and dark UI themes for tables.  At this time there is no need for additional UI theme colors such as the "color theme."  

There is an effort for both Visual Design and Development to improve the table component.  During this iteration, there may be future updates and changes to the theme colors of tables.

**Comment by nate-ni** [comment]
Will be addressed in #716
