### ISSUE TITLE
Intermittent build failures with TS 4.6.4

### ISSUE THREAD

**Issue by TrevorKarjanis** [ni/nimble#709]
# 🐛 Bug Report

The nimble-components and nimble-angular builds fail intermittently with TS 4.6.4.

## 💻 Repro or Code Sample

1. Pull the [angular-14](https://github.com/ni/nimble/tree/angular-14) branch.
2. Run `npm install`.
3. Run `npm install --no-save typescript@4.6.4`.
4. Run `npm run build`.

## 🤔 Expected Behavior

The build should pass.

## 😯 Current Behavior

@microsoft/fast-foundation fails the library checks ([example](https://github.com/ni/nimble/runs/8143047926?check_suite_focus=true))
```bash
Error: ../../node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts(2252,66): error TS2344: Type 'T' does not satisfy the constraint 'string | number | boolean | symbol | any[] | Uint8Array | ({ createCSS?(): string; } & Record<PropertyKey, any>) | null'.
  Type 'T' is not assignable to type '{ createCSS?(): string; } & Record<PropertyKey, any>'.
    Type 'T' is not assignable to type '{ createCSS?(): string; }'.
Error: ../../node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts(2254,186): error TS2344: Type 'T' does not satisfy the constraint 'string | number | boolean | symbol | any[] | Uint8Array | ({ createCSS?(): string; } & Record<PropertyKey, any>) | null'.
  Type 'T' is not assignable to type '{ createCSS?(): string; } & Record<PropertyKey, any>'.
    Type 'T' is not assignable to type '{ createCSS?(): string; }'.
Error: ../../node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts(2256,121): error TS2344: Type 'T' does not satisfy the constraint 'string | number | boolean | symbol | {} | any[] | Uint8Array | null'.
```

## 💁 Possible Solution

Pin the version declared by @microsoft/fast-foundation, 4.6.2 ([example](https://github.com/ni/nimble/runs/8144256119?check_suite_focus=true)).

## 🔦 Context

Upgrading Angular and ESLint upgrades TS.

## 🌍 Your Environment

* OS & Device: Windows
* Version: nimble-angular@8.4.7

**Comment by TrevorKarjanis** [comment]
This is also fast-foundaton issue [6365](https://github.com/microsoft/fast/issues/6365).

**Comment by rajsite** [comment]
With the #1000 update all of our packages (except one build tool) are resolving to TS 4.6.4 and the version in the root was removed. I have not seen intermittent build failures since the Angular 14 upgrade or issues regenerating the lockfile.

So as described I think this bug is resolved. We do need to still get TS 4.8.4 working and I'll repurpose #810 for that
