### ISSUE TITLE
[Blazor] Nimble dropdowns have noticeable update lag when scrolling.

### ISSUE THREAD

**Issue by atmgrifter00** [ni/nimble#710]
# 🐛 Bug Report

We noticed recently that there were some distinctions in performance of the `NimbleCombobox` (and `NimbleSelect`) when using them in a vanilla HTML environment versus from within a Blazor app.

Vanilla HTML:

![NimbleDropdownNative](https://user-images.githubusercontent.com/26874831/188197925-1f36679a-08b5-4d81-98e4-59d58777841c.gif)

Blazor Server:

![NimbleDropdownBlazor](https://user-images.githubusercontent.com/26874831/188197962-fddad01f-cfcf-467f-94f4-d838beb0982e.gif)

## 🤔 Expected Behavior

That there be not a noticeable difference in operation of dropdowns between a vanilla HTML environment and Blazor.

## 😯 Current Behavior

Dropdowns in Blazor have a noticeable lag in updating while being scrolled with thousands of elements.

## 💁 Possible Solution

Ultimately, we will likely file an issue to ASP.NET Core on this problem. The Nimble issue is here to track the need to file them an issue that will likely include creating examples that they can use to see the issue in a real environment.

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* Version [e.g. 1.8.0]

**Comment by atmgrifter00** [comment]
Ultimately, I'm not sure there are viable options for us to address this without diverging in our API/implementation from the FAST Select/Combobox. Ideally, we would be able to virtualize the set of options being displayed in the dropdown. However, the FAST implementation relies on the full set of options being present when [determining its `selectedIndex` setting](https://github.com/microsoft/fast/blob/f8dde59eee21a1152263447d22a76593ee5ed9e5/packages/web-components/fast-foundation/src/combobox/combobox.ts#L214) (amongst other things).

One option may be to upstream a change to FAST to attempt to virtualize the options in their template, potentially even using something like TanStack Virtual to do it. I even brought this up with FAST in a [Discord thread](https://discord.com/channels/449251231706251264/482296787021856768/1016730260928213123), but haven't seen much movement on it since then.

**Comment by jattasNI** [comment]
Let's drive a decision on this at our meeting today. I'd rather not leave the bug open but in a difficult-to-pick-up state. We should either:
1. file appropriate upstream bugs and mark this blocked
2. close it as not planned
3. decide that we want to make the (expensive) fix in our repo. This might mean converting the bug to an enhancement.

**Comment by fredvisser** [comment]
@atmgrifter00 - Curious if the filterable select also has this issue? Thinking of closing this as low ROI…

**Comment by atmgrifter00** [comment]
> @atmgrifter00 - Curious if the filterable select also has this issue? Thinking of closing this as low ROI…

This is almost certainly low ROI, as if a user is populating either a Combobox or Select with thousands of items it should be expected that the user will filter before scrolling through the list (and if they don't filter that's either a configuration problem or a user problem).
