### ISSUE TITLE
Design spacing tokens for Nimble

### ISSUE THREAD

**Issue by nate-ni** [ni/nimble#718]
This issue is specific to the Design needed. The overarching work and definition can be found at:
- #959 

## Needs specific to design are:
- [ ] Provide scale of context agnostic spacing tokens
- [ ] Provide recommendation for mapping existing spacing uses to token values, providing context specific token names, where needed.

**Comment by NIbokeefe** [comment]
https://nio365.sharepoint.com/:f:/r/sites/SystemLinkDesignSystem/Shared%20Documents/[General](https://nio365.sharepoint.com/:f:/r/sites/SystemLinkDesignSystem/Shared%20Documents/General?csf=1&web=1&e=eKhkto)?csf=1&web=1&e=eKhkto

Use the development link at the top left of this page.

Navigate to Tokens > Spacing
<img width="136" alt="Screen Shot 2023-02-03 at 11 12 37 AM" src="https://user-images.githubusercontent.com/106594349/216688865-b3cf00fa-2f4c-4b5a-884c-d6e029f5ffb9.png">


I've included spacing sizes that we currently use and will likely need in the near future.  I imagine this list will continue to grow as we have more context and we may need to wedge sizes in between these existing ones.

I provided a starting point and idea for how to name the tokens, but this is completely open to the teams decision.

This is not contextual guidance for how to use the spacing or to change current spacing.  This is a document to organize spacing options and start replacing existing spacing with token values.
