### ISSUE TITLE
Number field and table column should support types other than double

### ISSUE THREAD

**Issue by atmgrifter00** [ni/nimble#721]
## 😯 Problem to Solve

Nimble components that display numeric values (e.g. numeric text box and soon numeric text table column) currently only accept double precision floating point values. This means they don't accept types that NI has sometimes supported in the past like:
1. complex numbers
2. big integers (I64 / U64 / arbitrary precision)
3. fixed point numbers
4. high precision time stamps

Complex numbers, for example, should be able to be presented to a user with the `nimble-number-field` component, and have appropriate/expected interactions with the displayed value (e.g. pressing inc/dec buttons modify real value, and not the imaginary part).

Some noted concerns/issues to address:
- Types we know we may need to support now or need more feedback on. ie Integer vs float sure but does it being Int32 actually matter? Maybe it's just IEEE754 double vs [bigint](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt). Should we support IEEE754 double values, ie -Inf, +inf, -0, +0, NaN
- Maybe have a link to the input type blazor tagHelper which is solving a similar kind of issue in a way, ie what is the blazor-y way to say how an attribute should be configured on an element that has a corresponding type change for the value of the element (using the tag helper is the blazor-y way to say the value of `<input type="email">` is string vs `<input type="number">` is number). If anything it's a interesting reference.

## 💁 Proposed Solution

We could consider documenting this limitation in Storybook. (Or perhaps this issue serves as sufficient documentation).

I don't propose we try to solve this issue until we have concrete use cases. But this issue is a good place to collect discussion and workarounds.

One possible approach will be to employ a declarative type annotation/attribute that can be applied to the `nimble-number-field` similar to what was [developed for controls for WebVIs](https://github.com/ni-kismet/data-types/blob/master/sources/niType.js).

**Comment by fredvisser** [comment]
Closing as low ROI. As always, I continue to welcome any client use cases…
