### ISSUE TITLE
Banner Enhancements

### ISSUE THREAD

**Issue by nate-ni** [ni/nimble#724]
Banner needs to have some additional states documented in the design doc:

- Multiline text
- Stacking multiple banners (might be the same type, might be different types....Warning, Info, Error, etc.)
  - What order do we keep them in? (time, severity, etc.?)
- How many versions do we need? (Solid, outline, more?)

**Comment by NIbokeefe** [comment]
Navigate to: Notifications > Banners

Link to development spec:

https://nio365.sharepoint.com/sites/SystemLinkDesignSystem/Shared%20Documents/Forms/AllItems.aspx?csf=1&web=1&e=aYqhMD&CT=1656508192943&OR=Teams%2DHL&CID=268940c9%2Dea7e%2D64e6%2D9439%2Ddd1d7f452179&RootFolder=%2Fsites%2FSystemLinkDesignSystem%2FShared%20Documents%2FGeneral&FolderCTID=0x012000E78ACBC3759B344A87E59DB2A1AD584A&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiIyOC8yMjA2MTkwMDYwMCIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ%3D%3D

**Comment by nate-ni** [comment]
Link to banner page in spec:
https://xd.adobe.com/view/33ffad4a-eb2c-4241-b8c5-ebfff1faf6f6-66ac/screen/29c405f7-08ea-48b6-973f-546970b9dbab/
