### ISSUE TITLE
Nimble Angular extends the Angular public API

### ISSUE THREAD

**Issue by TrevorKarjanis** [ni/nimble#732]
# 🐛 Bug Report

[NimbleSelectControlValueAccessorDirective](https://github.com/ni/nimble/blob/8174d40b98d5c9841076b867f8c32c193bcbd1e3/angular-workspace/projects/ni/nimble-angular/src/directives/select/nimble-select-control-value-accessor.directive.ts#L24) and [NimbleSelectListOptionDirective](https://github.com/ni/nimble/blob/8174d40b98d5c9841076b867f8c32c193bcbd1e3/angular-workspace/projects/ni/nimble-angular/src/directives/list-option/nimble-select-list-option.directive.ts#L13) extend classes from @angular/forms.

Update:
There seem to be many more cases where we extend Angular classes that do not seem to be explicitly marked as extendable/non-final. This is not a comprehensive list:
- `NimbleNumberFieldControlValueAccessorDirective` extends `NumberValueAccessor`, whose [API doc](https://angular.io/api/forms/NumberValueAccessor) does not explicitly say it is not final/can be extended.
- `NimbleRadioControlValueAccessorDirective` extends `RadioControlValueAccessor`, whose [API doc](https://angular.io/api/forms/RadioControlValueAccessor) does not explicitly say it is not final/can be extended.
- `NimbleToggleButtonControlValueAccessorDirective` and `NimbleSwitchControlValueAccessorDirective` extend `CheckboxControlValueAccessor`, whose [API doc](https://angular.io/api/forms/CheckboxControlValueAccessor) does not explicitly say it is not final/can be extended.
- `NimbleTextFieldControlValueAccessorDirective` and `NimbleTextAreaControlValueAccessorDirective` extend `DefaultValueAccessor`, whose [API doc](https://angular.io/api/forms/DefaultValueAccessor) does not explicitly say it is not final/can be extended.

This is [not supported](https://github.com/angular/angular/blob/main/docs/PUBLIC_API.md) unless explicitly documented.
> We explicitly don't consider the following to be our public API surface:
> - constructors of injectable classes (services and directives) - please use DI to obtain instances of these classes
> - extending any of our classes unless the support for this is specifically documented in the API docs
>
> All classes in Angular's public API are final (they should not be extended) unless explicitly stated in the API documentation.
> Extending such final classes is not supported, since protected members and internal implementation may change outside of major releases.

## 💻 Repro or Code Sample

See [NimbleSelectControlValueAccessorDirective](https://github.com/ni/nimble/blob/8174d40b98d5c9841076b867f8c32c193bcbd1e3/angular-workspace/projects/ni/nimble-angular/src/directives/select/nimble-select-control-value-accessor.directive.ts#L24) and [NimbleSelectListOptionDirective](https://github.com/ni/nimble/blob/8174d40b98d5c9841076b867f8c32c193bcbd1e3/angular-workspace/projects/ni/nimble-angular/src/directives/list-option/nimble-select-list-option.directive.ts#L13).

## 🤔 Expected Behavior

N/A

## 😯 Current Behavior

N/A

## 💁 Possible Solution

This is just a warning that extending the public API can lead to breakages and isn't recommended. If they are documented as supporting such, this can be closed. My search was not extensive. An alternative might be to use composition.  Except for the constructor,  NimbleSelectListOptionDirective is probably not a high risk. However, NimbleSelectControlValueAccessorDirective appears to depend on [undocumented API](https://github.com/ni/nimble/blob/8174d40b98d5c9841076b867f8c32c193bcbd1e3/angular-workspace/projects/ni/nimble-angular/src/directives/select/nimble-select-control-value-accessor.directive.ts#L17).

## 🔦 Context

This was investigated as a possible cause to #729. It was not.

## 🌍 Your Environment

* Version: @ni/nimble-angular@8.4.10

**Comment by TrevorKarjanis** [comment]
> One step we could take to move this forward would be to open an issue / discussion / feature request on the Angular repo to explain our use case and request that the classes we extend be added to the public API. Even if it doesn't get prioritized immediately it would be good to have our use cases on their radar.

Another potential option coming in v14 is utilizing [hostDirectives](https://github.com/angular/angular/pull/47642). The idea being, apply an Angular accessor directive with a nimble directive.

**Comment by m-akinc** [comment]
> Another potential option coming in v14 is utilizing hostDirectives.

Unfortunately, it looks like that was only added in v15.

**Comment by jattasNI** [comment]
@m-akinc if that feature would solve our issue then could we switch to that approach when we fix #1079 (hopefully this cycle)?

**Comment by m-akinc** [comment]
@jattasNI It looks like a promising approach to me. I'd imagine we could wait until then to resolve this.

**Comment by m-akinc** [comment]
We cannot use `hostDirectives` as an alternative to extending `SelectControlValueAccessor` and `NgSelectOption`. There is a requirement that any directive specified in `hostDirectives` must be "standalone", and neither of them are.


![Image](https://github.com/ni/nimble/assets/7282195/71e3ffd3-d74b-4273-8998-7e657aae2541)

**Comment by rajsite** [comment]
> We cannot use `hostDirectives` as an alternative to extending `SelectControlValueAccessor` and `NgSelectOption`. There is a requirement that any directive specified in `hostDirectives` must be "standalone", and neither of them are.
> 
> ![Image](https://user-images.githubusercontent.com/7282195/270815810-71e3ffd3-d74b-4273-8998-7e657aae2541.png)

Ah yea, related to the issues in the Default CVA, Angular doesn't want to make the default CVA's standalone either: https://github.com/ni/nimble/issues/1017#issuecomment-1412957721
