### ISSUE TITLE
Update licenses, packages, other docs in repo for open source usage

### ISSUE THREAD

**Issue by nate-ni** [ni/nimble#740]
## 😯 Problem to Solve
Updates are needed to get our repo ready for being a public repo

## 💁 Proposed Solution/Tasks

- [x] Update repo to use an MIT license
- [x] Update package.json files license field correctly
- [x] Source code files have comments describing their licensing/copyright if necessary
- [x] Add Repo links to communication channels for bugs and discussion
- [x] Add Repo contributing docs describe contribution model (fork vs branch, contributor license agreement if needed)

**Comment by jattasNI** [comment]
At one point we had a thought that our icons might need different licensing than our code and binaries (e.g. creative commons instead of MIT). I don't see that listed anywhere in this issue. @rajsite or @nate-ni or @fredvisser  do you know if we ever reached a decision on whether that was necessary and if so what work needs to happen?

**Comment by nate-ni** [comment]
It was simpler, for the moment, to use a single license type so I had proposed that it all be under MIT. If there is a significant reason to start with a different license for images assets, we can talk about it. We can also update the licensing later if we have to. 

For getting started, it seemed to make things more complicated than they needed to be, so I abandoned considering multiple license types.

**Comment by jattasNI** [comment]
If the answer to [this post on Stack Exchange](https://softwareengineering.stackexchange.com/questions/318777/mit-license-vs-creative-commons-for-images-and-other-assets) is correct, this is a fine starting point.

>There is nothing in principle that would make the MIT license inapplicable to images, as long as they are subject to copyright. One thing to consider, though, is that the MIT license is not very frequently used for artistic works or presentations. So if you want to make it easy for your users to use some pictures in their works, you will do them a favor by dual-licensing them under a Creative Commons license. If you are the copyright holder, you can simultaneously license your work under as many licenses as you wish...Dual-licensing the pictures has the benefit that your project still uses the same license for all files but also offers using a more “natural” license for pictures for those users who would benefit from this.

**Comment by rajsite** [comment]
> If the answer to [this post on Stack Exchange](https://softwareengineering.stackexchange.com/questions/318777/mit-license-vs-creative-commons-for-images-and-other-assets) is correct, this is a fine starting point but we may end up also using CC if our clients aren't satisfied by MIT.
> 
> > There is nothing in principle that would make the MIT license inapplicable to images, as long as they are subject to copyright. One thing to consider, though, is that the MIT license is not very frequently used for artistic works or presentations. So if you want to make it easy for your users to use some pictures in their works, you will do them a favor by dual-licensing them under a Creative Commons license. If you are the copyright holder, you can simultaneously license your work under as many licenses as you wish...Dual-licensing the pictures has the benefit that your project still uses the same license for all files but also offers using a more “natural” license for pictures for those users who would benefit from this.

Agree that MIT is probably fine to start. Other icon system licenses:
- Material Icons uses[Apache 2](https://developers.google.com/fonts/docs/material_icons#licensing).
- Font Awesome uses [CC BY 4](https://fontawesome.com/license/free#icons). 
-

**Comment by nate-ni** [comment]
Licenses have been updated. All packages reflect an MIT license on npmjs.org or nuget.org where appropriate.
