### ISSUE TITLE
Drawer styles need updating

### ISSUE THREAD

**Issue by mollykreis** [ni/nimble#747]
# 🐛 Bug Report

The styles for the nimble-drawer need to be updated based on the [latest designs in XD](https://xd.adobe.com/view/33ffad4a-eb2c-4241-b8c5-ebfff1faf6f6-66ac/screen/6defe795-3099-4738-a15b-5a220b446366/specs/).

2024 visual design issue to update best practices: #1805 

Includes:
- Changing from styling specific expected child elements to using a slot based api like the dialog.
- The line that appears below the tabs which you can note is not inside the scroll area.

Here's a snapshot of the new design.
![image](https://user-images.githubusercontent.com/10500124/206007416-b1712676-35c1-4fbf-88c4-f715357dc6a7.png)

## 🤔 Expected Behavior

While doing this we should refactor the drawer's content slots to match the patterns we established when refactoring the dialog.

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* Version [e.g. 1.8.0]

**Comment by jattasNI** [comment]
Re-added the triage tag to trigger a discussion of whether there is anything left to do on this issue.

**Comment by jattasNI** [comment]
After team discussion, there is lots of work we still want to do. I updated the description to capture it in more detail.

**Comment by NITFALL** [comment]
Nimble-Tab-Panel styling needs also to be adapted, see [PR: Fix sildeout layout containing tabs](https://dev.azure.com/ni/DevCentral/_git/Skyline/pullrequest/672998) so we can remove ng-deep styling

**Comment by fredvisser** [comment]
Will capture any specific items required to update the drawer styling as part of the conformance items identified in #1150
