### ISSUE TITLE
How do we ensure the Nimble icons on NI corporate wallpaper remain up to date?

### ISSUE THREAD

**Issue by jattasNI** [ni/nimble#753]
# 🎙 Discussion

_This issue only exists to test the Discussion issue template._

Nimble icons are printed on wallpaper at NI headquarters. How can we ensure that wallpaper stays up to date when our icons change?

Some ideas:
1. never change icons that appear on the wallpaper
1. add a github action that detects when icons change and files a Jira ticket to facilities to print new wallpaper
2. devote a full-time visual designer to updating the existing wallpaper with whiteout and markers

Thoughts?

**Comment by rajsite** [comment]
@jattasNI to you have a photo / screenshot of the wallpaper as an example and / or can you reproduce the wallpaper in a stackblitz?

**Comment by jattasNI** [comment]
Yeah sure I can get you a photo of stackblitz later but in the meantime it looks kind of like https://ni.github.io/nimble/storybook/?path=/story/icons--icons but if that was made of wallpaper.

**Comment by rajsite** [comment]
Thanks, I'll able to see the same behavior locally

**Comment by nate-ni** [comment]
LInk to StackBlitz of icons: [Nimble Angular 12 App](https://stackblitz.com/edit/nimble-angular-12-app-6qayt4
)
