### ISSUE TITLE
Landing Page for Design System Documentation

### ISSUE THREAD

**Issue by nate-ni** [ni/nimble#771]
## 😯 Problem to Solve
We need a compelling landing page for the Nimble Design System documentation. 
Initially, this will likely just be the home page of Storybook, or link to it. 

## 💁 Proposed Solution
Here are some examples of landing pages from other design systems:
https://www.fast.design/
https://www.lightningdesignsystem.com/
https://carbondesignsystem.com/
https://spectrum.adobe.com/
https://clarity.design/
https://ni.github.io/design-system/   😁

## 📋 Tasks
- [ ] Create design for landing page
- [ ] Implement landing page

**Comment by nate-ni** [comment]
As this page will largely be a jumping off point to other areas (for now) where should/could we link it to?

- Storybook
- Nimble Repo
  - Specific spots in repo (Issues, for example)
- Sample apps
- Fuse?? (might confuse folks....not sure)

@rajsite @NIbokeefe @leslieab @RickA-NI @atmgrifter00 @mollykreis @msmithNI @m-akinc @fredvisser @jattasNI

**Comment by jattasNI** [comment]
Other ideas, not sure if good:
 - link to ni.com. Good because it associates the design system with NI. Possibly confusing because ni.com itself doesn't use Nimble.
 - link to real apps that use design system. e.g. the URL of our major client once it's hosted publicly

**Comment by NIbokeefe** [comment]
https://atlassian.design/components/breadcrumbs/examples
https://m3.material.io
https://spotify.design/article/reimagining-design-systems-at-spotify
https://indeed.design/brand/iconography
https://polaris.shopify.com

**Comment by NIbokeefe** [comment]
Nathan,

There are two pages on this spec.  

- Page 1 full screen
- Page 2 example of a smaller window resize, with scrolling.

Notes:  I've chosen to go with the clean/simple execution for the links (Storybook, Github, etc). If it's too problematic; where the links are overlap on the background we can always go with the "footer" or "card" execution.  

XD Spec:
https://xd.adobe.com/view/b9a38ee3-a4ca-42de-9a83-8733bb563876-ecf0/

Production asset attached as SVG.  Reach out to me if you need the illustrator file.

![Image](https://user-images.githubusercontent.com/106594349/202244781-183a322b-181a-4bf0-ba40-8accc8db4f29.svg)
