### ISSUE TITLE
Error typography

### ISSUE THREAD

**Issue by nate-ni** [ni/nimble#775]
Error text size is currently 9, but is hard to read. It should be bumped up to 11.

**Comment by NIbokeefe** [comment]
I have completed updating the tokens in the Nimble_Components DSP document to reflect the new typography changes for errors on controls; 11px Source Sans Pro.

I have also gone through each individual control for each UI theme and updated the error typography to use the correct tokens and adjusted the container height to 14px.

**Comment by NIbokeefe** [comment]
Accidentally closed while commenting.
