### ISSUE TITLE
Need alternative to XD VSCode plugin for integrating tokens from design

### ISSUE THREAD

**Issue by nate-ni** [ni/nimble#777]
## 🧹 Tech Debt
The Adobe XD VSCode extension appears to be dead. It no longer allows loading the XD library from Creative Cloud and doesn't appear to be getting updates anymore.

Last update was 1.2.3 (6/3/2021)

There may still be a use for it but it will no longer be a viable way to import tokens from Visual Design in to the token system.

Link to folks having the same issue we are:
https://marketplace.visualstudio.com/items?itemName=Adobe.xd&ssr=false#qna
https://marketplace.visualstudio.com/items?itemName=Adobe.xd&ssr=false#review-details
https://community.adobe.com/t5/adobe-xd-discussions/adobe-xd-plugin-for-visual-studio-code-is-not-importing/m-p/13130708
https://community.adobe.com/t5/adobe-xd-discussions/adobe-xd-plugin-for-visual-studio-code-is-not-authenticating/m-p/12370683
https://community.adobe.com/t5/adobe-xd-discussions/vs-code-extension-seems-broken/m-p/13249545

**Comment by jattasNI** [comment]
Closing in favor of #1175
