### ISSUE TITLE
Design for accordion

### ISSUE THREAD

**Issue by nate-ni** [ni/nimble#778]
## 😯 Problem to Solve
Need an interaction and visual design for an accordion.

This issue provides a design for implementing #533 

## 💁 Proposed Solution
Provide a design that incorporates a Nimble-fied version of the FAST Accordion.
https://explore.fast.design/components/fast-accordion

**Comment by atmgrifter00** [comment]
Some prior art that we used for designing the accordion look for BTS:

[https://xd.adobe.com/view/437966ff-1ab6-4d02-9bdf-ce565db5dc9a-162a/screen/93aaefc8-30ca-4375-bbb0-4b35aa2c4b34/](https://xd.adobe.com/view/437966ff-1ab6-4d02-9bdf-ce565db5dc9a-162a/screen/93aaefc8-30ca-4375-bbb0-4b35aa2c4b34/)

**Comment by NIbokeefe** [comment]
To view use: Navigation > Accordion 

This is a work in progress version for feedback and questions.  I'll create all theme colors after we approve this approach.  The original design was done by Meenatchi, I translated that design to our XD component spec.

https://xd.adobe.com/view/33ffad4a-eb2c-4241-b8c5-ebfff1faf6f6-66ac/
