### ISSUE TITLE
Evaluate and extend documentation around writing Angular unit tests with nimble components

### ISSUE THREAD

**Issue by mollykreis** [ni/nimble#779]
## 🧹 Tech Debt
We've seen intermittent tests in SLE (specifically noticed in SystemLinkShared) that are due to incorrect usage of `processUpdates`, `waitForUpdatesAsync`, and `fakeAsync`.

We should consider the following:
- Evaluate our existing documentation to see if it could be extended or improved
- Make sure developers are aware of the documentation (possibly by adding a discussion topic to the UI Working Group meeting)
- Look at SystemLinkShared to see if there are additional tests that should be updated to avoid intermittency in the future
- Consider adding helper functions or test wrappers to make it harder for people to write incorrect tests

**Comment by rajsite** [comment]
> Consider adding helper functions or test wrappers to make it harder for people to write incorrect tests

This point may be handled by #265 which @atmgrifter00 is investigating for their continuous improvement rotation

**Comment by rajsite** [comment]
> Evaluate our existing documentation to see if it could be extended or improved

Maybe the [Testing Asynchronous Behavior in Components](https://dev.azure.com/ni/DevCentral/_wiki/wikis/AppCentral.wiki/15402/Testing-Asynchronous-Behavior-in-Components) could be updated to include nimble-specific behaiors to be aware of (until #265 is addressed more thoroughly). While that might be useful, I'm not sure if that gives the visibility / awareness we are looking for.

**Comment by jattasNI** [comment]
This came up again [in this Teams thread](https://teams.microsoft.com/l/message/19:0c59ac4a4cc1438894cb42f4b21703f9@thread.skype/1677163709141?tenantId=87ba1f9a-44cd-43a6-b008-6fdb45a5204e&groupId=41626d4a-3f1f-49e2-abdc-f590be4a329d&parentMessageId=1677163709141&teamName=ASW%20SystemLink&channelName=UI%20Working%20Group&createdTime=1677163709141&allowXTenantAccess=false). Trevor took an action item to summarize the info in that thread in documentation.

**Comment by jattasNI** [comment]
The [async testing wiki page](https://dev.azure.com/ni/DevCentral/_wiki/wikis/AppCentral.wiki/15402/Testing-Asynchronous-Behavior-in-Components) has been updated.
