### ISSUE TITLE
Update design tokens

### ISSUE THREAD

**Issue by nate-ni** [ni/nimble#781]
## 😯 Problem to Solve
The design tokens we use need to be updated from the latest from visual design. Unfortunately, the Adobe XD VSCode extension is no longer working(#777) for part of this process and it appears that new/updated tokens will need to identified and updated manually.

Known updates:
#775  , #696 

Related PRs:
- #952

**Comment by mollykreis** [comment]
Open questions for the shadow tokens:
- What should we name the three tokens? Are there any existing naming conventions in other design systems that we could follow?
- Should the color of the shadow be the token, or should we have a token for the whole box shadow (i.e. color, X, Y, & blur)? There are some implications of creating a token of "box shadow" type, which doesn't exist yet.

**Comment by jattasNI** [comment]
As discussed in #835, once we are able to easily add color tokens to nimble-tokens again, we should do so for the colors used in `[/nimble-components/src/wafer-map/modules/prerendering.ts](https://github.com/ni/nimble/pull/835/files/1a3cb18be91dadc985f0e63f46cba83fe7f5ce7a#diff-f7818e503a099268b6e600871df415d39a36dc6e3d2f52351bc37ecd01d4dfc9)`

**Comment by nate-ni** [comment]
> As discussed in #835, once we are able to easily add color tokens to nimble-tokens again, we should do so for the colors used in [/nimble-components/src/wafer-map/modules/prerendering.ts](https://github.com/ni/nimble/pull/835/files/1a3cb18be91dadc985f0e63f46cba83fe7f5ce7a#diff-f7818e503a099268b6e600871df415d39a36dc6e3d2f52351bc37ecd01d4dfc9)

Will be addressed by 
- #971 

The immediate needs of this item have been addressed by the related PRs in the description.
