### ISSUE TITLE
Visual design for graph parts

### ISSUE THREAD

**Issue by jattasNI** [ni/nimble#787]
Sometime in Q4 a team will be incorporating a plotly graph into SLE. We would like it to use colors/fonts/spacing that aligns with other Nimble components.

This could be a lightweight pass to tell them which tokens to use for:
1. background color
2. text color, font, and size (axis and tick labels)
3. tick and grid line color and line thickness
5. plot colors
   - in this case the spec shows dots for each point but eventually clients will come along who want to connect them with lines
   - in this case there might only be one or two plots but we should provide a palette of default colors for many plots (a dozen?)
5. other graph parts like toolbars and legends
6. tooltips showing more information when hovering over a point

![](https://user-images.githubusercontent.com/10500124/196209932-c68aa72b-695a-4c9b-9a18-c50a950e3bd2.png)

**Comment by jattasNI** [comment]
Another screenshot from an earlier visual design research project.
<img width="914" alt="MicrosoftTeams-image" src="https://user-images.githubusercontent.com/10500124/198382974-48092fe8-1847-46ea-b8a2-786a25e2deba.png">

**Comment by jattasNI** [comment]
Brandon and Rick spoke about this at our team meeting today. Rick has some prior art for plot colors--when the time comes we can ask him for those values. Otherwise when this becomes a priority someone will have to collect values from the comps above and turn them into design tokens, filling in whatever gaps we find along the way.

**Comment by rajsite** [comment]
Some discussion on creating plotly templates to implement theming: https://www.nelsontang.com/blog/2021-08-01-build-your-first-plotly-template

**Comment by jattasNI** [comment]
Rick noted that there is no design for the color theme because it's impossible to pick plot colors that would work against every possible background color. For now we can just document that it's unsupported and use some placeholder colors (since the helpers in `design-tokens.ts` require that we provide colors for every theme).

**Comment by rajsite** [comment]
> Rick noted that there is no design for the color theme because it's impossible to pick plot colors that would work against every possible background color. For now we can just document that it's unsupported and use some placeholder colors (since the helpers in `design-tokens.ts` require that we provide colors for every theme).

For future considerations of color theme maybe we should think of it like monochrome printing. Would use different line styles and maybe picking the order of line styles could come from nimble.

**Comment by kroeschl** [comment]
Would it be possible to get tokens for graph colors beyond the existing `$ni-nimble-graph-gridline-color` token? Specifically, I'm looking for specific colors to use for e.g. different data series or different bars in a bar graph.

**Comment by rajsite** [comment]
> Would it be possible to get tokens for graph colors beyond the existing `$ni-nimble-graph-gridline-color` token? Specifically, I'm looking for specific colors to use for e.g. different data series or different bars in a bar graph.

@fredvisser @atmgrifter00 token name proposal:

Looks like Rick specced out 8 line colors. Guessing they are intentionally different from the Brand illustration guidelines?

-  [brand login credentials](https://nio365.sharepoint.com/sites/BrandCreative/SitePages/Brand-Guidelines.aspx)
-  [illustration construction guidelines](https://nibrand.frontify.com/document/4#/infographics-illustrations/infographics/construction) saying use secondary colors
- Page with [secondary color palette](https://nibrand.frontify.com/document/4#/color/color-palette-1)

Assuming the Xd tokens are good, I'd propose [token names](https://github.com/ni/nimble/blob/main/packages/nimble-components/CONTRIBUTING.md#component-naming):
- element: `graph`
- part: `trace-1`, `trace-2`, `trace-3`, up to `trace-9`
  - assumes we don't need to go double digits in traces?
  - using the plotly term `trace` for data + config which is decoupled from plot type, not sure if there are other standard terms
- interaction_states: n/a
- remainging_states: n/a
- token_type: `color`

Result: `ni-nimble-trace-1-color`, `ni-nimble-trace-2-color`, etc.

**Comment by fredvisser** [comment]
Sounds good - let's use the 8 XD tokens. And I don't expect to define more than the 8 colors, so the single digit suffix will work well. 

Per the naming scheme, should it be `ni-nimble-graph-trace-1-color`?

**Comment by rajsite** [comment]
> Per the naming scheme, should it be `ni-nimble-graph-trace-1-color`?

Yep! Even called it out as the`element` but messed up writing the result 🤦

**Comment by kroeschl** [comment]
Thanks!
