### ISSUE TITLE
Sectioned Select

### ISSUE THREAD

**Issue by TJ-G** [ni/nimble#791]
## 😯 Problem to Solve
I don't see anything tagged as 'client-request' or 'enhancement' that matches this, but please feel free to close if I missed an existing request similar to this.

When a user selects a notebook (say from the analyze slide-out in the files grid), they see all notebooks published to workspaces they have access to. One key thing here is that notebooks are published to workspaces for access control. Notebooks with the same name may be published to different workspaces and, currently, will show up in the dropdown without any way to differentiate which one is in what workspace.

## 💁 Proposed Solution
I'd like the ability to section/segment/group the items in a combo-box and give each section a header. This would let me group the notebooks by what workspace they're in, and let the user know the name of that workspace by using that as the header for each section.

It looks like we can sort of get this behavior by inserting disabled items as the header, but that means we can't actually have disabled items in the list, and they don't really stand out as a 'header' and are hard to read.

![image](https://user-images.githubusercontent.com/7433612/196754153-c30cefd5-6d40-4639-b265-9d4214c5c87a.png)

**Comment by m-akinc** [comment]
You can actually include elements other than `nimble-list-option` in the combobox's content, e.g. `<h3>Workspace 1</h3>`. Does that fully address your use case?

**Comment by TJ-G** [comment]
Oh, interesting... yes, I think it would, especially if we can stylize them a bit.

Thanks for letting me know that's already possible!

**Comment by rajsite** [comment]
> You can actually include elements other than `nimble-list-option` in the combobox's content, e.g. `<h3>Workspace 1</h3>`. Does that fully address your use case?

@m-akinc @atmgrifter00

I don't see any stories or tests describing that use case. Is it tested (maybe I'm missing it)? Do we know how things like tab order and keyboard interactions, etc behave? What kind of content are we supporting, just decorative or interactive (can you dump a textbox, or a nimble-button in there)?

If we say it's supported we need testing and user guidance of what is supported. In addition we need documentation and examples in storybook.

Generally speaking we do not support placing arbitrary content in slots. Only certain use-cases are supported and we should add tests if we want to say we support additional use cases.

**Comment by jattasNI** [comment]
One other workaround available today would be to append additional information to each item's text. e.g. "Notebook 1 (Default Workspace)"

**Comment by jattasNI** [comment]
This request came up again in [this SLE PR](https://dev.azure.com/ni/DevCentral/_git/Skyline/pullRequest/475249#1681993948). It was the same use case: notebooks in different workspaces not being easily distinguished.

![image](https://user-images.githubusercontent.com/10500124/233670174-842f07b3-9b3d-4596-a6e7-1d369dfe9b46.png)

**Comment by jattasNI** [comment]
[Here's another SLE PR](https://dev.azure.com/ni/DevCentral/_git/Skyline/pullrequest/484936?_a=files) implementing the approach described above of adding `<div>` elements to delineate sections. As suggested above, we should add test coverage and documentation for this case.

**Comment by jattasNI** [comment]
@NIbokeefe in [this SLE PR](https://dev.azure.com/ni/DevCentral/_git/Skyline/pullrequest/484936) we're adding section headers to separate groups of combobox items. Do you have any visual design feedback about the styling of the headers? Personally I think the padding looks a bit cramped but I defer to your recommendations. 

![image](https://github.com/ni/nimble/assets/10500124/397ed3e7-3a48-473f-a999-79c966297300)

**Comment by NIbokeefe** [comment]
> @NIbokeefe in [this SLE PR](https://dev.azure.com/ni/DevCentral/_git/Skyline/pullrequest/484936) we're adding section headers to separate groups of combobox items. Do you have any visual design feedback about the styling of the headers? Personally I think the padding looks a bit cramped but I defer to your recommendations.
> 
> ![image](https://user-images.githubusercontent.com/10500124/238078803-397ed3e7-3a48-473f-a999-79c966297300.png)

@jattasNI 

I have a design for headers/group-labels for menus.  In this design you've shown here it looks like we are using the **controlLabel_1** token as the menu header.  Instead if you can use the **GroupLabel_1** token documented in both XD and Figma.  It's an 11px Source Sans Pro Semi-bold font.  The color token is Black91 @ 100% Opacity.

You should be able to extract the correct spacing from either of those spec documents.  Please let me know if you run into any issues.

https://www.figma.com/file/PO9mFOu5BCl8aJvFchEeuN/Nimble_Components?type=design&node-id=1295%3A93863&t=JljnGeOi5lXwzyQf-1
<img width="1055" alt="Screen Shot 2023-05-15 at 2 44 39 PM" src="https://github.com/ni/nimble/assets/106594349/ca1c1a6f-8466-4173-951c-52f4660b8841">

https://xd.adobe.com/view/33ffad4a-eb2c-4241-b8c5-ebfff1faf6f6-66ac/
<img width="698" alt="Screen Shot 2023-05-15 at 2 46 39 PM" src="https://github.com/ni/nimble/assets/106594349/356e8794-37a1-4684-9f41-4ef4f64f63ad">

**Comment by rajsite** [comment]
@NIbokeefe would we expect to use the horizontal line between each of the headed groups like the menu? Notice that the screenshot of the select currently doesn't have those.
Are we concerned about forcing all caps on user provided strings? I'm not actually sure if workspace names are case-sensitive.

**Comment by NIbokeefe** [comment]
@rajsite 

Great questions Milan, thank you!

**Horizontal line:**  My instinct is to keep the lines by default for the sake of simplifying the way we handle our patterns.  If it's important to separate items by group it's ideal to visually reinforce it.  This horizontal line brake concept derives from our general menu and serves multiple purposes.  I always try to back a concept by 2-3 visual cues to account for accessibility and unknowns. I'll point out the added benefit to the line brake when regarding potential modification to the typography of the header. 

**All caps:** I don't have the context to this specific situation to say one way or another about the all caps.  By default, we should us all caps to drive consistency.  If the headers are user inputs and the case styling is important to their input; this is for sure a concern and we should consider deviating from the all caps.  The header visual design is supported in multiple ways:  Headers are at the top of grouped items, in semi bold font and are divided by the horizontal line brake.  We're not entirely relying on all caps to determine what's a header, so if we need to make that change it should not be a huge concern.  However, I can't guide whether that's necessary without learning more about the functionality and use case.

**Comment by rajsite** [comment]
A related issue that came up in an [SLE PR](https://ni.visualstudio.com/DevCentral/_git/Skyline/pullrequest/486972) is for the following scenario:

- The combobox has two options that have the same value under different header elements (a notebook with the same name in two different workspaces)
- The Angular CVA for the combobox always picks the first model object that matches the selected option value
- How can the app get the second model value instead?

This goes against the design of the combobox as-is which is modelled as a text input field that should not have knowledge of option selected but instead of text selected. Likely the desired behavior is to use a select control instead with the UX of being able to type ahead to filter options which can model a selected option correctly.

**Comment by jattasNI** [comment]
## Interaction Design Questions

1. how does filtering impact the section headers? Are the headers still visible after items are filtered (they likely should be)? Do section headers match the filter? If they do, should we show everything under the header that matches even if those items don't themselves match the filter?

We plan to have the dev team propose answers to these questions and run them by IxD.

**Comment by m-akinc** [comment]
The functionality is now part of the Nimble select. We'll use a [separate AzDO feature](https://ni.visualstudio.com/DevCentral/_workitems/edit/2769262) to track integration into SLE.
