### ISSUE TITLE
Comment component

### ISSUE THREAD

**Issue by nate-ni** [ni/nimble#793]
## 😯 Problem to Solve
I high-order component that allows users to comment. 
Similar to what is seen right here in GitHub and also in apps like Azure DevOps.

Potentially also look at how Office and Adobe XD provide comments in their right rail. This may/may not be appropriate for our use but is worth researching.

**Comment by jattasNI** [comment]
As we've started working on #1288 we've decided that Nimble should include components for rich text editing, viewing, and a way to do @mentioning but we don't think it should compose these into higher level comment component with support for displaying multiple comments, buttons for modifying/deleting comments, or a connection to a back-end. Our rationale is that those commenting features are likely to have app-specific UX and be tied to app-specific layers like localization and back-end services.

So I'm closing this issue for now. If anyone would like to revisit this decision, feel free to re-open and re-start the discussion.
