### ISSUE TITLE
Rich Text Editor component

### ISSUE THREAD

**Issue by nate-ni** [ni/nimble#794]
## 😯 Problem to Solve
A high-order component for allowing the user a consistent way to create and edit rich text.

## 💁 Proposed Solution
Could be MarkDown, a flavor of MarkDown or a different format for rich text.
Depending on user needs, something WYSIWYG may be more appropriate.
Needs to support `@mentions`

#### Quill - https://github.com/quilljs/quil
Quill is an example of a, non-markdown, technology but appears to no longer be maintained.
#### TipTap - https://github.com/ueberdosis/tiptap
TIpTap is a headless editor framework.

**Comment by rajsite** [comment]
Some research I'd done for RichText for WebVIs, it's a couple years old but the concepts are relevant https://github.com/rajsite/webvi-experiments/tree/main/RichText#rich-text-for-webvis

**Comment by prestwick** [comment]
FYI, a component with this capability came up in the context of the comments feature the LIMS teams may be prioritizing.
