### ISSUE TITLE
Support TypeScript 4.8

### ISSUE THREAD

**Issue by TrevorKarjanis** [ni/nimble#810]
## 🧹 Tech Debt

As per [issue 6365](https://github.com/microsoft/fast/issues/6365), @microsoft/fast-foundation is not compatible with TS 4.8.

We need to support TypeScript 4.8 to support Angular 15 where [TS 4.8 is the minimum support version](https://angular.io/guide/update-to-version-15#angular-v15-supports-typescript-version-48-or-later).

**Comment by rajsite** [comment]
FAST has a PR up from a contributor for TypeScript 4.8 support: https://github.com/microsoft/fast/pull/6779

We should try it and see if it can unblock Angular 15+ upgrades.

**Comment by rajsite** [comment]
With `@microsoft/fast-foundation` [v2.49.2](https://www.npmjs.com/package/@microsoft/fast-foundation/v/2.49.2) which includes changes from https://github.com/microsoft/fast/pull/6779 we should be unblocked by FAST for upgrading the typescript version.
