### ISSUE TITLE
Background color of menus in Color theme is incorrect

### ISSUE THREAD

**Issue by mollykreis** [ni/nimble#815]
# 🐛 Bug Report

The background color of menus in the Color UI theme is incorrect. It should be Forest Green + White @ 15% (according to the spec as of Nov 11 2022), but instead the background color is Forest Green.

## 💻 Repro or Code Sample

Look at a menu in the Color UI

## 🤔 Expected Behavior

Should look like this:
![image](https://user-images.githubusercontent.com/20542556/201383395-b01daf4f-7f13-4d63-82f2-ec136963e51c.png)

## 😯 Current Behavior

Looks like this:
![image](https://user-images.githubusercontent.com/20542556/201383473-a94e9ab0-abba-4351-bc7f-ac12d79ea344.png)

## 💁 Possible Solution

Fix the styling -- The Color UI of the tooltip faced a similar problem, so its styling could possibly used as an example.

## 🌍 Your Environment

Not environment dependent

**Comment by nate-ni** [comment]
@mollykreis, is there a way to achieve this by figuring out how to get two colors in the background or would it be simpler if we had a single flat color that was, essentially, the combination of the the green and semi-transparent white color?
