### ISSUE TITLE
Interactively resize column width

### ISSUE THREAD

**Issue by nate-ni** [ni/nimble#846]
## 😯 Problem to Solve
The end user needs to able to adjust the width of a column. 

## 💁 Proposed Solution
Design will be provided by
- [x] #885 

## 🤔 Open Questions
Now that the table will be interactive, this is a good point to decide about "role" for the Nimble table. We should resolve this before closing this or other "interactive" work items.

**Comment by tatwood2** [comment]
The Licensing NIC team would like to use this enhancement in our desktop Electron with Blazor application for LiMo when it is ready.  Please keep us in the loop as we'd like to uptake it as soon as it is ready.
