### ISSUE TITLE
Grouped columns in tables

### ISSUE THREAD

**Issue by nate-ni** [ni/nimble#847]
## 😯 Problem to Solve
This is a configuration of a table at development time to allow the ability to group columns.

## 💁 Proposed Solution
- [x] #895

## 🖼️ References/Prior Art
**TanStack React Example**
https://tanstack.com/table/v8/docs/examples/react/column-groups

**Other Example**
![Image](https://user-images.githubusercontent.com/109235103/200355754-fecb4311-8b33-44b8-b9bc-985a00aece01.png)

**Comment by fredvisser** [comment]
Not prioritized against current client requirements.
