### ISSUE TITLE
Design for visually connecting rows of content

### ISSUE THREAD

**Issue by nate-ni** [ni/nimble#849]
## 😯 Problem to Solve
There is a desire to provide an, easy to read, way to separate rows of content.
This need should be investigated/validated prior to work as the current design may suffice.

## 🤔 Open Questions
1. Does our current design/approach suffice?
 - Current approach will probably be found in this work item (unknown at time of writing)
 - [x] #883 
2. Should we provide alternative options for developers to accommodate a more diverse set of client needs?

**Comment by atmgrifter00** [comment]
@nate-ni, is this issue better worded as "visually connect _columns_ of content"? To me it seems the problem we're trying to solve is for a user to be able to determine which values in a given row are related with one another (i.e. across the various columns), which can be potentially solved by highlighting a row on hover, for instance.

**Comment by nate-ni** [comment]
I'm trying to describe the need that can be solved, like you said, by providing a hover state. It is also sometimes accomplished by zebra stripes in some tables. For normal states, it is sometimes provided just by lines instead of zebra stripes (or both).

This is issue is to figure of all of those, what are going to do.
