### ISSUE TITLE
Tooltip support for truncated cells

### ISSUE THREAD

**Issue by nate-ni** [ni/nimble#857]
## 😯 Problem to Solve
If a table cell (or table header cell) is too small to display the contents, it should be truncated. They user should be able to access the full content via a tooltip.

## 💁 Proposed Solution
 - [ ] #889

## 🤔 Open Questions
Are there any things to make sure we address for accessibility...alt text for truncated content?
Depends on: 
- [ ] #309

**Comment by jattasNI** [comment]
This was largely implemented in the PR linked above but I think one piece is missing: tooltips for truncated header text. We [thought about including this in another PR](https://github.com/ni/nimble/pull/1092#discussion_r1123607579) but I don't see it in the code or the product.

**Comment by m-akinc** [comment]
The change to provide tooltips for truncated header text was reverted in that dev branch before the branch was merged. Meyer had to revert it because of some issue he was dealing with, but now it seems like it can be re-applied. I believe he is going to submit it.
