### ISSUE TITLE
Tooltip support for extra cell information

### ISSUE THREAD

**Issue by nate-ni** [ni/nimble#858]
## 😯 Problem to Solve
A developer should be able to provide more information to expand on some content in a cell.

## 💁 Proposed Solution
 - [x] #889 

### Accessibility
1. Should the content be somewhere else in the markup so screen readers can see it?
2. Should we just pull from there?
3. How does this work alongside truncated cell content?
  - [x] #857 

## 🖼️ References/Prior Art
For example
![Image](https://user-images.githubusercontent.com/109235103/200389344-30a55713-3439-4825-b7ea-15ac69eaf37f.png)

**Comment by fredvisser** [comment]
The title attribute is fully supported for truncated column text and the [icon column](https://nimble.ni.dev/storybook/?path=/docs/components-table-column-icon--docs). See also #857. Closing.
