### ISSUE TITLE
Interactive grouping data rows

### ISSUE THREAD

**Issue by nate-ni** [ni/nimble#867]
## 😯 Problem to Solve
We need to provide the ability for the user to do "simple grouping" in the table and make sure we still support the existing workflows of supporting multiple groups.

In this context, simple grouping provides the ability to quickly group/ungroup data in a table by a single column value.

## 💁 Proposed Solution
 - #885 

## 🤔 Open Questions
Can we make sure that the current state of grouping is reflected so that it is known for any programmatic grouping that may also need to be supported?

Now that the table will be interactive, this is a good point to decide about "role" for the Nimble table. We should resolve this before closing this or other "interactive" work items.

**Comment by fredvisser** [comment]
Adding column header menus to support grouping is not a near to medium priority for the nimble-table. In Stratus apps, we have other shared components to configure columns, so don't require this capability.
