### ISSUE TITLE
As a table user, I should be able to programmatically handle the view configuration of my table.

### ISSUE THREAD

**Issue by nate-ni** [ni/nimble#870]
The table has view configuration state that is created interactively (non-comprehensive) such as:
- column sorting
- column grouping

And programmatically (non-comprehensive) such as:
- column visibility
- column ordering

Table integrators need a way to programmatically set view configuration state, be notified of interactive changes to view configuration state, and read the current table view configuration state.

We need a research spike / prototypes to answer several questions:
- Should every interactive operation that changes table view state have its own event?
  - Are those events just for tracking view state changes that are likely to be persisted or do they have other uses?
    - For instance sorting a column may fire an event that can have the default prevented so that the table author and query a backend for new sorted data.
- Should there be a single "view-configuration" type event so that table integrators don't have to listen to many different events?
   - Should such an event give a table-defined representation of the view state that can be persisted and restored without significant extra processing?

**Comment by rajsite** [comment]
Added the triage tag as there was concerns that we should start addressing this issue sooner and so we can prioritize

**Comment by jattasNI** [comment]
Related: #1047 is the (currently not prioritized) follow up work to make this part of the table itself.

**Comment by mollykreis** [comment]
We've added a `column-configuration-change` event to the table that emits when a column's configuration is changed interactively by the user. The event details include the current configuration of all columns. We decided that having functions to get/set the column configuration at an arbitrary point in time was not necessary at this point in time.

See #1240 and #1247
