### ISSUE TITLE
Programmatically resize column width

### ISSUE THREAD

**Issue by nate-ni** [ni/nimble#873]
## 😯 Problem to Solve
There is a need to provide a method of adjusting column widths in a table from outside of directly interacting with the table. 

The most notable use case is within SLE where columns need to be resized from loading a saved/stored view.

## Solution details
The implemented solution will allow the previously mentioned use case to work with the `nimble-table`

```[tasklist]
## Related PRs
- [ ] #1002
```

**Comment by jattasNI** [comment]
This was completed via #1098
