### ISSUE TITLE
Define keyboard interactions of table

### ISSUE THREAD

**Issue by nate-ni** [ni/nimble#877]
## 😯 Problem to Solve
There are expected keyboard interactions for a table and it can vary based on whether we deem to be the "grid" model or "table" model from the W3C.

## W3C References
https://w3c.github.io/aria-practices/#table
https://w3c.github.io/aria-practices/#grid

## ARIA References
https://www.w3.org/WAI/ARIA/apg/patterns/table/
https://www.w3.org/WAI/ARIA/apg/patterns/grid/

## External References
https://material.angular.io/components/table/overview#accessibility
https://carbondesignsystem.com/components/data-table/accessibility
https://spectrum.adobe.com/page/table/#Keyboard-interactions

**Comment by jattasNI** [comment]
In today's SLE iteration review, someone asked about keyboard navigation in hierarchical grids. I think we'd want to support using arrow keys to navigate between rows and expand/collapse them.

**Comment by leslieab** [comment]
[IxD design document](https://xd.adobe.com/view/fa09e396-dbb9-40b8-547f-1cf9eab35a0b-8c38) (password is UXDesign1).

Please note that this document includes keyboard interactions for group rows, but not for hierarchical data rows. I will include hierarchical data row keyboard interactions as part of #890 in Milestone 4.

**Comment by jattasNI** [comment]
Leslie responded to all of the dev team's feedback in the linked document so we're ready to call this closed. We can pick up more detailed discussion when we're ready to implement it.
