### ISSUE TITLE
Visual design for initial table implementation

### ISSUE THREAD

**Issue by nate-ni** [ni/nimble#883]
## 😯 Problem to Solve
This design should provide visual design information for a basic, non-interactive table.

#### Typography
- [ ] Header cell
- [ ] Table cell

#### Colors
- [ ] Header background
- [ ] Header borders
- [ ] Cell background
- [ ] Cell borders
- [ ] Table Borders (if any)

#### Sizing
- [ ] Header height
- [ ] Cell height

**Comment by RickA-NI** [comment]
updated spec with Dark and Color themes as well as added the selected rollover state for all themes
