### ISSUE TITLE
UX Design for basic column/row interactions

### ISSUE THREAD

**Issue by nate-ni** [ni/nimble#885]
## 😯 Problem to Solve
Sorting
Simple Grouping/Ungrouping
Resizing
Visual Design for Multiple groups
Collapsing table contents (aka "Collapse All")
Interactive states for columns and rows (Hover, etc.)

## 🤔 Open Questions
1. There will be a min width necessary. 
    - Will it be different for interactive columns vs static columns (columns with no sorting, grouping, etc.) ?
2. How will the user "auto-fit" the width of a column
    - Through a command ("size to fit")?
    - Double-clicking on the column edge (like Excel)?
    - Both?
    - Something else?

3. Cursor Feedback - The cursor should provide an appropriate cursor to communicate state when interacting
4. While resizing, how should the UI should update to reflect the state?
5. When table is grouped (or any tree-like view) how should sorting work?
6. While we won't be implementing interactive column re-ordering at the same time. It should be a consideration for this design.

```[tasklist]
## 📋 Tasks
- [ ] https://github.com/ni/nimble/issues/1085
- [ ] https://github.com/ni/nimble/issues/1086
```

## 🖼️ References/Prior Art
**Example of simple grouping GH Projects**
![Image](https://user-images.githubusercontent.com/109235103/205622947-3d9befbf-0417-441d-af7c-85b4366dd006.png)

![Image](https://user-images.githubusercontent.com/109235103/205622984-ab0c01f6-65ea-4369-865e-3466f9895b48.png)

**Comment by jattasNI** [comment]
https://xd.adobe.com/view/6f3be15d-8503-4f1f-54b9-5bc27955b3e4-190a/
UXDesign1

**Comment by leslieab** [comment]
Note: I have added mouse interaction information to the [IxD design document](https://xd.adobe.com/view/6f3be15d-8503-4f1f-54b9-5bc27955b3e4-190a) (password is UXDesign1) for tables that support multi-sort.

SHIFT + CLICKING an unsorted column adds the column to the sort hierarchy and sorts it in an ascending direction. SHIFT + CLICKING a sorted ascending column keeps it in the sort hierarchy and sorts it in a descending direction. SHIFT + CLICKING on a sorted descending column removes it from the sort hierarchy and unsorts it.

Purely keyboard interactions for sorting, multi-sorting, grouping, and multi-grouping are documented as part of #877 .

**Comment by msmithNI** [comment]
@leslieab I have a few questions on the interactive sorting UX.
- If multi-sort is enabled, and multiple columns are currently sorted, will unsorting a column via the header menu unsort the other columns too?
    - i.e. [this screen](https://xd.adobe.com/view/6f3be15d-8503-4f1f-54b9-5bc27955b3e4-190a/screen/3edcb948-fb5d-4503-aaea-30ab0b3e56e0), but if First Name was already sorted (along with City), will unsorting City via the menu result in First Name getting unsorted?
- Similar question with Shift-click on a column header when multiple columns are sorted. If First Name and City are both sorted (descending), and the user Shift-clicks on City (resulting in it being unsorted), should First Name still be sorted?
    - My current assumption is that First Name would still be sorted (i.e. Shift-click will never change the sort of other columns), but I wanted to double-check.

**Comment by leslieab** [comment]
@msmithNI great questions! This might be something worth user testing. For now I would say:

- Yes, let's keep the menu behavior consistent with click behavior
- I agree with your assumptions
