### ISSUE TITLE
Visual Design for basic table content types

### ISSUE THREAD

**Issue by nate-ni** [ni/nimble#887]
## 😯 Problem to Solve
Provide designs for basic content types outside of what was already completed from the initial design 
- #883

### In table cells
- Numeric values (Related dev task: #1011)
- Hyperlinks (Related dev task: #1012)
- Icons (Related dev task: #1013 )
- DateTime (Related dev task: #1014)

### In table header cells
- Icon
- Text and Icon

## 🤔 Open Questions
1. What size should the icons be?
2. Do we need default alignments for different data types?

## 🖼️ References/Prior Art
Design for basic table
- #883

**Comment by jattasNI** [comment]
@RickA-NI here are a couple prototypes of right-aligned numeric columns. They reveal some interesting questions for you to provide guidance on:
1. For numeric columns, should we right align the values, both the values and the header, or neither?
2. If we right align the values, should we also set [`font-variant-numeric: tabular-nums`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-numeric) to request that the browser render digits with equal widths? Does our font support this setting? (I couldn't see a difference when I played with it)

![image](https://user-images.githubusercontent.com/10500124/216631469-ebc5513e-ce2f-42a3-86b3-d38feedbd469.png)

![image](https://user-images.githubusercontent.com/10500124/216631867-a26c4615-949b-4328-a36f-524fd486f358.png)

**Comment by RickA-NI** [comment]
1) My initial reaction is that headers should match their data. I'm not sure what the ramifications are for all the stuff (sorting direction, menu icons, grab handles, etc.) we've talked about stick up there but visually it looks better and keeps the header from becoming dissociated from the data as in your example.
2) Source Sans Pro renders digits with equal widths by default. You shouldn't need to turn that on unless we're trying to force it into a monospaced like mode where the decimal places and commas take up equal space to a didgit.

**Comment by nate-ni** [comment]
I've always thought....strings to the left, numbers to the right...but it is challenging to visually connect data when you don't have borders in the headers to group columns, like we've got.

![Image](https://user-images.githubusercontent.com/109235103/216718117-aeca7292-7b43-4703-941a-2b3412293376.png)

**Comment by RickA-NI** [comment]
I found some blog on table design and it had three (and a half) rules for alignment that seem to jive pretty well with what we're all aligning on here:
![image](https://user-images.githubusercontent.com/104936907/216789239-73cb9987-2398-4426-883c-b5abad2ddfe0.png)

**Comment by nate-ni** [comment]
Ahhhh...the good ole "some blog" :) Just kidding, the No.3 is new to me but does appear to be a pretty standard practice and something I've, admittedly, not thought about too much. Learn something new everyday. 🌈⭐️

No. 3 1/2 is interesting as their could be some cases (not necessarily our use cases) where centering the value along a separator might be preferable like the resolution and ratio columns in the image below. Not sure if modern CSS supports this well yet and probably isn't a priority for us right now, but you can learn more at: https://ux.stackexchange.com/questions/24066/what-is-the-best-practice-for-data-table-cell-content-alignment

![image](https://user-images.githubusercontent.com/109235103/216993140-c18f6053-2915-4ac6-a672-7e386f364c18.png)

Here's a link to another some blog that reiterates 1-3 of the simple rules to follow...with a fun little animation to show the impact. https://www.darkhorseanalytics.com/blog/clear-off-the-table/

**Comment by RickA-NI** [comment]
how is that content aligned in the resolution and aspect ratio columns? I get the intent to align by the midpoint symbol (x or :) but the data in those columns is not left right or center aligned it's like some bespoke hand layout stuff. If you couldn't do a custom layout and had to pick one then I'd think matching the header to the one pick is still the right choice.

**Comment by atmgrifter00** [comment]
@RickA-NI, just for clarity, the aspect ratio column is using an existing [CSS mechanism](https://developer.mozilla.org/en-US/docs/Web/CSS/text-align#syntax) to provide that alignment behavior. Basically, CSS would look like this:
```
.resolution {
    text-align: 'x' center;
}

.aspect-ratio {
    text-align: '.' center;
}
```

**Comment by nate-ni** [comment]
> aspect ratio column is using an existing [CSS mechanism](https://developer.mozilla.org/en-US/docs/Web/CSS/text-align#syntax)

Support for this particular CSS feature doesn't look so great. Looks like we still need vendor prefixes and a non-vendor prefix version might be deprecated/obsolete.
https://caniuse.com/mdn-css_properties_text-align_block_alignment_values

**Support as of 02/02/2023**
![image](https://user-images.githubusercontent.com/109235103/217295870-a572aa74-84c2-4941-8d89-2d79578bf85d.png)

![image](https://user-images.githubusercontent.com/109235103/217296380-5ecedf5c-834d-4f55-b067-abcbea3101fa.png)

**Comment by RickA-NI** [comment]
@jattasNI @nate-ni @leslieab I think I've got these recommendations ready to go. I just want to run them by everyone here before I add examples to the visual spec Storybook is pulling in.

These three rules I think are widely accepted norms and good guidelines for all column types:

1. Numeric data is right-aligned
2. Textual data is left-aligned
3. Headers are aligned with their data

For Numeric value columns I think the above guidelines and Jesse research has pretty much laid out what we do here. We right-align and use tabular numbers. The font is standard body copy. Source Sans Pro has tabular numbers by default so we get that for free.

For Hyperlinks columns we use our standard anchor link control. We treat them as textual data and left-align.

For Icon columns we can have icons with text or without. Either way we treat them as textual data and left-align. Text when needed is standard body copy and offset from icon using our standard sizing token.

DateTime columns are mostly numeric data but seem to be usually treated like textual data and left-aligned. Again we use our standard body copy font. There is a standard format set by ISO 8601 and suggested for use by W3C on how to format this data. We should look into adopting it at least as a default. Here is a summary:

![image](https://user-images.githubusercontent.com/104936907/219173553-0a201ff0-7a97-481b-8841-06ad40850a7a.png)

For a more full breakdown on this standard you can see this page here written by the author.
[https://www.cl.cam.ac.uk/~mgk25/iso-time.html](url)

**Comment by nate-ni** [comment]
The only one that we may have to think more about is #3..."Headers are aligned with their data" specifically for right-aligned content (numbers). All other direction seems pretty solid to me. Since we intend to have controls and icons (for sorting) in the header, we may need to explore how that impacts that particular guidance.

As an example, GH is in a similar situation and has maintained left-alignment in their headers for numeric, right-aligned, columns. While this doesn't dictate our solution, it is a reference to see the impact of that solution.

![image](https://user-images.githubusercontent.com/109235103/219393272-9f47e7d2-b9f1-41be-bc75-385d328c4f6f.png)

I know we don't have final designs for those fully featured headers yet but the initial prototype may give us something to work from.

**Comment by leslieab** [comment]
I agree, I think right-aligning headers is going to be problematic. And due to sort/grouping iconography and the menu button, the text will never vertically right align with row cell content anyway.

**Comment by atmgrifter00** [comment]
@leslieab just brought up the points I was about to. So...I have nothing. Gosh leslie!

**Comment by RickA-NI** [comment]
Here are my column alignment mockups. I think this covers all of the relavent scenarios. Let me know if you like to see something else.
![Column-Alignment](https://user-images.githubusercontent.com/104936907/219809401-721ed589-7248-4ed3-ae97-1ce6e0b0b4ba.png)

**Comment by nate-ni** [comment]
Thanks for posting these, @RickA-NI!! It is really helpful.

If our tables were static (non-interactive) displays of data...or maybe just didn't have multiple elements in the header; I think we would align the header content with the column content...but they aren't. I think we should start with keeping the header content left-aligned.

This might just be a place to start, I think this is a decision we can change relatively easy and with low impact.
Having all the controls in the same order across headers will also likely make things a little less complicated when we get to supporting keyboards and screen readers.

**Comment by jattasNI** [comment]
One more case to consider: would numeric data with units still be right aligned? We lose some benefit of right aligning if the units have inconsistent widths. e.g.:
```
Voltage
    101.0V
     1.3mV
    25.7kV
```

**Comment by jattasNI** [comment]
> Here are my column alignment mockups. I think this covers all of the relavent scenarios. Let me know if you like to see something else. ![Column-Alignment](https://user-images.githubusercontent.com/104936907/219809401-721ed589-7248-4ed3-ae97-1ce6e0b0b4ba.png)

Sounds like @nate-ni's vote is to go with "Numeric headers left aligned, values right-aligned" to begin with. I'm ok with this as our initial approach but want to note that, to me, it feels a bit harder to associate the header with the data than other examples in this thread because of our lack of vertical lines separating the columns. While I recognize it's not my area of expertise or decision to make, is there anything we could do visually to increase the association between the column and its header in that case? e.g. Subtle background colors? Always showing the header dividers? @RickA-NI

**Comment by jattasNI** [comment]
We decided in a team meeting to start with  "Numeric headers left aligned, values right-aligned". The concern above will likely be moot if users size their columns to match their data; there won't be large amouts of whitespace which cause headers to be far from their content. We can always revisit this if it turns out to be a faulty assumption.

**Comment by jattasNI** [comment]
Note from Rick in response to a question from Molly in a team meeting: if the content is mixed data type (e.g. an SLE tag column with strings and numbers) then it should be left aligned.

**Comment by RickA-NI** [comment]
@jattasNI I know that this has been closed but I did come across an pretty indepth breakdown of how to format a table for scientific and technical publication. This is for print so there are some things we might do differently, but this section seems pertinent to your last question:
![image](https://user-images.githubusercontent.com/104936907/224857839-767d285f-16ad-4ae9-98b7-9bc8f7c637c1.png)
