### ISSUE TITLE
Design for tooltips in table

### ISSUE THREAD

**Issue by nate-ni** [ni/nimble#889]
## 😯 Problem to Solve
There are two known instances where we would provide tooltips for the end user.
1. When content is truncated
2. When the developer wants to display extra content to support the content in the cell (for example, explaining the meaning of an icon)

## 💁 Proposed Solution
[Fred Visser - 03/01/2023] Per team meeting today, the current proposal is to add a `title` attribute to the cell content, and not to depend on the `nimble-tooltip`.

## 🤔 Open Questions
1. Are there other instances we need to define?
3. Is a design for this needed?

## 🖼️ References/Prior Art
**Example of extra information being used in a tooltip**

![Image](https://user-images.githubusercontent.com/109235103/200389344-30a55713-3439-4825-b7ea-15ac69eaf37f.png)

**Comment by fredvisser** [comment]
![Image](https://github.com/ni/nimble/assets/1458528/c5369da2-14d0-43dd-9491-28b70da85591)

The `title` attribute is fully supported for truncated column text (☝️) and the [icon column](https://nimble.ni.dev/storybook/?path=/docs/components-table-column-icon--docs). Closing.
