### ISSUE TITLE
Design for hierarchical data support in tables

### ISSUE THREAD

**Issue by nate-ni** [ni/nimble#890]
## 😯 Problem to Solve
A design is needed to define how hierarchical data support will appear in the nimble table.

## 🤔 Open Questions/Considerations
- Data will be n-levels deep.
- Different levels may have different columns
   - guidance about always showing all columns vs. "table in a table" vs. other approaches
   - guidance about how the end user can configure which columns should be shown at each level (and how to prevent a user from hiding all the columns at a particular level)
- Need to be able to collapse all (this design will likely already be done)
- Do we need "roll-up" counts in this case, like we intend for "grouping"?
- Should we allow "grouping" and "hierarchy" at the same time in the same table? Which one is at the top level?
   - we believe TanStack will easily support grouping as the "top level" with hierarchy as the last level below it
- fetching items for a sub-level might take some time so showing a progress indicator is likely useful
   - we should consider the corner case when the fetch fails - do we need to show an error in line or rely on existing app-wide error reporting mechanisms?
- What does selection mean for a parent row? There are likely use cases for selecting just the parent row (and not all the children), but should there be some way to select-all for a parent?

## 🖼️ References/Prior Art
![Image](https://user-images.githubusercontent.com/109235103/200389498-b34805b6-07f3-4b07-a783-c0696d56e139.png)

[Video of SLE Steps use case](https://nio365.sharepoint.com/:v:/s/ASWSystemLink/EaIA-u9rRzNKgteD_BnVRPEBQKq8rYOr8kU6ymQ5f_P_PQ?e=ce0MMk)

**Comment by jattasNI** [comment]
Existing SLE use cases:
1. [Tags](https://test.lifecyclesolutions.ni.com/tags/)
2. [Steps](https://test.lifecyclesolutions.ni.com/testinsights/results) then click a result row and look at the Steps tab
3. Specs - still behind a feature flag

**Comment by fredvisser** [comment]
@atmgrifter00 - Just checking on this…

1. I see the loading spinner in the [Figma doc](https://www.figma.com/file/PO9mFOu5BCl8aJvFchEeuN/Nimble_Components?type=design&node-id=5629-46871&mode=design&t=nX6LmHvqWou7CWfl-4)
2. I don't see any table error state designs yet. I assume that'll block the delivery of this feature? I.e. We should prioritize this visual/IxD design?

**Comment by atmgrifter00** [comment]
@jattasNI @fredvisser I'm not sure the absence of error state designs blocks delivery of the feature, as I don't believe it's needed to cover existing capabilities. I believe this is more representative of a feature that we think would be ideal, but there is a lot of FUD around what the actual IX/UX would be for this.

**Comment by fredvisser** [comment]
@fredvisser - TODO: Rewrite to include only the error state design.

**Comment by fredvisser** [comment]
Upon further reflection, we should rely on the existing app-wide error notification UX for any issues loading row content. Closing this visual design request.
