### ISSUE TITLE
Design for action menu in a table

### ISSUE THREAD

**Issue by nate-ni** [ni/nimble#891]
## 😯 Problem to Solve
There is a need to show an action menu within a cell of the table.

This issue is for the UX design. For implementation see:
- #859 

## 🤔 Open Questions
1. Should the icon for this action menu be consistent with the icon for the table header cell action menu?
2. Do we leave "dead space" for the action menu, when enabled for a cell, or do we adjust the cell contents only when hovered? 
    - This may, as an example, truncate text during hover.

**Worth considering:**
This might be addressed (also/in lieu of) by providing right-click functionality.
Right-click access is/ is becoming common in many web apps:
- Most Canvas apps (Figma, Mural, Excalidraw as some examples)
- Table apps (AirTable)
- The file browsing part of many web apps (AzDO, Figma, Mural, O365, and more)

## 🖼️ References/Prior Art
**Example of action menu sharing space with content**
![image](https://user-images.githubusercontent.com/109235103/205911141-88454b9a-5ba6-4187-95d1-9f7322bfbf84.png)
![image](https://user-images.githubusercontent.com/109235103/205911195-2e26d2ec-e91c-410f-869c-10b381aef64c.png)

**Comment by leslieab** [comment]
[IxD](https://xd.adobe.com/view/6febf578-c381-466d-4d2f-98e004ff1d09-19da/) document (password is UXDesign1)

**Comment by nate-ni** [comment]
## Questions that were addressed
How does interacting with the menu affect the row?
- Does opening the menu select the row? 
- Does it de-select other existing selections?

How does interacting with the row affect the menu?
- Do we leave “dead space” or adjust content in cell?When/in what state is the menu button visible?

How is menu button visibility affected by focus state and keyboard navigation?
- Does the menu button appear if cell content is focused? If not, is the menu accessible via keyboard navigation when/if the button is hidden?

Are there alternative/additional interactions to open the menu?

**Comment by nate-ni** [comment]
@leslieab, I thought the original thoughts were to not do the context menu but I might be mis-remembering? 

Are you recommending we provide that, or is it in the design just as an exploration?

**Comment by leslieab** [comment]
@nate-ni I don't really understand what you mean. How are you differentiating between the action menu and the context menu?

**Comment by nate-ni** [comment]
@RickA-NI, looking at the design doc from Leslie is there any visual design spec info you need to provide.

For the icon, I think we would use `nimble-icon-three-dots-line`
The menu, itself, would just be the same as a `nimble-menu`

Is there anything you think is needed from visual design?

**Comment by nate-ni** [comment]
Fair point, sorry. I mean invoking the action menu via a button vs. right-click.



> @nate-ni I don't really understand what you mean. How are you differentiating between the action menu and the context menu?

Fair point, sorry. I mean invoking the action menu via right-click. I was using context menu to mean "right-click menu"...but they are both contextual menus. I should have just said accessing the action menu via right-click.

**Comment by mollykreis** [comment]
@nate-ni, @RickA-NI - One question for visual design is what size should the button be? By default the button is 32x32, but the interaction wireframes show the button being smaller than the row height (which right now is also 32px). In some places, such as [putting a button within a text field](https://nimble.ni.dev/storybook/?path=/story/text-field--underline-text-field&args=appearance:outline;actionButton:true), we use a 24x24 button.

**Comment by leslieab** [comment]
> Fair point, sorry. I mean invoking the action menu via right-click. I was using context menu to mean "right-click menu"...but they are both contextual menus. I should have just said accessing the action menu via right-click.

It's not an uncommon pattern and it only adds value, so I decided to include it. It's fine if we decide not to implement it (the developers mentioned it might be somewhat difficult), but it's "nice to have".

**Comment by nate-ni** [comment]
> It's not an uncommon pattern and it only adds value, so I decided to include it. It's fine if we decide not to implement it (the developers mentioned it might be somewhat difficult), but it's "nice to have".

Gotcha. Thanks for following up. I have captured the implemenation of that interaction in #1018

**Comment by RickA-NI** [comment]
I was hoping we could not use smaller special sized controls in the table rows. Brandon and I talked this over and we think this will lead to issues down the road. It's only a matter of time before someone wants a 24px tall row height and now we have to come up with a 16px tall button with new iconopgraphy. So the only tweak I would make would be to use the standard 32px button instead of that 24px button

**Comment by nate-ni** [comment]
Known open questions have been resolved and this design is complete.
