### ISSUE TITLE
Design for pinned/frozen column

### ISSUE THREAD

**Issue by nate-ni** [ni/nimble#892]
## 😯 Problem to Solve
This is a development configuration freezing the first/last column (or first/last **_n_** columns) in a table. This is helpful when a table is very wide and the first column should remain visible when horizontally scrolling.

## 🤔 Open Questions
1. Have we enabled horizontal scrolling?
2. Do we need to be able to enable pinning for **_last_** columns?
   - It's not unheard of, but is this something we need?
   - https://material.angular.io/components/table/overview#sticky-rows-and-columns
3. Should there be an interactive version of this feature (so the end user can "pin/freeze" a column)?
4. What is the visual design when horizontally scrolling? Do non-frozen columns go behind frozen columns? If so what happens to parts of the table that are transparent (e.g. what stops you from seeing the non-frozen column text and hover visual through the transparent parts of the frozen column?) See [SLE PR for old table](https://dev.azure.com/ni/DevCentral/_git/Skyline/pullrequest/552222) for example of this.

## 🖼️ References/Prior Art
https://user-images.githubusercontent.com/109235103/205920352-456669aa-0586-466c-9792-9088c1d9a2dd.mov

**Comment by fredvisser** [comment]
Not prioritizing against current client requirements.
