### ISSUE TITLE
Design for pagination in tables

### ISSUE THREAD

**Issue by nate-ni** [ni/nimble#894]
## 😯 Problem to Solve
Some tables need to be able to provide pagination controls for their user.
The location of this pagination may vary across apps and their needs.
 - Top
 - Bottom
 - Both
The pagination options will also vary across apps (items per page, go to page, etc.)

## 💁 Proposed Solution
1. How many options to provide in this first iteration?

**Comment by fredvisser** [comment]
Closing as low ROI
