### ISSUE TITLE
Spinner design followup (PowerGreen only vs. changeable color)

### ISSUE THREAD

**Issue by msmithNI** [ni/nimble#916]
## 😯 Problem to Solve

Followup from #822 for #346 

The [XD design](https://xd.adobe.com/view/33ffad4a-eb2c-4241-b8c5-ebfff1faf6f6-66ac/) for the spinner has a "Color UI Alt" version that makes the spinning bits the PowerGreen color. There's discussion/ an open question in #837 on how we should expose that variant:
- Have we shipped apps using that color variant already / do we already have specific apps in mind that will use that specific color for a spinner? (Brandon to answer this)
- Do we instead need a more general way for apps to provide an arbitrary/custom color for the spinner, to match their app theme/ background?
   - Dev note: In this case, we'd make a new token like `spinner-color` that can be overridden, and follow the same patterns we did for the icon colors which also allow overrides.

**Comment by NIbokeefe** [comment]
I'm still looking into where the power-green color scheme has been used.

I created an update to the design spec including additional sizes for the "bits-squares."

Sizes now include:

16, 32, 48, 96, 128

**Comment by NIbokeefe** [comment]
We'll move forward without the Powergreen version of the bits spinner.  I have not found where it's implemented.

**Comment by nate-ni** [comment]
Also, we have returned to the original sizes with 16, 32, 64.
