### ISSUE TITLE
Using external design tokens with the nimble components

### ISSUE THREAD

**Issue by git-anurag-hub** [ni/nimble#934]
# 🎙 Discussion

I wanted to use my own suite of design tokens with nimble components. What I have is the suite of tokens generated with the help of the style dictionary. I really liked the nimble design but wanted to apply my own touch to them.
Also I there a way for me to choose some specific tokens rather than using the whole generated token file?

**Comment by jattasNI** [comment]
@git-anurag-hub I would love to hear some more detail about your use case. Our general philosophy so far has been not to provide too many ways for clients to customize the appearance of Nimble components as that can lead to inconsistencies between NI apps, which goes against one of the main goals of Nimble.

However there are probably good reasons to allow what you're requesting. Then the question would be what mechanism we'd want to expose. More details would help us decide that.

1. Are there specific components/fonts/colors/sizes you want to be able to change?
2. Is there a larger goal behind your request? For example, exposing the ability for an app to to apply a different brand color? Or adding a new theme?
