### ISSUE TITLE
Resolve label accessibility errors

### ISSUE THREAD

**Issue by fredvisser** [ni/nimble#94]
The Select component is called out for not having ARIA values for several attributes, including labels –

![Screen Shot 2021-09-02 at 10 18 20 AM](https://user-images.githubusercontent.com/1458528/131891182-8c28a117-dd19-4aa7-b4a6-c51cc1460696.png)

However, FAST is still developing a strategy for labels within components (https://github.com/microsoft/fast/issues/4801), so we should resolve the accessibility & label issues when the above issue is resolved.

**Comment by rajsite** [comment]
More discussion around having labels associated with controls as being a good default: https://twitter.com/claviska/status/1677469942394900480?s=20

**Comment by jattasNI** [comment]
A couple clients mentioned wanting this recently: [LiMo in a Teams thread](https://teams.microsoft.com/l/message/19:wo8vmMKMsHfltKXxc0bczZo-X4JlQSV5VxpaRJdh13k1@thread.tacv2/1695654013481?tenantId=87ba1f9a-44cd-43a6-b008-6fdb45a5204e&groupId=9ee065d7-3898-4245-82f6-76e86084b8b1&parentMessageId=1695654013481&teamName=Design%20System&channelName=General&createdTime=1695654013481) and TestHub in a meeting.

**Comment by jattasNI** [comment]
Fixing this should help prevent bugs like this, where the "Workspace" select is disabled but its label isn't. We should validate that this behaves correctly when we fix this issue. This example comes from the [SLE Edit Asset slidein](https://test.lifecyclesolutions.ni.com/assets/3f43450b-259d-4ade-95b7-b3cf64bd4703/history)
![image](https://github.com/ni/nimble/assets/10500124/195e0e7a-38cf-487d-86da-f3bca87e5f64)

**Comment by msmithNI** [comment]
Select component has built-in label support as of #2315 - [Select story](https://nimble.ni.dev/storybook/?path=/story/components-select--select) no longer shows accessibility violations.
