### ISSUE TITLE
How to determine remaining third party elements to replace in SLE?

### ISSUE THREAD

**Issue by nate-ni** [ni/nimble#942]
# 🎙 Discussion
We have identified the JQX dependencies that are remaining (it would be good to verify that) but we there are other, non-Nimble, libraries being used that we should be providing Nimble version of. We should make sure we have an updated set of that information.

I'm just not sure how to categorize the work item to do this evaluation? Is it tech debt, enhancement, something else like "research"?

**Comment by m-akinc** [comment]
Consider delegating to app teams to tell us what they need replaced.
