### ISSUE TITLE
Wafer map event listener not removed correctly

### ISSUE THREAD

**Issue by jattasNI** [ni/nimble#964]
# 🐛 Bug Report

In #923 the wafer map added a new event listener that isn't being cleaned up correctly. See this comment thread: https://github.com/ni/nimble/pull/923/files/55d84f9c37d9e0c07c3831a5b9e4b61c4f7d5327#r1068536429

## 🤔 Expected Behavior

Only ever a single event listener per wafer map

## 😯 Current Behavior

More event listeners added when a wafer map is re-added to the page.

## 💁 Possible Solution

Save the event listener to a class member variable and pass that variable to both addEventListener and removeEventListener.

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* Version [e.g. 1.8.0]

**Comment by rajsite** [comment]
Looks like this will be addressed by #1005 but not closing yet as it is still in review and subject to change

**Comment by munteannatan** [comment]
The event listeners are removed at the beginning of each render cycle [here](https://github.com/ni/nimble/blob/b39cac6d5651afee85bd9f5e18c91d2e7ad17503/packages/nimble-components/src/wafer-map/index.ts#L180). The function listeners are stored in the private properties of the `EventCoordinator`.
