### ISSUE TITLE
Provide ability to display merged cells

### ISSUE THREAD

**Issue by nate-ni** [ni/nimble#970]
## 😯 Problem to Solve
There is an existing need to display merged cells within the table. In this case it is for cells which span multiple rows.

Example:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/109235103/212991233-4fb7fc56-7dbe-4a43-a3ab-0b6c36aa78ae.png)

![image](https://user-images.githubusercontent.com/109235103/212992276-63e2e36e-53bf-4bf3-925f-7117f8cb34dd.png)

**Comment by fredvisser** [comment]
Not prioritized against current client requirements.
