### ISSUE TITLE
Provide validation APIs/implementation for TableColumn

### ISSUE THREAD

**Issue by atmgrifter00** [ni/nimble#973]
## 📌 User Story

As discussed in the description for PR #947, we left out the API for validating cell data, as there are some questions that need to be answered for properly implementing and testing the desired API. Namely, what is the consequence of data that fails validation? Is there a visual consequence (beyond displaying nothing for that cell, for example, coloring a cell border red), or are we simply updating the `TableValidity` state with this information (or not even that)?

Ultimately, addressing this User Story should involve the implementation of the `validateCellData` API as described in the [spec.](https://github.com/ni/nimble/blob/main/packages/nimble-components/src/table/specs/table-columns-hld.md#tablecolumn). The remaining implementation question is simply what happens as a result of calling that method.

**Comment by jattasNI** [comment]
@atmgrifter00 can you provide some examples of invalid configuration? Is invalidity an indication that the table was configured incorrectly or that the data had unexpected values? If users hit this is it an indication of a bug or is this a case we'd expect users to hit?

**Comment by atmgrifter00** [comment]
> @atmgrifter00 can you provide some examples of invalid configuration? Is invalidity an indication that the table was configured incorrectly or that the data had unexpected values? If users hit this is it an indication of a bug or is this a case we'd expect users to hit?

The main case I can think of is where the data being given to a cell of a column is of an unexpected/unsupported type (i.e. a numeric given to a text column). So, no, I don't expect this will ever be indicative of a bug, just invalid configuration.

**Comment by jattasNI** [comment]
I believe we've reached consensus that invalid configuration is reflected in the existing validity API on the table and that invalid data will be handled per-column as blank cells or cells with placeholder text. Marking this as closed, but we can re-open if there's more to do.
