### ISSUE TITLE
Allow dynamic and non-text header content for TableColumn

### ISSUE THREAD

**Issue by atmgrifter00** [ni/nimble#974]
## 📌 User Story

One of the concessions made in PR #947 was only allowing static text content for column headers. Ultimately we want to support dynamic, and non-text content for headers as described in [one of the PR comments](https://github.com/ni/nimble/pull/947#discussion_r1066431222).

## Related PRs
- #1016

**Comment by jattasNI** [comment]
This might be a duplicate of #862 but I'll let @m-akinc @atmgrifter00 or @nate-ni decide that.

**Comment by atmgrifter00** [comment]
> This might be a duplicate of #862 but I'll let @m-akinc @atmgrifter00 or @nate-ni decide that.

This is indeed a duplicate. Closing.
