### ISSUE TITLE
Update TableValidity with new state when TableColumn improperly configured

### ISSUE THREAD

**Issue by atmgrifter00** [ni/nimble#979]
## 📌 User Story

It's quite possible for a particular TableColumn implementation to be configured improperly (as discussed in [this PR comment](https://github.com/ni/nimble/pull/947#discussion_r1068846726)). For instance if a requested field in a row of data does not exists (e.g. the provided `fieldName` of a `TableColumnText` does not exist in the data). In such a case it seems appropriate to update the `TableValidity` state indicating such a problem.

**Comment by jattasNI** [comment]
Similar to #973, I believe we'vre reached consensus that invalid configuration is reflected in the existing validity API on the table and that invalid data will be handled per-column as blank cells or cells with placeholder text. Marking this as closed, but we can re-open if there's more to do.
