### ISSUE TITLE
Chromatic detects changes in spinner stories

### ISSUE THREAD

**Issue by mollykreis** [ni/nimble#983]
# 🐛 Bug Report

Chromatic intermittently detects changes in the spinner stories when nothing has changed with the spinner's styling. It appears that the animation is running during those tests, which causes the snapshot to be taken at slightly different points within the animation.

## 🤔 Expected Behavior

The spinner snapshot should be consistent when no changes are made to it.

## 😯 Current Behavior

Spinner changes are detected by Chromatic when nothing has changed.

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* Version [e.g. 1.8.0]

```[tasklist]
## Related PRs
- [ ] #1019 
```

**Comment by jattasNI** [comment]
Here's one build where this occurred: https://www.chromatic.com/test?appId=60e89457a987cf003efc0a5b&id=63c8778cf800826a28d41e94

We chatted with our Chromatic rep today and she said she'd pass it along to their dev team and get back to us. According to [Chromatic's docs on animations](https://www.chromatic.com/docs/animations), CSS animations should be paused.
