### ISSUE TITLE
gantt chart component

### ISSUE THREAD

**Issue by nate-ni** [ni/nimble#991]
## 😯 Problem to Solve
There is a client need for a gantt chart component.

**Comment by bmarkov** [comment]
Hi, we may be able to help with a Gantt chart component development, if you need.

**Comment by rajsite** [comment]
Current SLE decision is to use the [third party mobiscroll control](https://ni.visualstudio.com/DevCentral/_git/Skyline?path=/docs/design-documents/Lab-Management/Calendar-workflow-library-decision.md&_a=preview).
